# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qt_test.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(996, 542)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 0, 981, 511))
        self.MainDisplay = QWidget()
        self.MainDisplay.setObjectName(u"MainDisplay")
        self.Block1 = QLineEdit(self.MainDisplay)
        self.Block1.setObjectName(u"Block1")
        self.Block1.setGeometry(QRect(10, 140, 51, 21))
        self.Block1.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block2 = QLineEdit(self.MainDisplay)
        self.Block2.setObjectName(u"Block2")
        self.Block2.setGeometry(QRect(60, 140, 51, 21))
        self.Block2.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block5 = QLineEdit(self.MainDisplay)
        self.Block5.setObjectName(u"Block5")
        self.Block5.setGeometry(QRect(210, 140, 51, 21))
        self.Block5.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block6 = QLineEdit(self.MainDisplay)
        self.Block6.setObjectName(u"Block6")
        self.Block6.setGeometry(QRect(260, 120, 51, 21))
        self.Block6.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block7 = QLineEdit(self.MainDisplay)
        self.Block7.setObjectName(u"Block7")
        self.Block7.setGeometry(QRect(300, 100, 51, 21))
        self.Block7.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block8 = QLineEdit(self.MainDisplay)
        self.Block8.setObjectName(u"Block8")
        self.Block8.setGeometry(QRect(340, 80, 51, 21))
        self.Block8.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block4 = QLineEdit(self.MainDisplay)
        self.Block4.setObjectName(u"Block4")
        self.Block4.setGeometry(QRect(160, 140, 51, 21))
        self.Block4.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block3 = QLineEdit(self.MainDisplay)
        self.Block3.setObjectName(u"Block3")
        self.Block3.setGeometry(QRect(110, 140, 51, 21))
        self.Block3.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block14 = QLineEdit(self.MainDisplay)
        self.Block14.setObjectName(u"Block14")
        self.Block14.setGeometry(QRect(380, 220, 51, 21))
        self.Block14.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block13 = QLineEdit(self.MainDisplay)
        self.Block13.setObjectName(u"Block13")
        self.Block13.setGeometry(QRect(340, 200, 51, 21))
        self.Block13.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block12 = QLineEdit(self.MainDisplay)
        self.Block12.setObjectName(u"Block12")
        self.Block12.setGeometry(QRect(300, 180, 51, 21))
        self.Block12.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block11 = QLineEdit(self.MainDisplay)
        self.Block11.setObjectName(u"Block11")
        self.Block11.setGeometry(QRect(260, 160, 51, 21))
        self.Block11.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block10 = QLineEdit(self.MainDisplay)
        self.Block10.setObjectName(u"Block10")
        self.Block10.setGeometry(QRect(410, 40, 51, 21))
        self.Block10.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block9 = QLineEdit(self.MainDisplay)
        self.Block9.setObjectName(u"Block9")
        self.Block9.setGeometry(QRect(380, 60, 51, 21))
        self.Block9.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.Block15 = QLineEdit(self.MainDisplay)
        self.Block15.setObjectName(u"Block15")
        self.Block15.setGeometry(QRect(410, 240, 51, 21))
        self.Block15.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.keyBlockGreen = QLineEdit(self.MainDisplay)
        self.keyBlockGreen.setObjectName(u"keyBlockGreen")
        self.keyBlockGreen.setGeometry(QRect(20, 30, 51, 21))
        self.keyBlockGreen.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.keyBlockRed = QLineEdit(self.MainDisplay)
        self.keyBlockRed.setObjectName(u"keyBlockRed")
        self.keyBlockRed.setGeometry(QRect(20, 60, 51, 21))
        self.keyBlockRed.setStyleSheet(u"background-color: rgb(255, 0, 0)")
        self.keyLabelGreen = QLabel(self.MainDisplay)
        self.keyLabelGreen.setObjectName(u"keyLabelGreen")
        self.keyLabelGreen.setGeometry(QRect(80, 30, 71, 16))
        self.keyLabelRed = QLabel(self.MainDisplay)
        self.keyLabelRed.setObjectName(u"keyLabelRed")
        self.keyLabelRed.setGeometry(QRect(80, 60, 71, 16))
        self.yardLabel = QLabel(self.MainDisplay)
        self.yardLabel.setObjectName(u"yardLabel")
        self.yardLabel.setGeometry(QRect(20, 120, 41, 16))
        self.stationBLabel = QLabel(self.MainDisplay)
        self.stationBLabel.setObjectName(u"stationBLabel")
        self.stationBLabel.setGeometry(QRect(400, 20, 71, 16))
        self.stationCLabel = QLabel(self.MainDisplay)
        self.stationCLabel.setObjectName(u"stationCLabel")
        self.stationCLabel.setGeometry(QRect(400, 260, 71, 16))
        self.junction511 = QLineEdit(self.MainDisplay)
        self.junction511.setObjectName(u"junction511")
        self.junction511.setGeometry(QRect(230, 170, 31, 21))
        self.junction511.setStyleSheet(u"background-color: rgb(0, 170, 0)")
        self.junction56 = QLineEdit(self.MainDisplay)
        self.junction56.setObjectName(u"junction56")
        self.junction56.setGeometry(QRect(230, 110, 31, 21))
        self.junction56.setStyleSheet(u"background-color: rgb(255,0, 0)")
        self.switchJunctionLabel = QLabel(self.MainDisplay)
        self.switchJunctionLabel.setObjectName(u"switchJunctionLabel")
        self.switchJunctionLabel.setGeometry(QRect(540, 60, 111, 41))
        font = QFont()
        font.setPointSize(12)
        self.switchJunctionLabel.setFont(font)
        self.button56 = QPushButton(self.MainDisplay)
        self.button56.setObjectName(u"button56")
        self.button56.setGeometry(QRect(550, 110, 81, 24))
        self.button511 = QPushButton(self.MainDisplay)
        self.button511.setObjectName(u"button511")
        self.button511.setGeometry(QRect(550, 160, 81, 24))
        self.orLabel = QLabel(self.MainDisplay)
        self.orLabel.setObjectName(u"orLabel")
        self.orLabel.setGeometry(QRect(580, 140, 16, 16))
        self.lightsLabel = QLabel(self.MainDisplay)
        self.lightsLabel.setObjectName(u"lightsLabel")
        self.lightsLabel.setGeometry(QRect(760, 40, 111, 81))
        self.lightsLabel.setFont(font)
        self.warningLightsLabel = QLabel(self.MainDisplay)
        self.warningLightsLabel.setObjectName(u"warningLightsLabel")
        self.warningLightsLabel.setGeometry(QRect(740, 110, 61, 61))
        font1 = QFont()
        font1.setPointSize(10)
        self.warningLightsLabel.setFont(font1)
        self.warningLightsCheckBox = QCheckBox(self.MainDisplay)
        self.warningLightsCheckBox.setObjectName(u"warningLightsCheckBox")
        self.warningLightsCheckBox.setGeometry(QRect(840, 130, 51, 20))
        self.warningLightsCheckBox.setFont(font1)
        self.crossingGatesLabel = QLabel(self.MainDisplay)
        self.crossingGatesLabel.setObjectName(u"crossingGatesLabel")
        self.crossingGatesLabel.setGeometry(QRect(740, 170, 61, 61))
        self.crossingGatesLabel.setFont(font1)
        self.crossingGatesCheckBox = QCheckBox(self.MainDisplay)
        self.crossingGatesCheckBox.setObjectName(u"crossingGatesCheckBox")
        self.crossingGatesCheckBox.setGeometry(QRect(840, 190, 51, 20))
        self.crossingGatesCheckBox.setFont(font1)
        self.trainDisplayTabWidget = QTabWidget(self.MainDisplay)
        self.trainDisplayTabWidget.setObjectName(u"trainDisplayTabWidget")
        self.trainDisplayTabWidget.setGeometry(QRect(560, 290, 321, 151))
        self.train1 = QWidget()
        self.train1.setObjectName(u"train1")
        self.indTrainSuggestedSpeedLabel = QLabel(self.train1)
        self.indTrainSuggestedSpeedLabel.setObjectName(u"indTrainSuggestedSpeedLabel")
        self.indTrainSuggestedSpeedLabel.setGeometry(QRect(20, 20, 101, 16))
        self.indTrainAuthorityLabel = QLabel(self.train1)
        self.indTrainAuthorityLabel.setObjectName(u"indTrainAuthorityLabel")
        self.indTrainAuthorityLabel.setGeometry(QRect(20, 60, 71, 16))
        self.indTrainSuggestedSpeedDisplay = QLineEdit(self.train1)
        self.indTrainSuggestedSpeedDisplay.setObjectName(u"indTrainSuggestedSpeedDisplay")
        self.indTrainSuggestedSpeedDisplay.setGeometry(QRect(150, 20, 91, 21))
        self.indTrainAuthorityDisplay = QLineEdit(self.train1)
        self.indTrainAuthorityDisplay.setObjectName(u"indTrainAuthorityDisplay")
        self.indTrainAuthorityDisplay.setGeometry(QRect(150, 60, 91, 21))
        self.mphUnitLabel = QLabel(self.train1)
        self.mphUnitLabel.setObjectName(u"mphUnitLabel")
        self.mphUnitLabel.setGeometry(QRect(250, 20, 31, 16))
        self.ftUnitLabel = QLabel(self.train1)
        self.ftUnitLabel.setObjectName(u"ftUnitLabel")
        self.ftUnitLabel.setGeometry(QRect(250, 60, 21, 16))
        self.trainDisplayTabWidget.addTab(self.train1, "")
        self.train2 = QWidget()
        self.train2.setObjectName(u"train2")
        self.indTrainSuggestedSpeedLabel_2 = QLabel(self.train2)
        self.indTrainSuggestedSpeedLabel_2.setObjectName(u"indTrainSuggestedSpeedLabel_2")
        self.indTrainSuggestedSpeedLabel_2.setGeometry(QRect(20, 20, 101, 16))
        self.indTrainAuthorityLabel_2 = QLabel(self.train2)
        self.indTrainAuthorityLabel_2.setObjectName(u"indTrainAuthorityLabel_2")
        self.indTrainAuthorityLabel_2.setGeometry(QRect(20, 60, 71, 16))
        self.indTrainSuggestedSpeedDisplay_2 = QLineEdit(self.train2)
        self.indTrainSuggestedSpeedDisplay_2.setObjectName(u"indTrainSuggestedSpeedDisplay_2")
        self.indTrainSuggestedSpeedDisplay_2.setGeometry(QRect(150, 20, 91, 21))
        self.mphUnitLabel_2 = QLabel(self.train2)
        self.mphUnitLabel_2.setObjectName(u"mphUnitLabel_2")
        self.mphUnitLabel_2.setGeometry(QRect(250, 20, 31, 16))
        self.ftUnitLabel_2 = QLabel(self.train2)
        self.ftUnitLabel_2.setObjectName(u"ftUnitLabel_2")
        self.ftUnitLabel_2.setGeometry(QRect(250, 60, 21, 16))
        self.indTrainAuthorityDisplay_2 = QLineEdit(self.train2)
        self.indTrainAuthorityDisplay_2.setObjectName(u"indTrainAuthorityDisplay_2")
        self.indTrainAuthorityDisplay_2.setGeometry(QRect(150, 60, 91, 21))
        self.trainDisplayTabWidget.addTab(self.train2, "")
        self.train3 = QWidget()
        self.train3.setObjectName(u"train3")
        self.indTrainSuggestedSpeedLabel_3 = QLabel(self.train3)
        self.indTrainSuggestedSpeedLabel_3.setObjectName(u"indTrainSuggestedSpeedLabel_3")
        self.indTrainSuggestedSpeedLabel_3.setGeometry(QRect(20, 20, 101, 16))
        self.indTrainAuthorityLabel_3 = QLabel(self.train3)
        self.indTrainAuthorityLabel_3.setObjectName(u"indTrainAuthorityLabel_3")
        self.indTrainAuthorityLabel_3.setGeometry(QRect(20, 60, 71, 16))
        self.indTrainSuggestedSpeedDisplay_3 = QLineEdit(self.train3)
        self.indTrainSuggestedSpeedDisplay_3.setObjectName(u"indTrainSuggestedSpeedDisplay_3")
        self.indTrainSuggestedSpeedDisplay_3.setGeometry(QRect(150, 20, 91, 21))
        self.indTrainAuthorityDisplay_3 = QLineEdit(self.train3)
        self.indTrainAuthorityDisplay_3.setObjectName(u"indTrainAuthorityDisplay_3")
        self.indTrainAuthorityDisplay_3.setGeometry(QRect(150, 60, 91, 21))
        self.mphUnitLabel_3 = QLabel(self.train3)
        self.mphUnitLabel_3.setObjectName(u"mphUnitLabel_3")
        self.mphUnitLabel_3.setGeometry(QRect(250, 20, 31, 16))
        self.ftUnitLabel_3 = QLabel(self.train3)
        self.ftUnitLabel_3.setObjectName(u"ftUnitLabel_3")
        self.ftUnitLabel_3.setGeometry(QRect(250, 60, 21, 16))
        self.trainDisplayTabWidget.addTab(self.train3, "")
        self.controllerDisplayTabWidget = QTabWidget(self.MainDisplay)
        self.controllerDisplayTabWidget.setObjectName(u"controllerDisplayTabWidget")
        self.controllerDisplayTabWidget.setGeometry(QRect(10, 280, 531, 181))
        self.controller1 = QWidget()
        self.controller1.setObjectName(u"controller1")
        self.label = QLabel(self.controller1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(130, 10, 49, 16))
        self.label_2 = QLabel(self.controller1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(230, 10, 49, 16))
        self.label_3 = QLabel(self.controller1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(330, 10, 49, 16))
        self.label_4 = QLabel(self.controller1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(430, 10, 49, 16))
        self.label_8 = QLabel(self.controller1)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 50, 101, 16))
        self.label_9 = QLabel(self.controller1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 90, 91, 16))
        self.Block1controllerOcc = QLineEdit(self.controller1)
        self.Block1controllerOcc.setObjectName(u"Block1controllerOcc")
        self.Block1controllerOcc.setGeometry(QRect(110, 120, 71, 21))
        self.Block1controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block2controllerOcc = QLineEdit(self.controller1)
        self.Block2controllerOcc.setObjectName(u"Block2controllerOcc")
        self.Block2controllerOcc.setGeometry(QRect(210, 120, 71, 21))
        self.Block2controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block3controllerOcc = QLineEdit(self.controller1)
        self.Block3controllerOcc.setObjectName(u"Block3controllerOcc")
        self.Block3controllerOcc.setGeometry(QRect(310, 120, 71, 21))
        self.Block3controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block4controllerOcc = QLineEdit(self.controller1)
        self.Block4controllerOcc.setObjectName(u"Block4controllerOcc")
        self.Block4controllerOcc.setGeometry(QRect(410, 120, 71, 21))
        self.Block4controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.block1controllerSpeedLimitDisplay = QLineEdit(self.controller1)
        self.block1controllerSpeedLimitDisplay.setObjectName(u"block1controllerSpeedLimitDisplay")
        self.block1controllerSpeedLimitDisplay.setGeometry(QRect(110, 50, 71, 21))
        self.block2controllerSpeedLimitDisplay = QLineEdit(self.controller1)
        self.block2controllerSpeedLimitDisplay.setObjectName(u"block2controllerSpeedLimitDisplay")
        self.block2controllerSpeedLimitDisplay.setGeometry(QRect(210, 50, 71, 21))
        self.block3controllerSpeedLimitDisplay = QLineEdit(self.controller1)
        self.block3controllerSpeedLimitDisplay.setObjectName(u"block3controllerSpeedLimitDisplay")
        self.block3controllerSpeedLimitDisplay.setGeometry(QRect(310, 50, 71, 21))
        self.block4controllerSpeedLimitDisplay = QLineEdit(self.controller1)
        self.block4controllerSpeedLimitDisplay.setObjectName(u"block4controllerSpeedLimitDisplay")
        self.block4controllerSpeedLimitDisplay.setGeometry(QRect(410, 50, 71, 21))
        self.block1controllerBlockLengthDisplay = QLineEdit(self.controller1)
        self.block1controllerBlockLengthDisplay.setObjectName(u"block1controllerBlockLengthDisplay")
        self.block1controllerBlockLengthDisplay.setGeometry(QRect(110, 90, 71, 21))
        self.block2controllerBlockLengthDisplay = QLineEdit(self.controller1)
        self.block2controllerBlockLengthDisplay.setObjectName(u"block2controllerBlockLengthDisplay")
        self.block2controllerBlockLengthDisplay.setGeometry(QRect(210, 90, 71, 21))
        self.block3controllerBlockLengthDisplay = QLineEdit(self.controller1)
        self.block3controllerBlockLengthDisplay.setObjectName(u"block3controllerBlockLengthDisplay")
        self.block3controllerBlockLengthDisplay.setGeometry(QRect(310, 90, 71, 21))
        self.block4controllerBlockLengthDisplay = QLineEdit(self.controller1)
        self.block4controllerBlockLengthDisplay.setObjectName(u"block4controllerBlockLengthDisplay")
        self.block4controllerBlockLengthDisplay.setGeometry(QRect(410, 90, 71, 21))
        self.controllerDisplayTabWidget.addTab(self.controller1, "")
        self.controller2 = QWidget()
        self.controller2.setObjectName(u"controller2")
        self.label_10 = QLabel(self.controller2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 10, 49, 16))
        self.label_11 = QLabel(self.controller2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(230, 10, 49, 16))
        self.label_12 = QLabel(self.controller2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(330, 10, 49, 16))
        self.label_29 = QLabel(self.controller2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 50, 101, 16))
        self.label_32 = QLabel(self.controller2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 90, 91, 16))
        self.block5controllerSpeedLimitDisplay = QLineEdit(self.controller2)
        self.block5controllerSpeedLimitDisplay.setObjectName(u"block5controllerSpeedLimitDisplay")
        self.block5controllerSpeedLimitDisplay.setGeometry(QRect(110, 50, 71, 21))
        self.block6controllerSpeedLimitDisplay = QLineEdit(self.controller2)
        self.block6controllerSpeedLimitDisplay.setObjectName(u"block6controllerSpeedLimitDisplay")
        self.block6controllerSpeedLimitDisplay.setGeometry(QRect(210, 50, 71, 21))
        self.block11controllerSpeedLimitDisplay = QLineEdit(self.controller2)
        self.block11controllerSpeedLimitDisplay.setObjectName(u"block11controllerSpeedLimitDisplay")
        self.block11controllerSpeedLimitDisplay.setGeometry(QRect(310, 50, 71, 21))
        self.block5controllerBlockLengthDisplay = QLineEdit(self.controller2)
        self.block5controllerBlockLengthDisplay.setObjectName(u"block5controllerBlockLengthDisplay")
        self.block5controllerBlockLengthDisplay.setGeometry(QRect(110, 90, 71, 21))
        self.block6controllerBlockLengthDisplay = QLineEdit(self.controller2)
        self.block6controllerBlockLengthDisplay.setObjectName(u"block6controllerBlockLengthDisplay")
        self.block6controllerBlockLengthDisplay.setGeometry(QRect(210, 90, 71, 21))
        self.block11controllerBlockLengthDisplay = QLineEdit(self.controller2)
        self.block11controllerBlockLengthDisplay.setObjectName(u"block11controllerBlockLengthDisplay")
        self.block11controllerBlockLengthDisplay.setGeometry(QRect(310, 90, 71, 21))
        self.Block5controllerOcc = QLineEdit(self.controller2)
        self.Block5controllerOcc.setObjectName(u"Block5controllerOcc")
        self.Block5controllerOcc.setGeometry(QRect(110, 120, 71, 21))
        self.Block5controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block6controllerOcc = QLineEdit(self.controller2)
        self.Block6controllerOcc.setObjectName(u"Block6controllerOcc")
        self.Block6controllerOcc.setGeometry(QRect(210, 120, 71, 21))
        self.Block6controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block11controllerOcc = QLineEdit(self.controller2)
        self.Block11controllerOcc.setObjectName(u"Block11controllerOcc")
        self.Block11controllerOcc.setGeometry(QRect(310, 120, 71, 21))
        self.Block11controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.controllerDisplayTabWidget.addTab(self.controller2, "")
        self.controller3 = QWidget()
        self.controller3.setObjectName(u"controller3")
        self.label_13 = QLabel(self.controller3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 10, 49, 16))
        self.label_14 = QLabel(self.controller3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(230, 10, 49, 16))
        self.label_15 = QLabel(self.controller3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(330, 10, 49, 16))
        self.label_16 = QLabel(self.controller3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(430, 10, 49, 16))
        self.label_30 = QLabel(self.controller3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 50, 101, 16))
        self.label_33 = QLabel(self.controller3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 90, 101, 16))
        self.block7controllerSpeedLimitDisplay = QLineEdit(self.controller3)
        self.block7controllerSpeedLimitDisplay.setObjectName(u"block7controllerSpeedLimitDisplay")
        self.block7controllerSpeedLimitDisplay.setGeometry(QRect(110, 50, 71, 21))
        self.block8controllerSpeedLimitDisplay = QLineEdit(self.controller3)
        self.block8controllerSpeedLimitDisplay.setObjectName(u"block8controllerSpeedLimitDisplay")
        self.block8controllerSpeedLimitDisplay.setGeometry(QRect(210, 50, 71, 21))
        self.block9controllerSpeedLimitDisplay = QLineEdit(self.controller3)
        self.block9controllerSpeedLimitDisplay.setObjectName(u"block9controllerSpeedLimitDisplay")
        self.block9controllerSpeedLimitDisplay.setGeometry(QRect(310, 50, 71, 21))
        self.block10controllerSpeedLimitDisplay = QLineEdit(self.controller3)
        self.block10controllerSpeedLimitDisplay.setObjectName(u"block10controllerSpeedLimitDisplay")
        self.block10controllerSpeedLimitDisplay.setGeometry(QRect(410, 50, 71, 21))
        self.block7controllerBlockLengthDisplay = QLineEdit(self.controller3)
        self.block7controllerBlockLengthDisplay.setObjectName(u"block7controllerBlockLengthDisplay")
        self.block7controllerBlockLengthDisplay.setGeometry(QRect(110, 90, 71, 21))
        self.block8controllerBlockLengthDisplay = QLineEdit(self.controller3)
        self.block8controllerBlockLengthDisplay.setObjectName(u"block8controllerBlockLengthDisplay")
        self.block8controllerBlockLengthDisplay.setGeometry(QRect(210, 90, 71, 21))
        self.block9controllerBlockLengthDisplay = QLineEdit(self.controller3)
        self.block9controllerBlockLengthDisplay.setObjectName(u"block9controllerBlockLengthDisplay")
        self.block9controllerBlockLengthDisplay.setGeometry(QRect(310, 90, 71, 21))
        self.block10controllerBlockLengthDisplay = QLineEdit(self.controller3)
        self.block10controllerBlockLengthDisplay.setObjectName(u"block10controllerBlockLengthDisplay")
        self.block10controllerBlockLengthDisplay.setGeometry(QRect(410, 90, 71, 21))
        self.Block7controllerOcc = QLineEdit(self.controller3)
        self.Block7controllerOcc.setObjectName(u"Block7controllerOcc")
        self.Block7controllerOcc.setGeometry(QRect(110, 120, 71, 21))
        self.Block7controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block8controllerOcc = QLineEdit(self.controller3)
        self.Block8controllerOcc.setObjectName(u"Block8controllerOcc")
        self.Block8controllerOcc.setGeometry(QRect(210, 120, 71, 21))
        self.Block8controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block9controllerOcc = QLineEdit(self.controller3)
        self.Block9controllerOcc.setObjectName(u"Block9controllerOcc")
        self.Block9controllerOcc.setGeometry(QRect(310, 120, 71, 21))
        self.Block9controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block10controllerOcc = QLineEdit(self.controller3)
        self.Block10controllerOcc.setObjectName(u"Block10controllerOcc")
        self.Block10controllerOcc.setGeometry(QRect(410, 120, 71, 21))
        self.Block10controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.controllerDisplayTabWidget.addTab(self.controller3, "")
        self.controller4 = QWidget()
        self.controller4.setObjectName(u"controller4")
        self.label_31 = QLabel(self.controller4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 50, 101, 16))
        self.label_34 = QLabel(self.controller4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 90, 101, 16))
        self.label_35 = QLabel(self.controller4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(130, 10, 51, 16))
        self.label_36 = QLabel(self.controller4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(230, 10, 51, 16))
        self.label_37 = QLabel(self.controller4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(330, 10, 51, 16))
        self.label_38 = QLabel(self.controller4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(430, 10, 51, 16))
        self.block12controllerSpeedLimitDisplay = QLineEdit(self.controller4)
        self.block12controllerSpeedLimitDisplay.setObjectName(u"block12controllerSpeedLimitDisplay")
        self.block12controllerSpeedLimitDisplay.setGeometry(QRect(110, 50, 71, 21))
        self.block13controllerSpeedLimitDisplay = QLineEdit(self.controller4)
        self.block13controllerSpeedLimitDisplay.setObjectName(u"block13controllerSpeedLimitDisplay")
        self.block13controllerSpeedLimitDisplay.setGeometry(QRect(210, 50, 71, 21))
        self.block14controllerSpeedLimitDisplay = QLineEdit(self.controller4)
        self.block14controllerSpeedLimitDisplay.setObjectName(u"block14controllerSpeedLimitDisplay")
        self.block14controllerSpeedLimitDisplay.setGeometry(QRect(310, 50, 71, 21))
        self.block15controllerSpeedLimitDisplay = QLineEdit(self.controller4)
        self.block15controllerSpeedLimitDisplay.setObjectName(u"block15controllerSpeedLimitDisplay")
        self.block15controllerSpeedLimitDisplay.setGeometry(QRect(410, 50, 71, 21))
        self.block12controllerBlockLengthDisplay = QLineEdit(self.controller4)
        self.block12controllerBlockLengthDisplay.setObjectName(u"block12controllerBlockLengthDisplay")
        self.block12controllerBlockLengthDisplay.setGeometry(QRect(110, 90, 71, 21))
        self.Block12controllerOcc = QLineEdit(self.controller4)
        self.Block12controllerOcc.setObjectName(u"Block12controllerOcc")
        self.Block12controllerOcc.setGeometry(QRect(110, 120, 71, 21))
        self.Block12controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.block13controllerBlockLengthDisplay = QLineEdit(self.controller4)
        self.block13controllerBlockLengthDisplay.setObjectName(u"block13controllerBlockLengthDisplay")
        self.block13controllerBlockLengthDisplay.setGeometry(QRect(210, 90, 71, 21))
        self.block14controllerBlockLengthDisplay = QLineEdit(self.controller4)
        self.block14controllerBlockLengthDisplay.setObjectName(u"block14controllerBlockLengthDisplay")
        self.block14controllerBlockLengthDisplay.setGeometry(QRect(310, 90, 71, 21))
        self.block15controllerBlockLengthDisplay = QLineEdit(self.controller4)
        self.block15controllerBlockLengthDisplay.setObjectName(u"block15controllerBlockLengthDisplay")
        self.block15controllerBlockLengthDisplay.setGeometry(QRect(410, 90, 71, 21))
        self.Block13controllerOcc = QLineEdit(self.controller4)
        self.Block13controllerOcc.setObjectName(u"Block13controllerOcc")
        self.Block13controllerOcc.setGeometry(QRect(210, 120, 71, 21))
        self.Block13controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block14controllerOcc = QLineEdit(self.controller4)
        self.Block14controllerOcc.setObjectName(u"Block14controllerOcc")
        self.Block14controllerOcc.setGeometry(QRect(310, 120, 71, 21))
        self.Block14controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.Block15controllerOcc = QLineEdit(self.controller4)
        self.Block15controllerOcc.setObjectName(u"Block15controllerOcc")
        self.Block15controllerOcc.setGeometry(QRect(410, 120, 71, 21))
        self.Block15controllerOcc.setStyleSheet(u"background-color: rgb(0,170, 0)")
        self.controllerDisplayTabWidget.addTab(self.controller4, "")
        self.tabWidget.addTab(self.MainDisplay, "")
        self.Test_tab = QWidget()
        self.Test_tab.setObjectName(u"Test_tab")
        self.inputLabel = QLabel(self.Test_tab)
        self.inputLabel.setObjectName(u"inputLabel")
        self.inputLabel.setGeometry(QRect(100, 40, 141, 61))
        font2 = QFont()
        font2.setPointSize(14)
        self.inputLabel.setFont(font2)
        self.outputLabel = QLabel(self.Test_tab)
        self.outputLabel.setObjectName(u"outputLabel")
        self.outputLabel.setGeometry(QRect(560, 40, 171, 71))
        self.outputLabel.setFont(font2)
        self.trainNumberLabel = QLabel(self.Test_tab)
        self.trainNumberLabel.setObjectName(u"trainNumberLabel")
        self.trainNumberLabel.setGeometry(QRect(70, 130, 81, 16))
        self.suggestedSpeedLabel = QLabel(self.Test_tab)
        self.suggestedSpeedLabel.setObjectName(u"suggestedSpeedLabel")
        self.suggestedSpeedLabel.setGeometry(QRect(70, 160, 131, 16))
        self.authorityLabel = QLabel(self.Test_tab)
        self.authorityLabel.setObjectName(u"authorityLabel")
        self.authorityLabel.setGeometry(QRect(70, 190, 131, 16))
        self.trainNumberInput = QLineEdit(self.Test_tab)
        self.trainNumberInput.setObjectName(u"trainNumberInput")
        self.trainNumberInput.setGeometry(QRect(210, 130, 91, 21))
        self.suggestedSpeedInput = QLineEdit(self.Test_tab)
        self.suggestedSpeedInput.setObjectName(u"suggestedSpeedInput")
        self.suggestedSpeedInput.setGeometry(QRect(210, 160, 91, 21))
        self.authorityInput = QLineEdit(self.Test_tab)
        self.authorityInput.setObjectName(u"authorityInput")
        self.authorityInput.setGeometry(QRect(210, 190, 91, 21))
        self.trainInputButton = QPushButton(self.Test_tab)
        self.trainInputButton.setObjectName(u"trainInputButton")
        self.trainInputButton.setGeometry(QRect(150, 220, 75, 24))
        self.blockNumberLabel = QLabel(self.Test_tab)
        self.blockNumberLabel.setObjectName(u"blockNumberLabel")
        self.blockNumberLabel.setGeometry(QRect(100, 260, 81, 16))
        self.blockLengthLabel = QLabel(self.Test_tab)
        self.blockLengthLabel.setObjectName(u"blockLengthLabel")
        self.blockLengthLabel.setGeometry(QRect(100, 290, 81, 16))
        self.speedLimitLabel = QLabel(self.Test_tab)
        self.speedLimitLabel.setObjectName(u"speedLimitLabel")
        self.speedLimitLabel.setGeometry(QRect(100, 320, 101, 16))
        self.blockNumberInput = QLineEdit(self.Test_tab)
        self.blockNumberInput.setObjectName(u"blockNumberInput")
        self.blockNumberInput.setGeometry(QRect(210, 260, 91, 21))
        self.blockLengthInput = QLineEdit(self.Test_tab)
        self.blockLengthInput.setObjectName(u"blockLengthInput")
        self.blockLengthInput.setGeometry(QRect(210, 290, 91, 21))
        self.speedLimitInput = QLineEdit(self.Test_tab)
        self.speedLimitInput.setObjectName(u"speedLimitInput")
        self.speedLimitInput.setGeometry(QRect(210, 320, 91, 21))
        self.blockInputButton = QPushButton(self.Test_tab)
        self.blockInputButton.setObjectName(u"blockInputButton")
        self.blockInputButton.setGeometry(QRect(150, 380, 75, 24))
        self.occupancyInput = QLineEdit(self.Test_tab)
        self.occupancyInput.setObjectName(u"occupancyInput")
        self.occupancyInput.setGeometry(QRect(210, 350, 91, 21))
        self.occupancyLabel = QLabel(self.Test_tab)
        self.occupancyLabel.setObjectName(u"occupancyLabel")
        self.occupancyLabel.setGeometry(QRect(100, 350, 91, 16))
        self.trainNumberSelectLabel = QLabel(self.Test_tab)
        self.trainNumberSelectLabel.setObjectName(u"trainNumberSelectLabel")
        self.trainNumberSelectLabel.setGeometry(QRect(520, 130, 111, 16))
        self.commandedSpeedLabel = QLabel(self.Test_tab)
        self.commandedSpeedLabel.setObjectName(u"commandedSpeedLabel")
        self.commandedSpeedLabel.setGeometry(QRect(520, 160, 141, 16))
        self.trainNumberSelectInput = QLineEdit(self.Test_tab)
        self.trainNumberSelectInput.setObjectName(u"trainNumberSelectInput")
        self.trainNumberSelectInput.setGeometry(QRect(660, 130, 91, 21))
        self.commandedSpeedDisplay = QLineEdit(self.Test_tab)
        self.commandedSpeedDisplay.setObjectName(u"commandedSpeedDisplay")
        self.commandedSpeedDisplay.setGeometry(QRect(660, 160, 91, 21))
        self.trainSelectButton = QPushButton(self.Test_tab)
        self.trainSelectButton.setObjectName(u"trainSelectButton")
        self.trainSelectButton.setGeometry(QRect(760, 130, 75, 24))
        self.blockNumberSelectLabel = QLabel(self.Test_tab)
        self.blockNumberSelectLabel.setObjectName(u"blockNumberSelectLabel")
        self.blockNumberSelectLabel.setGeometry(QRect(520, 230, 111, 16))
        self.occupancyDisplayLabel = QLabel(self.Test_tab)
        self.occupancyDisplayLabel.setObjectName(u"occupancyDisplayLabel")
        self.occupancyDisplayLabel.setGeometry(QRect(520, 270, 111, 16))
        self.blockNumberSelectInput = QLineEdit(self.Test_tab)
        self.blockNumberSelectInput.setObjectName(u"blockNumberSelectInput")
        self.blockNumberSelectInput.setGeometry(QRect(660, 230, 91, 21))
        self.occupancyDisplay = QLineEdit(self.Test_tab)
        self.occupancyDisplay.setObjectName(u"occupancyDisplay")
        self.occupancyDisplay.setGeometry(QRect(660, 270, 91, 21))
        self.blockSelectButton = QPushButton(self.Test_tab)
        self.blockSelectButton.setObjectName(u"blockSelectButton")
        self.blockSelectButton.setGeometry(QRect(760, 230, 75, 24))
        self.junctionPositionLabel = QLabel(self.Test_tab)
        self.junctionPositionLabel.setObjectName(u"junctionPositionLabel")
        self.junctionPositionLabel.setGeometry(QRect(520, 340, 111, 16))
        self.junctionPositionDisplay = QLineEdit(self.Test_tab)
        self.junctionPositionDisplay.setObjectName(u"junctionPositionDisplay")
        self.junctionPositionDisplay.setGeometry(QRect(660, 340, 91, 21))
        self.tabWidget.addTab(self.Test_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 996, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)
        self.trainDisplayTabWidget.setCurrentIndex(1)
        self.controllerDisplayTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Track Controller HW Demo", None))
        self.Block1.setText(QCoreApplication.translate("MainWindow", u"Block 1", None))
        self.Block2.setText(QCoreApplication.translate("MainWindow", u"Block 2", None))
        self.Block5.setText(QCoreApplication.translate("MainWindow", u"Block 5", None))
        self.Block6.setText(QCoreApplication.translate("MainWindow", u"Block 6", None))
        self.Block7.setText(QCoreApplication.translate("MainWindow", u"Block 7", None))
        self.Block8.setText(QCoreApplication.translate("MainWindow", u"Block 8", None))
        self.Block4.setText(QCoreApplication.translate("MainWindow", u"Block 4", None))
        self.Block3.setText(QCoreApplication.translate("MainWindow", u"Block 3", None))
        self.Block14.setText(QCoreApplication.translate("MainWindow", u"Block 14", None))
        self.Block13.setText(QCoreApplication.translate("MainWindow", u"Block 13", None))
        self.Block12.setText(QCoreApplication.translate("MainWindow", u"Block 12", None))
        self.Block11.setText(QCoreApplication.translate("MainWindow", u"Block 11", None))
        self.Block10.setText(QCoreApplication.translate("MainWindow", u"Block 10", None))
        self.Block9.setText(QCoreApplication.translate("MainWindow", u"Block 9", None))
        self.Block15.setText(QCoreApplication.translate("MainWindow", u"Block 15", None))
        self.keyBlockGreen.setText("")
        self.keyBlockRed.setText("")
        self.keyLabelGreen.setText(QCoreApplication.translate("MainWindow", u"Unoccupied", None))
        self.keyLabelRed.setText(QCoreApplication.translate("MainWindow", u"Occupied", None))
        self.yardLabel.setText(QCoreApplication.translate("MainWindow", u"Yard", None))
        self.stationBLabel.setText(QCoreApplication.translate("MainWindow", u"Station B", None))
        self.stationCLabel.setText(QCoreApplication.translate("MainWindow", u"Station C", None))
        self.junction511.setText(QCoreApplication.translate("MainWindow", u"5-11", None))
        self.junction56.setText(QCoreApplication.translate("MainWindow", u"5-6", None))
        self.switchJunctionLabel.setText(QCoreApplication.translate("MainWindow", u"Switch Junction?", None))
        self.button56.setText(QCoreApplication.translate("MainWindow", u"Connect 5-6", None))
        self.button511.setText(QCoreApplication.translate("MainWindow", u"Connect 5-11", None))
        self.orLabel.setText(QCoreApplication.translate("MainWindow", u"or", None))
        self.lightsLabel.setText(QCoreApplication.translate("MainWindow", u"Crossing Lights \n"
"   for Nearest \n"
"      Junction ", None))
        self.warningLightsLabel.setText(QCoreApplication.translate("MainWindow", u"Warning \n"
" Lights", None))
        self.warningLightsCheckBox.setText(QCoreApplication.translate("MainWindow", u"Y/N", None))
        self.crossingGatesLabel.setText(QCoreApplication.translate("MainWindow", u"Crossing \n"
" Gates", None))
        self.crossingGatesCheckBox.setText(QCoreApplication.translate("MainWindow", u"Y/N", None))
        self.indTrainSuggestedSpeedLabel.setText(QCoreApplication.translate("MainWindow", u"Suggested Speed", None))
        self.indTrainAuthorityLabel.setText(QCoreApplication.translate("MainWindow", u"Authority", None))
        self.mphUnitLabel.setText(QCoreApplication.translate("MainWindow", u"mph", None))
        self.ftUnitLabel.setText(QCoreApplication.translate("MainWindow", u"ft", None))
        self.trainDisplayTabWidget.setTabText(self.trainDisplayTabWidget.indexOf(self.train1), QCoreApplication.translate("MainWindow", u"Train 1", None))
        self.indTrainSuggestedSpeedLabel_2.setText(QCoreApplication.translate("MainWindow", u"Suggested Speed", None))
        self.indTrainAuthorityLabel_2.setText(QCoreApplication.translate("MainWindow", u"Authority", None))
        self.mphUnitLabel_2.setText(QCoreApplication.translate("MainWindow", u"mph", None))
        self.ftUnitLabel_2.setText(QCoreApplication.translate("MainWindow", u"ft", None))
        self.trainDisplayTabWidget.setTabText(self.trainDisplayTabWidget.indexOf(self.train2), QCoreApplication.translate("MainWindow", u"Train2", None))
        self.indTrainSuggestedSpeedLabel_3.setText(QCoreApplication.translate("MainWindow", u"Suggested Speed", None))
        self.indTrainAuthorityLabel_3.setText(QCoreApplication.translate("MainWindow", u"Authority", None))
        self.mphUnitLabel_3.setText(QCoreApplication.translate("MainWindow", u"mph", None))
        self.ftUnitLabel_3.setText(QCoreApplication.translate("MainWindow", u"ft", None))
        self.trainDisplayTabWidget.setTabText(self.trainDisplayTabWidget.indexOf(self.train3), QCoreApplication.translate("MainWindow", u"Train3", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Block1", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Block2", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Block3", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Block4", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Speed Limit (mph)", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Block Length (ft.)", None))
        self.Block1controllerOcc.setText("")
        self.Block2controllerOcc.setText("")
        self.Block3controllerOcc.setText("")
        self.Block4controllerOcc.setText("")
        self.controllerDisplayTabWidget.setTabText(self.controllerDisplayTabWidget.indexOf(self.controller1), QCoreApplication.translate("MainWindow", u"Controller 1", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Block5", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Block6", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Block11", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Speed Limit (mph)", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Block Length (ft.)", None))
        self.Block5controllerOcc.setText("")
        self.Block6controllerOcc.setText("")
        self.Block11controllerOcc.setText("")
        self.controllerDisplayTabWidget.setTabText(self.controllerDisplayTabWidget.indexOf(self.controller2), QCoreApplication.translate("MainWindow", u"Controller 2", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Block7", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Block8", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Block9", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Block10", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Speed Limit (mph)", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Block Length (ft.)", None))
        self.Block7controllerOcc.setText("")
        self.Block8controllerOcc.setText("")
        self.Block9controllerOcc.setText("")
        self.Block10controllerOcc.setText("")
        self.controllerDisplayTabWidget.setTabText(self.controllerDisplayTabWidget.indexOf(self.controller3), QCoreApplication.translate("MainWindow", u"Controller 3", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Speed Limit (mph)", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Block Length (ft.)", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Block 12", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Block 13", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Block 14", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Block 15", None))
        self.Block12controllerOcc.setText("")
        self.Block13controllerOcc.setText("")
        self.Block14controllerOcc.setText("")
        self.Block15controllerOcc.setText("")
        self.controllerDisplayTabWidget.setTabText(self.controllerDisplayTabWidget.indexOf(self.controller4), QCoreApplication.translate("MainWindow", u"Controller 4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainDisplay), QCoreApplication.translate("MainWindow", u"Display", None))
        self.inputLabel.setText(QCoreApplication.translate("MainWindow", u"Input Test Data", None))
        self.outputLabel.setText(QCoreApplication.translate("MainWindow", u"Output Sample Data", None))
        self.trainNumberLabel.setText(QCoreApplication.translate("MainWindow", u"Train Number", None))
        self.suggestedSpeedLabel.setText(QCoreApplication.translate("MainWindow", u"Suggested Speed (kph)", None))
        self.authorityLabel.setText(QCoreApplication.translate("MainWindow", u"Authority (# of blocks)", None))
        self.trainNumberInput.setText("")
        self.suggestedSpeedInput.setText("")
        self.authorityInput.setText("")
        self.trainInputButton.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.blockNumberLabel.setText(QCoreApplication.translate("MainWindow", u"Block Number", None))
        self.blockLengthLabel.setText(QCoreApplication.translate("MainWindow", u"Block Length", None))
        self.speedLimitLabel.setText(QCoreApplication.translate("MainWindow", u"Speed Limit (kph)", None))
        self.blockNumberInput.setText("")
        self.blockLengthInput.setText("")
        self.speedLimitInput.setText("")
        self.blockInputButton.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.occupancyInput.setText("")
        self.occupancyLabel.setText(QCoreApplication.translate("MainWindow", u"Occupancy (Y/N)", None))
        self.trainNumberSelectLabel.setText(QCoreApplication.translate("MainWindow", u"Select Train Number", None))
        self.commandedSpeedLabel.setText(QCoreApplication.translate("MainWindow", u"Commanded Speed (mph)", None))
        self.trainNumberSelectInput.setText("")
        self.commandedSpeedDisplay.setText("")
        self.trainSelectButton.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.blockNumberSelectLabel.setText(QCoreApplication.translate("MainWindow", u"Select Block Number", None))
        self.occupancyDisplayLabel.setText(QCoreApplication.translate("MainWindow", u"Occupancy", None))
        self.blockNumberSelectInput.setText("")
        self.occupancyDisplay.setText("")
        self.blockSelectButton.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.junctionPositionLabel.setText(QCoreApplication.translate("MainWindow", u"Junction Position", None))
        self.junctionPositionDisplay.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Test_tab), QCoreApplication.translate("MainWindow", u"Test", None))
    # retranslateUi

