# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'InterfaceV1.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_TrainModelInterface(object):
    def setupUi(self, TrainModelInterface):
        if not TrainModelInterface.objectName():
            TrainModelInterface.setObjectName(u"TrainModelInterface")
        TrainModelInterface.resize(1248, 566)
        self.PowerVal = QPlainTextEdit(TrainModelInterface)
        self.PowerVal.setObjectName(u"PowerVal")
        self.PowerVal.setGeometry(QRect(140, 110, 101, 21))
        self.PowerVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PowerVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PowerVal.setReadOnly(True)
        self.LDoorVal = QPlainTextEdit(TrainModelInterface)
        self.LDoorVal.setObjectName(u"LDoorVal")
        self.LDoorVal.setGeometry(QRect(403, 110, 101, 21))
        self.LDoorVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.LDoorVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.LDoorVal.setReadOnly(True)
        self.LDoorVal.setOverwriteMode(False)
        self.RDoorVal = QPlainTextEdit(TrainModelInterface)
        self.RDoorVal.setObjectName(u"RDoorVal")
        self.RDoorVal.setGeometry(QRect(403, 140, 101, 21))
        self.RDoorVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RDoorVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RDoorVal.setReadOnly(True)
        self.ILightVal = QPlainTextEdit(TrainModelInterface)
        self.ILightVal.setObjectName(u"ILightVal")
        self.ILightVal.setGeometry(QRect(403, 190, 101, 21))
        self.ILightVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ILightVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ILightVal.setReadOnly(True)
        self.ELightVal = QPlainTextEdit(TrainModelInterface)
        self.ELightVal.setObjectName(u"ELightVal")
        self.ELightVal.setGeometry(QRect(403, 220, 101, 21))
        self.ELightVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ELightVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ELightVal.setReadOnly(True)
        self.CommSpeedVal = QPlainTextEdit(TrainModelInterface)
        self.CommSpeedVal.setObjectName(u"CommSpeedVal")
        self.CommSpeedVal.setGeometry(QRect(730, 140, 101, 21))
        self.CommSpeedVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CommSpeedVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CommSpeedVal.setReadOnly(False)
        self.EBrakeVal = QPlainTextEdit(TrainModelInterface)
        self.EBrakeVal.setObjectName(u"EBrakeVal")
        self.EBrakeVal.setGeometry(QRect(140, 220, 101, 21))
        self.EBrakeVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.EBrakeVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.EBrakeVal.setReadOnly(True)
        self.SBrakeVal = QPlainTextEdit(TrainModelInterface)
        self.SBrakeVal.setObjectName(u"SBrakeVal")
        self.SBrakeVal.setGeometry(QRect(140, 190, 101, 21))
        self.SBrakeVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.SBrakeVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.SBrakeVal.setReadOnly(True)
        self.label = QLabel(TrainModelInterface)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 110, 81, 20))
        self.label_2 = QLabel(TrainModelInterface)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(610, 140, 121, 20))
        self.label_3 = QLabel(TrainModelInterface)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(340, 110, 81, 20))
        self.label_4 = QLabel(TrainModelInterface)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(330, 140, 81, 20))
        self.label_5 = QLabel(TrainModelInterface)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(320, 190, 91, 20))
        self.label_6 = QLabel(TrainModelInterface)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(320, 220, 91, 20))
        self.label_7 = QLabel(TrainModelInterface)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 190, 91, 20))
        self.label_8 = QLabel(TrainModelInterface)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 220, 91, 20))
        self.line = QFrame(TrainModelInterface)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(580, 0, 21, 441))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(TrainModelInterface)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(150, 30, 321, 41))
        font = QFont()
        font.setPointSize(22)
        self.label_9.setFont(font)
        self.label_10 = QLabel(TrainModelInterface)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(720, 30, 321, 41))
        self.label_10.setFont(font)
        self.AuthVal = QPlainTextEdit(TrainModelInterface)
        self.AuthVal.setObjectName(u"AuthVal")
        self.AuthVal.setGeometry(QRect(730, 170, 101, 21))
        self.AuthVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.AuthVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.AuthVal.setReadOnly(False)
        self.label_12 = QLabel(TrainModelInterface)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(660, 170, 81, 20))
        self.label_13 = QLabel(TrainModelInterface)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(940, 140, 101, 20))
        self.tcButton = QPushButton(TrainModelInterface)
        self.tcButton.setObjectName(u"tcButton")
        self.tcButton.setGeometry(QRect(710, 260, 131, 51))
        self.label_11 = QLabel(TrainModelInterface)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(780, 350, 121, 20))
        self.CurSpeedVal = QPlainTextEdit(TrainModelInterface)
        self.CurSpeedVal.setObjectName(u"CurSpeedVal")
        self.CurSpeedVal.setGeometry(QRect(870, 350, 101, 21))
        self.CurSpeedVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CurSpeedVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CurSpeedVal.setReadOnly(False)
        self.sigFail = QCheckBox(TrainModelInterface)
        self.sigFail.setObjectName(u"sigFail")
        self.sigFail.setGeometry(QRect(730, 210, 141, 17))
        self.stationComing = QCheckBox(TrainModelInterface)
        self.stationComing.setObjectName(u"stationComing")
        self.stationComing.setGeometry(QRect(1020, 170, 131, 17))
        self.BLDoor = QCheckBox(TrainModelInterface)
        self.BLDoor.setObjectName(u"BLDoor")
        self.BLDoor.setGeometry(QRect(1020, 190, 131, 17))
        self.BRDoor = QCheckBox(TrainModelInterface)
        self.BRDoor.setObjectName(u"BRDoor")
        self.BRDoor.setGeometry(QRect(1020, 210, 131, 17))
        self.BExtLight = QCheckBox(TrainModelInterface)
        self.BExtLight.setObjectName(u"BExtLight")
        self.BExtLight.setGeometry(QRect(1020, 230, 131, 17))
        self.label_14 = QLabel(TrainModelInterface)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(670, 100, 131, 21))
        font1 = QFont()
        font1.setPointSize(16)
        self.label_14.setFont(font1)
        self.label_15 = QLabel(TrainModelInterface)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(1000, 100, 131, 21))
        self.label_15.setFont(font1)
        self.beaconButton = QPushButton(TrainModelInterface)
        self.beaconButton.setObjectName(u"beaconButton")
        self.beaconButton.setGeometry(QRect(1000, 260, 131, 51))
        self.speedButton = QPushButton(TrainModelInterface)
        self.speedButton.setObjectName(u"speedButton")
        self.speedButton.setGeometry(QRect(860, 400, 131, 51))
        self.stationSel = QComboBox(TrainModelInterface)
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.addItem("")
        self.stationSel.setObjectName(u"stationSel")
        self.stationSel.setGeometry(QRect(1018, 140, 101, 22))
        self.label_16 = QLabel(TrainModelInterface)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(70, 370, 111, 16))
        self.AnnounceVal = QPlainTextEdit(TrainModelInterface)
        self.AnnounceVal.setObjectName(u"AnnounceVal")
        self.AnnounceVal.setGeometry(QRect(160, 400, 391, 71))
        self.AnnounceVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.AnnounceVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.AnnounceVal.setReadOnly(True)

        self.retranslateUi(TrainModelInterface)

        QMetaObject.connectSlotsByName(TrainModelInterface)
    # setupUi

    def retranslateUi(self, TrainModelInterface):
        TrainModelInterface.setWindowTitle(QCoreApplication.translate("TrainModelInterface", u"Train Model Interface", None))
        self.ILightVal.setPlainText("")
        self.ELightVal.setPlainText("")
        self.CommSpeedVal.setPlainText("")
        self.EBrakeVal.setPlainText("")
        self.SBrakeVal.setPlainText("")
        self.label.setText(QCoreApplication.translate("TrainModelInterface", u"Power Output:", None))
        self.label_2.setText(QCoreApplication.translate("TrainModelInterface", u"Commanded Speed:", None))
        self.label_3.setText(QCoreApplication.translate("TrainModelInterface", u"Left Door:", None))
        self.label_4.setText(QCoreApplication.translate("TrainModelInterface", u"Right Door:", None))
        self.label_5.setText(QCoreApplication.translate("TrainModelInterface", u"Interior Lights:", None))
        self.label_6.setText(QCoreApplication.translate("TrainModelInterface", u"Exterior Lights:", None))
        self.label_7.setText(QCoreApplication.translate("TrainModelInterface", u"Service Brake:", None))
        self.label_8.setText(QCoreApplication.translate("TrainModelInterface", u"Emergency Brake:", None))
        self.label_9.setText(QCoreApplication.translate("TrainModelInterface", u"Controller to Model", None))
        self.label_10.setText(QCoreApplication.translate("TrainModelInterface", u"Model to Controller", None))
        self.AuthVal.setPlainText("")
        self.label_12.setText(QCoreApplication.translate("TrainModelInterface", u"Authourity:", None))
        self.label_13.setText(QCoreApplication.translate("TrainModelInterface", u"Station Name:", None))
        self.tcButton.setText(QCoreApplication.translate("TrainModelInterface", u"Update TC", None))
        self.label_11.setText(QCoreApplication.translate("TrainModelInterface", u"Current Speed:", None))
        self.CurSpeedVal.setPlainText("")
        self.sigFail.setText(QCoreApplication.translate("TrainModelInterface", u"Cause Signal Failure", None))
        self.stationComing.setText(QCoreApplication.translate("TrainModelInterface", u"Station Upcoming", None))
        self.BLDoor.setText(QCoreApplication.translate("TrainModelInterface", u"Left Doors", None))
        self.BRDoor.setText(QCoreApplication.translate("TrainModelInterface", u"Right Doors", None))
        self.BExtLight.setText(QCoreApplication.translate("TrainModelInterface", u"Exterioir Lights On", None))
        self.label_14.setText(QCoreApplication.translate("TrainModelInterface", u"Track Circuit", None))
        self.label_15.setText(QCoreApplication.translate("TrainModelInterface", u"Beacon", None))
        self.beaconButton.setText(QCoreApplication.translate("TrainModelInterface", u"Update Beacon", None))
        self.speedButton.setText(QCoreApplication.translate("TrainModelInterface", u"Update Speed", None))
        self.stationSel.setItemText(0, QCoreApplication.translate("TrainModelInterface", u"Shadyside", None))
        self.stationSel.setItemText(1, QCoreApplication.translate("TrainModelInterface", u"Herron Ave", None))
        self.stationSel.setItemText(2, QCoreApplication.translate("TrainModelInterface", u"Swissville", None))
        self.stationSel.setItemText(3, QCoreApplication.translate("TrainModelInterface", u"Penn Station", None))
        self.stationSel.setItemText(4, QCoreApplication.translate("TrainModelInterface", u"Steel Plaza", None))
        self.stationSel.setItemText(5, QCoreApplication.translate("TrainModelInterface", u"First Ave", None))
        self.stationSel.setItemText(6, QCoreApplication.translate("TrainModelInterface", u"Station Square", None))
        self.stationSel.setItemText(7, QCoreApplication.translate("TrainModelInterface", u"South Hills Junction", None))
        self.stationSel.setItemText(8, QCoreApplication.translate("TrainModelInterface", u"Pioneer", None))
        self.stationSel.setItemText(9, QCoreApplication.translate("TrainModelInterface", u"Edgebrook", None))
        self.stationSel.setItemText(10, QCoreApplication.translate("TrainModelInterface", u"Whited", None))
        self.stationSel.setItemText(11, QCoreApplication.translate("TrainModelInterface", u"South Bank", None))
        self.stationSel.setItemText(12, QCoreApplication.translate("TrainModelInterface", u"Central", None))
        self.stationSel.setItemText(13, QCoreApplication.translate("TrainModelInterface", u"Inglewood", None))
        self.stationSel.setItemText(14, QCoreApplication.translate("TrainModelInterface", u"Overbrook", None))
        self.stationSel.setItemText(15, QCoreApplication.translate("TrainModelInterface", u"Glenbury", None))
        self.stationSel.setItemText(16, QCoreApplication.translate("TrainModelInterface", u"Dormont", None))
        self.stationSel.setItemText(17, QCoreApplication.translate("TrainModelInterface", u"Mt Lebanon", None))
        self.stationSel.setItemText(18, QCoreApplication.translate("TrainModelInterface", u"Poplar", None))
        self.stationSel.setItemText(19, QCoreApplication.translate("TrainModelInterface", u"Castle Shannon", None))

        self.label_16.setText(QCoreApplication.translate("TrainModelInterface", u"Announcement:", None))
        self.AnnounceVal.setPlainText("")
    # retranslateUi

