# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'InterfaceV1.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_TrainModelInterface(object):
    def setupUi(self, TrainModelInterface):
        if not TrainModelInterface.objectName():
            TrainModelInterface.setObjectName(u"TrainModelInterface")
        TrainModelInterface.resize(738, 526)
        self.PowerLabel = QPlainTextEdit(TrainModelInterface)
        self.PowerLabel.setObjectName(u"PowerLabel")
        self.PowerLabel.setEnabled(True)
        self.PowerLabel.setGeometry(QRect(50, 110, 81, 21))
        self.PowerLabel.setFrameShape(QFrame.NoFrame)
        self.PowerLabel.setFrameShadow(QFrame.Plain)
        self.PowerLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PowerLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PowerLabel.setReadOnly(True)
        self.PowerLabel.setBackgroundVisible(False)
        self.PowerVal = QPlainTextEdit(TrainModelInterface)
        self.PowerVal.setObjectName(u"PowerVal")
        self.PowerVal.setGeometry(QRect(133, 110, 101, 21))
        self.PowerVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PowerVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PowerVal.setReadOnly(True)
        self.LDoorVal = QPlainTextEdit(TrainModelInterface)
        self.LDoorVal.setObjectName(u"LDoorVal")
        self.LDoorVal.setGeometry(QRect(403, 110, 101, 21))
        self.LDoorVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.LDoorVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.LDoorVal.setReadOnly(True)
        self.LDoorLabel = QPlainTextEdit(TrainModelInterface)
        self.LDoorLabel.setObjectName(u"LDoorLabel")
        self.LDoorLabel.setEnabled(True)
        self.LDoorLabel.setGeometry(QRect(320, 110, 81, 21))
        self.LDoorLabel.setFrameShape(QFrame.NoFrame)
        self.LDoorLabel.setFrameShadow(QFrame.Plain)
        self.LDoorLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.LDoorLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.LDoorLabel.setReadOnly(True)
        self.LDoorLabel.setBackgroundVisible(False)
        self.RDoorVal = QPlainTextEdit(TrainModelInterface)
        self.RDoorVal.setObjectName(u"RDoorVal")
        self.RDoorVal.setGeometry(QRect(403, 140, 101, 21))
        self.RDoorVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RDoorVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RDoorVal.setReadOnly(True)
        self.RDoorLabel = QPlainTextEdit(TrainModelInterface)
        self.RDoorLabel.setObjectName(u"RDoorLabel")
        self.RDoorLabel.setEnabled(True)
        self.RDoorLabel.setGeometry(QRect(320, 140, 81, 21))
        self.RDoorLabel.setFrameShape(QFrame.NoFrame)
        self.RDoorLabel.setFrameShadow(QFrame.Plain)
        self.RDoorLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RDoorLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RDoorLabel.setReadOnly(True)
        self.RDoorLabel.setBackgroundVisible(False)
        self.ILightVal = QPlainTextEdit(TrainModelInterface)
        self.ILightVal.setObjectName(u"ILightVal")
        self.ILightVal.setGeometry(QRect(403, 190, 101, 21))
        self.ILightVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ILightVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ILightVal.setReadOnly(True)
        self.ELightLabel = QPlainTextEdit(TrainModelInterface)
        self.ELightLabel.setObjectName(u"ELightLabel")
        self.ELightLabel.setEnabled(True)
        self.ELightLabel.setGeometry(QRect(300, 220, 101, 21))
        self.ELightLabel.setFrameShape(QFrame.NoFrame)
        self.ELightLabel.setFrameShadow(QFrame.Plain)
        self.ELightLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ELightLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ELightLabel.setReadOnly(True)
        self.ELightLabel.setBackgroundVisible(False)
        self.ELightVal = QPlainTextEdit(TrainModelInterface)
        self.ELightVal.setObjectName(u"ELightVal")
        self.ELightVal.setGeometry(QRect(403, 220, 101, 21))
        self.ELightVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ELightVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ELightVal.setReadOnly(True)
        self.ILightLabel = QPlainTextEdit(TrainModelInterface)
        self.ILightLabel.setObjectName(u"ILightLabel")
        self.ILightLabel.setEnabled(True)
        self.ILightLabel.setGeometry(QRect(300, 190, 101, 21))
        self.ILightLabel.setFrameShape(QFrame.NoFrame)
        self.ILightLabel.setFrameShadow(QFrame.Plain)
        self.ILightLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ILightLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ILightLabel.setReadOnly(True)
        self.ILightLabel.setBackgroundVisible(False)
        self.CommSpeedLabel = QPlainTextEdit(TrainModelInterface)
        self.CommSpeedLabel.setObjectName(u"CommSpeedLabel")
        self.CommSpeedLabel.setEnabled(True)
        self.CommSpeedLabel.setGeometry(QRect(300, 410, 91, 21))
        self.CommSpeedLabel.setFrameShape(QFrame.NoFrame)
        self.CommSpeedLabel.setFrameShadow(QFrame.Plain)
        self.CommSpeedLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CommSpeedLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CommSpeedLabel.setReadOnly(True)
        self.CommSpeedLabel.setBackgroundVisible(False)
        self.CommSpeedVal = QPlainTextEdit(TrainModelInterface)
        self.CommSpeedVal.setObjectName(u"CommSpeedVal")
        self.CommSpeedVal.setGeometry(QRect(400, 410, 101, 21))
        self.CommSpeedVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CommSpeedVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CommSpeedVal.setReadOnly(True)
        self.CurSpeedLabel = QPlainTextEdit(TrainModelInterface)
        self.CurSpeedLabel.setObjectName(u"CurSpeedLabel")
        self.CurSpeedLabel.setEnabled(True)
        self.CurSpeedLabel.setGeometry(QRect(307, 380, 81, 21))
        self.CurSpeedLabel.setFrameShape(QFrame.NoFrame)
        self.CurSpeedLabel.setFrameShadow(QFrame.Plain)
        self.CurSpeedLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CurSpeedLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CurSpeedLabel.setReadOnly(True)
        self.CurSpeedLabel.setBackgroundVisible(False)
        self.CurSpeedVal = QPlainTextEdit(TrainModelInterface)
        self.CurSpeedVal.setObjectName(u"CurSpeedVal")
        self.CurSpeedVal.setGeometry(QRect(400, 380, 101, 21))
        self.CurSpeedVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CurSpeedVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.CurSpeedVal.setReadOnly(True)
        self.EBrakeLabel = QPlainTextEdit(TrainModelInterface)
        self.EBrakeLabel.setObjectName(u"EBrakeLabel")
        self.EBrakeLabel.setEnabled(True)
        self.EBrakeLabel.setGeometry(QRect(327, 300, 81, 21))
        self.EBrakeLabel.setFrameShape(QFrame.NoFrame)
        self.EBrakeLabel.setFrameShadow(QFrame.Plain)
        self.EBrakeLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.EBrakeLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.EBrakeLabel.setReadOnly(True)
        self.EBrakeLabel.setBackgroundVisible(False)
        self.EBrakeVal = QPlainTextEdit(TrainModelInterface)
        self.EBrakeVal.setObjectName(u"EBrakeVal")
        self.EBrakeVal.setGeometry(QRect(410, 300, 101, 21))
        self.EBrakeVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.EBrakeVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.EBrakeVal.setReadOnly(True)
        self.SBrakeLabel = QPlainTextEdit(TrainModelInterface)
        self.SBrakeLabel.setObjectName(u"SBrakeLabel")
        self.SBrakeLabel.setEnabled(True)
        self.SBrakeLabel.setGeometry(QRect(327, 270, 81, 21))
        self.SBrakeLabel.setFrameShape(QFrame.NoFrame)
        self.SBrakeLabel.setFrameShadow(QFrame.Plain)
        self.SBrakeLabel.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.SBrakeLabel.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.SBrakeLabel.setReadOnly(True)
        self.SBrakeLabel.setBackgroundVisible(False)
        self.SBrakeVal = QPlainTextEdit(TrainModelInterface)
        self.SBrakeVal.setObjectName(u"SBrakeVal")
        self.SBrakeVal.setGeometry(QRect(410, 270, 101, 21))
        self.SBrakeVal.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.SBrakeVal.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.SBrakeVal.setReadOnly(True)

        self.retranslateUi(TrainModelInterface)

        QMetaObject.connectSlotsByName(TrainModelInterface)
    # setupUi

    def retranslateUi(self, TrainModelInterface):
        TrainModelInterface.setWindowTitle(QCoreApplication.translate("TrainModelInterface", u"Train Model Interface", None))
        self.PowerLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Power Output:", None))
        self.LDoorLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Left Doors:", None))
        self.RDoorLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Right Doors:", None))
        self.ILightVal.setPlainText("")
        self.ELightLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Exterior Lights:", None))
        self.ELightVal.setPlainText("")
        self.ILightLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Interior Lights:", None))
        self.CommSpeedLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Comm Speed:", None))
        self.CommSpeedVal.setPlainText("")
        self.CurSpeedLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Cur Speed:\n"
"", None))
        self.CurSpeedVal.setPlainText("")
        self.EBrakeLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"      E.  Brake:", None))
        self.EBrakeVal.setPlainText("")
        self.SBrakeLabel.setPlainText(QCoreApplication.translate("TrainModelInterface", u"Service Brake:", None))
        self.SBrakeVal.setPlainText("")
    # retranslateUi

