# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TrackControllerSW.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_TrackControllerUI(object):
    def setupUi(self, TrackControllerUI):
        if not TrackControllerUI.objectName():
            TrackControllerUI.setObjectName(u"TrackControllerUI")
        TrackControllerUI.setWindowModality(Qt.NonModal)
        TrackControllerUI.resize(554, 385)
        self.centralwidget = QWidget(TrackControllerUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Program_2 = QTabWidget(self.centralwidget)
        self.Program_2.setObjectName(u"Program_2")
        self.Program_2.setGeometry(QRect(0, 0, 491, 441))
        self.Program_2.setAutoFillBackground(False)
        self.Program_2.setTabPosition(QTabWidget.North)
        self.Program_2.setTabShape(QTabWidget.Triangular)
        self.Program_2.setElideMode(Qt.ElideNone)
        self.Program_2.setUsesScrollButtons(True)
        self.Program_2.setDocumentMode(False)
        self.Program = QWidget()
        self.Program.setObjectName(u"Program")
        self.line_2 = QFrame(self.Program)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 0, 821, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_2 = QLabel(self.Program)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 231, 21))
        self.label_2.setFrameShape(QFrame.Box)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.ImportLine = QLineEdit(self.Program)
        self.ImportLine.setObjectName(u"ImportLine")
        self.ImportLine.setGeometry(QRect(10, 110, 113, 21))
        self.ImportButton = QPushButton(self.Program)
        self.ImportButton.setObjectName(u"ImportButton")
        self.ImportButton.setGeometry(QRect(130, 110, 111, 21))
        self.SuccessFailLine = QLabel(self.Program)
        self.SuccessFailLine.setObjectName(u"SuccessFailLine")
        self.SuccessFailLine.setGeometry(QRect(10, 140, 111, 21))
        self.label_3 = QLabel(self.Program)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 111, 21))
        self.label_3.setFrameShape(QFrame.Box)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.ProgramLineBox = QComboBox(self.Program)
        self.ProgramLineBox.addItem("")
        self.ProgramLineBox.addItem("")
        self.ProgramLineBox.addItem("")
        self.ProgramLineBox.setObjectName(u"ProgramLineBox")
        self.ProgramLineBox.setGeometry(QRect(129, 50, 111, 22))
        self.label_4 = QLabel(self.Program)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 80, 111, 20))
        self.label_4.setFrameShape(QFrame.Box)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.ProgramControllerBox = QComboBox(self.Program)
        self.ProgramControllerBox.setObjectName(u"ProgramControllerBox")
        self.ProgramControllerBox.setGeometry(QRect(130, 80, 111, 22))
        self.Program_2.addTab(self.Program, "")
        self.TrackStatus = QWidget()
        self.TrackStatus.setObjectName(u"TrackStatus")
        self.line = QFrame(self.TrackStatus)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 0, 821, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.BlockInput = QComboBox(self.TrackStatus)
        self.BlockInput.addItem("")
        self.BlockInput.setObjectName(u"BlockInput")
        self.BlockInput.setGeometry(QRect(150, 90, 71, 22))
        self.BlockInput.setEditable(False)
        self.BlockInput.setMaxVisibleItems(9)
        self.BlockInput.setModelColumn(0)
        self.label = QLabel(self.TrackStatus)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 90, 101, 21))
        self.label.setFrameShape(QFrame.Box)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.TrackStatus)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 120, 101, 21))
        self.label_6.setFrameShape(QFrame.Box)
        self.BlockStatus = QLabel(self.TrackStatus)
        self.BlockStatus.setObjectName(u"BlockStatus")
        self.BlockStatus.setGeometry(QRect(150, 120, 71, 21))
        self.BlockStatus.setFrameShape(QFrame.Box)
        self.label_7 = QLabel(self.TrackStatus)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 150, 101, 21))
        self.label_7.setFrameShape(QFrame.Box)
        self.Occupancy = QLabel(self.TrackStatus)
        self.Occupancy.setObjectName(u"Occupancy")
        self.Occupancy.setGeometry(QRect(150, 150, 71, 21))
        self.Occupancy.setFrameShape(QFrame.Box)
        self.label_9 = QLabel(self.TrackStatus)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 180, 101, 21))
        self.label_9.setFrameShape(QFrame.Box)
        self.Authority = QLabel(self.TrackStatus)
        self.Authority.setObjectName(u"Authority")
        self.Authority.setGeometry(QRect(150, 180, 71, 21))
        self.Authority.setFrameShape(QFrame.Box)
        self.label_11 = QLabel(self.TrackStatus)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 210, 101, 21))
        self.label_11.setFrameShape(QFrame.Box)
        self.CommandedSpeed = QLabel(self.TrackStatus)
        self.CommandedSpeed.setObjectName(u"CommandedSpeed")
        self.CommandedSpeed.setGeometry(QRect(150, 210, 71, 21))
        self.CommandedSpeed.setFrameShape(QFrame.Box)
        self.label_13 = QLabel(self.TrackStatus)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 240, 101, 21))
        self.label_13.setFrameShape(QFrame.Box)
        self.CrossingStatus = QLabel(self.TrackStatus)
        self.CrossingStatus.setObjectName(u"CrossingStatus")
        self.CrossingStatus.setGeometry(QRect(150, 240, 71, 21))
        self.CrossingStatus.setFrameShape(QFrame.Box)
        self.label_15 = QLabel(self.TrackStatus)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 270, 101, 21))
        self.label_15.setFrameShape(QFrame.Box)
        self.SwitchStatus = QLabel(self.TrackStatus)
        self.SwitchStatus.setObjectName(u"SwitchStatus")
        self.SwitchStatus.setGeometry(QRect(150, 270, 71, 21))
        self.SwitchStatus.setFrameShape(QFrame.Box)
        self.label_5 = QLabel(self.TrackStatus)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 30, 101, 21))
        self.label_5.setFrameShape(QFrame.Box)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.StatusLineBox = QComboBox(self.TrackStatus)
        self.StatusLineBox.addItem("")
        self.StatusLineBox.addItem("")
        self.StatusLineBox.addItem("")
        self.StatusLineBox.setObjectName(u"StatusLineBox")
        self.StatusLineBox.setGeometry(QRect(150, 30, 71, 20))
        self.label_8 = QLabel(self.TrackStatus)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 60, 101, 21))
        self.label_8.setFrameShape(QFrame.Box)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.StatusControllerBox = QComboBox(self.TrackStatus)
        self.StatusControllerBox.addItem("")
        self.StatusControllerBox.setObjectName(u"StatusControllerBox")
        self.StatusControllerBox.setGeometry(QRect(150, 60, 71, 21))
        self.Program_2.addTab(self.TrackStatus, "")
        TrackControllerUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TrackControllerUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 554, 22))
        TrackControllerUI.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TrackControllerUI)
        self.statusbar.setObjectName(u"statusbar")
        TrackControllerUI.setStatusBar(self.statusbar)

        self.retranslateUi(TrackControllerUI)

        self.Program_2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(TrackControllerUI)
    # setupUi

    def retranslateUi(self, TrackControllerUI):
        TrackControllerUI.setWindowTitle(QCoreApplication.translate("TrackControllerUI", u"MainWindow", None))
        self.label_2.setText(QCoreApplication.translate("TrackControllerUI", u"PLC File", None))
        self.ImportLine.setText("")
        self.ImportButton.setText(QCoreApplication.translate("TrackControllerUI", u"Import", None))
        self.SuccessFailLine.setText("")
        self.label_3.setText(QCoreApplication.translate("TrackControllerUI", u"Line", None))
        self.ProgramLineBox.setItemText(0, QCoreApplication.translate("TrackControllerUI", u"Choose", None))
        self.ProgramLineBox.setItemText(1, QCoreApplication.translate("TrackControllerUI", u"Green", None))
        self.ProgramLineBox.setItemText(2, QCoreApplication.translate("TrackControllerUI", u"Red", None))

        self.label_4.setText(QCoreApplication.translate("TrackControllerUI", u"Controller", None))
        self.Program_2.setTabText(self.Program_2.indexOf(self.Program), QCoreApplication.translate("TrackControllerUI", u"Program", None))
        self.BlockInput.setItemText(0, QCoreApplication.translate("TrackControllerUI", u"Choose", None))

        self.label.setText(QCoreApplication.translate("TrackControllerUI", u"Block Number", None))
        self.label_6.setText(QCoreApplication.translate("TrackControllerUI", u"Block Status", None))
        self.BlockStatus.setText("")
        self.label_7.setText(QCoreApplication.translate("TrackControllerUI", u"Occupancy", None))
        self.Occupancy.setText("")
        self.label_9.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.Authority.setText("")
        self.label_11.setText(QCoreApplication.translate("TrackControllerUI", u"Commanded Speed", None))
        self.CommandedSpeed.setText("")
        self.label_13.setText(QCoreApplication.translate("TrackControllerUI", u"Crossing Signal", None))
        self.CrossingStatus.setText("")
        self.label_15.setText(QCoreApplication.translate("TrackControllerUI", u"Switch Status", None))
        self.SwitchStatus.setText("")
        self.label_5.setText(QCoreApplication.translate("TrackControllerUI", u"Line", None))
        self.StatusLineBox.setItemText(0, QCoreApplication.translate("TrackControllerUI", u"Choose", None))
        self.StatusLineBox.setItemText(1, QCoreApplication.translate("TrackControllerUI", u"Green", None))
        self.StatusLineBox.setItemText(2, QCoreApplication.translate("TrackControllerUI", u"Red", None))

        self.label_8.setText(QCoreApplication.translate("TrackControllerUI", u"Controller", None))
        self.StatusControllerBox.setItemText(0, QCoreApplication.translate("TrackControllerUI", u"Choose", None))

        self.Program_2.setTabText(self.Program_2.indexOf(self.TrackStatus), QCoreApplication.translate("TrackControllerUI", u"Track Status", None))
    # retranslateUi

