# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TrackControllerSW.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_TrackControllerUI(object):
    def setupUi(self, TrackControllerUI):
        if not TrackControllerUI.objectName():
            TrackControllerUI.setObjectName(u"TrackControllerUI")
        TrackControllerUI.setWindowModality(Qt.NonModal)
        TrackControllerUI.resize(765, 571)
        self.centralwidget = QWidget(TrackControllerUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 821, 411))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.TrackStatus = QWidget()
        self.TrackStatus.setObjectName(u"TrackStatus")
        self.tabWidget_3 = QTabWidget(self.TrackStatus)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 10, 231, 381))
        self.tabWidget_3.setTabShape(QTabWidget.Triangular)
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.toolBox = QToolBox(self.tab_5)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(0, 0, 221, 191))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB1 = QLabel(self.page)
        self.StatusB1.setObjectName(u"StatusB1")
        self.StatusB1.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB1.setFrameShape(QFrame.Box)
        self.StatusB1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.AuthorityB1 = QLabel(self.page)
        self.AuthorityB1.setObjectName(u"AuthorityB1")
        self.AuthorityB1.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB1.setFrameShape(QFrame.Box)
        self.AuthorityB1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_145 = QLabel(self.page)
        self.label_145.setObjectName(u"label_145")
        self.label_145.setGeometry(QRect(10, 20, 101, 16))
        self.label_145.setFrameShape(QFrame.Box)
        self.SugSpeedB1 = QLabel(self.page)
        self.SugSpeedB1.setObjectName(u"SugSpeedB1")
        self.SugSpeedB1.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB1.setFrameShape(QFrame.Box)
        self.SugSpeedB1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_142 = QLabel(self.page)
        self.label_142.setObjectName(u"label_142")
        self.label_142.setGeometry(QRect(10, 60, 101, 16))
        self.label_142.setFrameShape(QFrame.Box)
        self.label_141 = QLabel(self.page)
        self.label_141.setObjectName(u"label_141")
        self.label_141.setGeometry(QRect(10, 40, 101, 16))
        self.label_141.setFrameShape(QFrame.Box)
        self.OccupationB1 = QLabel(self.page)
        self.OccupationB1.setObjectName(u"OccupationB1")
        self.OccupationB1.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB1.setFrameShape(QFrame.Box)
        self.OccupationB1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_143 = QLabel(self.page)
        self.label_143.setObjectName(u"label_143")
        self.label_143.setGeometry(QRect(10, 0, 101, 16))
        self.label_143.setFrameShape(QFrame.Box)
        self.toolBox.addItem(self.page, u"Block 1")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB2 = QLabel(self.page_2)
        self.StatusB2.setObjectName(u"StatusB2")
        self.StatusB2.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB2.setFrameShape(QFrame.Box)
        self.StatusB2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SugSpeedB2 = QLabel(self.page_2)
        self.SugSpeedB2.setObjectName(u"SugSpeedB2")
        self.SugSpeedB2.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB2.setFrameShape(QFrame.Box)
        self.SugSpeedB2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_137 = QLabel(self.page_2)
        self.label_137.setObjectName(u"label_137")
        self.label_137.setGeometry(QRect(10, 20, 101, 16))
        self.label_137.setFrameShape(QFrame.Box)
        self.label_133 = QLabel(self.page_2)
        self.label_133.setObjectName(u"label_133")
        self.label_133.setGeometry(QRect(10, 40, 101, 16))
        self.label_133.setFrameShape(QFrame.Box)
        self.OccupationB2 = QLabel(self.page_2)
        self.OccupationB2.setObjectName(u"OccupationB2")
        self.OccupationB2.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB2.setFrameShape(QFrame.Box)
        self.OccupationB2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_135 = QLabel(self.page_2)
        self.label_135.setObjectName(u"label_135")
        self.label_135.setGeometry(QRect(10, 0, 101, 16))
        self.label_135.setFrameShape(QFrame.Box)
        self.AuthorityB2 = QLabel(self.page_2)
        self.AuthorityB2.setObjectName(u"AuthorityB2")
        self.AuthorityB2.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB2.setFrameShape(QFrame.Box)
        self.AuthorityB2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_134 = QLabel(self.page_2)
        self.label_134.setObjectName(u"label_134")
        self.label_134.setGeometry(QRect(10, 60, 101, 16))
        self.label_134.setFrameShape(QFrame.Box)
        self.toolBox.addItem(self.page_2, u"Block 2")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB3 = QLabel(self.page_3)
        self.StatusB3.setObjectName(u"StatusB3")
        self.StatusB3.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB3.setFrameShape(QFrame.Box)
        self.StatusB3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.OccupationB3 = QLabel(self.page_3)
        self.OccupationB3.setObjectName(u"OccupationB3")
        self.OccupationB3.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB3.setFrameShape(QFrame.Box)
        self.OccupationB3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_127 = QLabel(self.page_3)
        self.label_127.setObjectName(u"label_127")
        self.label_127.setGeometry(QRect(10, 0, 101, 16))
        self.label_127.setFrameShape(QFrame.Box)
        self.label_125 = QLabel(self.page_3)
        self.label_125.setObjectName(u"label_125")
        self.label_125.setGeometry(QRect(10, 40, 101, 16))
        self.label_125.setFrameShape(QFrame.Box)
        self.SugSpeedB3 = QLabel(self.page_3)
        self.SugSpeedB3.setObjectName(u"SugSpeedB3")
        self.SugSpeedB3.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB3.setFrameShape(QFrame.Box)
        self.SugSpeedB3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.AuthorityB3 = QLabel(self.page_3)
        self.AuthorityB3.setObjectName(u"AuthorityB3")
        self.AuthorityB3.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB3.setFrameShape(QFrame.Box)
        self.AuthorityB3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_129 = QLabel(self.page_3)
        self.label_129.setObjectName(u"label_129")
        self.label_129.setGeometry(QRect(10, 20, 101, 16))
        self.label_129.setFrameShape(QFrame.Box)
        self.label_126 = QLabel(self.page_3)
        self.label_126.setObjectName(u"label_126")
        self.label_126.setGeometry(QRect(10, 60, 101, 16))
        self.label_126.setFrameShape(QFrame.Box)
        self.toolBox.addItem(self.page_3, u"Block 3")
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4.setGeometry(QRect(0, 0, 221, 79))
        self.SugSpeedB4 = QLabel(self.page_4)
        self.SugSpeedB4.setObjectName(u"SugSpeedB4")
        self.SugSpeedB4.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB4.setFrameShape(QFrame.Box)
        self.SugSpeedB4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_119 = QLabel(self.page_4)
        self.label_119.setObjectName(u"label_119")
        self.label_119.setGeometry(QRect(10, 0, 101, 16))
        self.label_119.setFrameShape(QFrame.Box)
        self.AuthorityB4 = QLabel(self.page_4)
        self.AuthorityB4.setObjectName(u"AuthorityB4")
        self.AuthorityB4.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB4.setFrameShape(QFrame.Box)
        self.AuthorityB4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.StatusB4 = QLabel(self.page_4)
        self.StatusB4.setObjectName(u"StatusB4")
        self.StatusB4.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB4.setFrameShape(QFrame.Box)
        self.StatusB4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_106 = QLabel(self.page_4)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setGeometry(QRect(10, 60, 101, 16))
        self.label_106.setFrameShape(QFrame.Box)
        self.label_105 = QLabel(self.page_4)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(10, 40, 101, 16))
        self.label_105.setFrameShape(QFrame.Box)
        self.OccupationB4 = QLabel(self.page_4)
        self.OccupationB4.setObjectName(u"OccupationB4")
        self.OccupationB4.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB4.setFrameShape(QFrame.Box)
        self.OccupationB4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_121 = QLabel(self.page_4)
        self.label_121.setObjectName(u"label_121")
        self.label_121.setGeometry(QRect(10, 20, 101, 16))
        self.label_121.setFrameShape(QFrame.Box)
        self.toolBox.addItem(self.page_4, u"Block 4")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.toolBox_2 = QToolBox(self.tab_6)
        self.toolBox_2.setObjectName(u"toolBox_2")
        self.toolBox_2.setGeometry(QRect(0, 0, 221, 191))
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.page_6.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB5 = QLabel(self.page_6)
        self.StatusB5.setObjectName(u"StatusB5")
        self.StatusB5.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB5.setFrameShape(QFrame.Box)
        self.StatusB5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.OccupationB5 = QLabel(self.page_6)
        self.OccupationB5.setObjectName(u"OccupationB5")
        self.OccupationB5.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB5.setFrameShape(QFrame.Box)
        self.OccupationB5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SugSpeedB5 = QLabel(self.page_6)
        self.SugSpeedB5.setObjectName(u"SugSpeedB5")
        self.SugSpeedB5.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB5.setFrameShape(QFrame.Box)
        self.SugSpeedB5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_157 = QLabel(self.page_6)
        self.label_157.setObjectName(u"label_157")
        self.label_157.setGeometry(QRect(10, 60, 101, 16))
        self.label_157.setFrameShape(QFrame.Box)
        self.label_35 = QLabel(self.page_6)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 20, 101, 16))
        self.label_35.setFrameShape(QFrame.Box)
        self.AuthorityB5 = QLabel(self.page_6)
        self.AuthorityB5.setObjectName(u"AuthorityB5")
        self.AuthorityB5.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB5.setFrameShape(QFrame.Box)
        self.AuthorityB5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_32 = QLabel(self.page_6)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 40, 101, 16))
        self.label_32.setFrameShape(QFrame.Box)
        self.label_33 = QLabel(self.page_6)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 0, 101, 16))
        self.label_33.setFrameShape(QFrame.Box)
        self.toolBox_2.addItem(self.page_6, u"Block 5")
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.page_7.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB6 = QLabel(self.page_7)
        self.StatusB6.setObjectName(u"StatusB6")
        self.StatusB6.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB6.setFrameShape(QFrame.Box)
        self.StatusB6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SugSpeedB6 = QLabel(self.page_7)
        self.SugSpeedB6.setObjectName(u"SugSpeedB6")
        self.SugSpeedB6.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB6.setFrameShape(QFrame.Box)
        self.SugSpeedB6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_38 = QLabel(self.page_7)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 40, 101, 16))
        self.label_38.setFrameShape(QFrame.Box)
        self.label_41 = QLabel(self.page_7)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 20, 101, 16))
        self.label_41.setFrameShape(QFrame.Box)
        self.label_155 = QLabel(self.page_7)
        self.label_155.setObjectName(u"label_155")
        self.label_155.setGeometry(QRect(10, 60, 101, 16))
        self.label_155.setFrameShape(QFrame.Box)
        self.AuthorityB6 = QLabel(self.page_7)
        self.AuthorityB6.setObjectName(u"AuthorityB6")
        self.AuthorityB6.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB6.setFrameShape(QFrame.Box)
        self.AuthorityB6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_39 = QLabel(self.page_7)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 0, 101, 16))
        self.label_39.setFrameShape(QFrame.Box)
        self.OccupationB6 = QLabel(self.page_7)
        self.OccupationB6.setObjectName(u"OccupationB6")
        self.OccupationB6.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB6.setFrameShape(QFrame.Box)
        self.OccupationB6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.toolBox_2.addItem(self.page_7, u"Block 6")
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.page_8.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB11 = QLabel(self.page_8)
        self.StatusB11.setObjectName(u"StatusB11")
        self.StatusB11.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB11.setFrameShape(QFrame.Box)
        self.StatusB11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.OccupationB11 = QLabel(self.page_8)
        self.OccupationB11.setObjectName(u"OccupationB11")
        self.OccupationB11.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB11.setFrameShape(QFrame.Box)
        self.OccupationB11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_45 = QLabel(self.page_8)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 0, 101, 16))
        self.label_45.setFrameShape(QFrame.Box)
        self.label_153 = QLabel(self.page_8)
        self.label_153.setObjectName(u"label_153")
        self.label_153.setGeometry(QRect(10, 60, 101, 16))
        self.label_153.setFrameShape(QFrame.Box)
        self.AuthorityB11 = QLabel(self.page_8)
        self.AuthorityB11.setObjectName(u"AuthorityB11")
        self.AuthorityB11.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB11.setFrameShape(QFrame.Box)
        self.AuthorityB11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_47 = QLabel(self.page_8)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(10, 20, 101, 16))
        self.label_47.setFrameShape(QFrame.Box)
        self.SugSpeedB11 = QLabel(self.page_8)
        self.SugSpeedB11.setObjectName(u"SugSpeedB11")
        self.SugSpeedB11.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB11.setFrameShape(QFrame.Box)
        self.SugSpeedB11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_44 = QLabel(self.page_8)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 40, 101, 16))
        self.label_44.setFrameShape(QFrame.Box)
        self.toolBox_2.addItem(self.page_8, u"Block 11")
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.page_9.setGeometry(QRect(0, 0, 221, 79))
        self.SwitchDisp = QLabel(self.page_9)
        self.SwitchDisp.setObjectName(u"SwitchDisp")
        self.SwitchDisp.setGeometry(QRect(110, 0, 101, 16))
        self.SwitchDisp.setFrameShape(QFrame.Box)
        self.SwitchDisp.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_51 = QLabel(self.page_9)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 0, 101, 16))
        self.label_51.setFrameShape(QFrame.Box)
        self.toolBox_2.addItem(self.page_9, u"Switch 1")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.toolBox_4 = QToolBox(self.tab_8)
        self.toolBox_4.setObjectName(u"toolBox_4")
        self.toolBox_4.setGeometry(QRect(0, 0, 221, 191))
        self.page_16 = QWidget()
        self.page_16.setObjectName(u"page_16")
        self.page_16.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB7 = QLabel(self.page_16)
        self.StatusB7.setObjectName(u"StatusB7")
        self.StatusB7.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB7.setFrameShape(QFrame.Box)
        self.StatusB7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.OccupationB7 = QLabel(self.page_16)
        self.OccupationB7.setObjectName(u"OccupationB7")
        self.OccupationB7.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB7.setFrameShape(QFrame.Box)
        self.OccupationB7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SugSpeedB7 = QLabel(self.page_16)
        self.SugSpeedB7.setObjectName(u"SugSpeedB7")
        self.SugSpeedB7.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB7.setFrameShape(QFrame.Box)
        self.SugSpeedB7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_169 = QLabel(self.page_16)
        self.label_169.setObjectName(u"label_169")
        self.label_169.setGeometry(QRect(10, 60, 101, 16))
        self.label_169.setFrameShape(QFrame.Box)
        self.label_102 = QLabel(self.page_16)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(10, 40, 101, 16))
        self.label_102.setFrameShape(QFrame.Box)
        self.label_103 = QLabel(self.page_16)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(10, 20, 101, 16))
        self.label_103.setFrameShape(QFrame.Box)
        self.label_148 = QLabel(self.page_16)
        self.label_148.setObjectName(u"label_148")
        self.label_148.setGeometry(QRect(10, 0, 101, 16))
        self.label_148.setFrameShape(QFrame.Box)
        self.AuthorityB7 = QLabel(self.page_16)
        self.AuthorityB7.setObjectName(u"AuthorityB7")
        self.AuthorityB7.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB7.setFrameShape(QFrame.Box)
        self.AuthorityB7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.toolBox_4.addItem(self.page_16, u"Block 7")
        self.page_17 = QWidget()
        self.page_17.setObjectName(u"page_17")
        self.page_17.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB8 = QLabel(self.page_17)
        self.StatusB8.setObjectName(u"StatusB8")
        self.StatusB8.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB8.setFrameShape(QFrame.Box)
        self.StatusB8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SugSpeedB8 = QLabel(self.page_17)
        self.SugSpeedB8.setObjectName(u"SugSpeedB8")
        self.SugSpeedB8.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB8.setFrameShape(QFrame.Box)
        self.SugSpeedB8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_151 = QLabel(self.page_17)
        self.label_151.setObjectName(u"label_151")
        self.label_151.setGeometry(QRect(10, 0, 101, 16))
        self.label_151.setFrameShape(QFrame.Box)
        self.label_158 = QLabel(self.page_17)
        self.label_158.setObjectName(u"label_158")
        self.label_158.setGeometry(QRect(10, 20, 101, 16))
        self.label_158.setFrameShape(QFrame.Box)
        self.label_159 = QLabel(self.page_17)
        self.label_159.setObjectName(u"label_159")
        self.label_159.setGeometry(QRect(10, 40, 101, 16))
        self.label_159.setFrameShape(QFrame.Box)
        self.OccupationB8 = QLabel(self.page_17)
        self.OccupationB8.setObjectName(u"OccupationB8")
        self.OccupationB8.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB8.setFrameShape(QFrame.Box)
        self.OccupationB8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.AuthorityB8 = QLabel(self.page_17)
        self.AuthorityB8.setObjectName(u"AuthorityB8")
        self.AuthorityB8.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB8.setFrameShape(QFrame.Box)
        self.AuthorityB8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_173 = QLabel(self.page_17)
        self.label_173.setObjectName(u"label_173")
        self.label_173.setGeometry(QRect(10, 60, 101, 16))
        self.label_173.setFrameShape(QFrame.Box)
        self.toolBox_4.addItem(self.page_17, u"Block 8")
        self.page_18 = QWidget()
        self.page_18.setObjectName(u"page_18")
        self.page_18.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB9 = QLabel(self.page_18)
        self.StatusB9.setObjectName(u"StatusB9")
        self.StatusB9.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB9.setFrameShape(QFrame.Box)
        self.StatusB9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_175 = QLabel(self.page_18)
        self.label_175.setObjectName(u"label_175")
        self.label_175.setGeometry(QRect(10, 60, 101, 16))
        self.label_175.setFrameShape(QFrame.Box)
        self.label_176 = QLabel(self.page_18)
        self.label_176.setObjectName(u"label_176")
        self.label_176.setGeometry(QRect(10, 20, 101, 16))
        self.label_176.setFrameShape(QFrame.Box)
        self.label_177 = QLabel(self.page_18)
        self.label_177.setObjectName(u"label_177")
        self.label_177.setGeometry(QRect(10, 0, 101, 16))
        self.label_177.setFrameShape(QFrame.Box)
        self.SugSpeedB9 = QLabel(self.page_18)
        self.SugSpeedB9.setObjectName(u"SugSpeedB9")
        self.SugSpeedB9.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB9.setFrameShape(QFrame.Box)
        self.SugSpeedB9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_179 = QLabel(self.page_18)
        self.label_179.setObjectName(u"label_179")
        self.label_179.setGeometry(QRect(10, 40, 101, 16))
        self.label_179.setFrameShape(QFrame.Box)
        self.AuthorityB9 = QLabel(self.page_18)
        self.AuthorityB9.setObjectName(u"AuthorityB9")
        self.AuthorityB9.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB9.setFrameShape(QFrame.Box)
        self.AuthorityB9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.OccupationB9 = QLabel(self.page_18)
        self.OccupationB9.setObjectName(u"OccupationB9")
        self.OccupationB9.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB9.setFrameShape(QFrame.Box)
        self.OccupationB9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.toolBox_4.addItem(self.page_18, u"Block 9")
        self.page_19 = QWidget()
        self.page_19.setObjectName(u"page_19")
        self.page_19.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB10 = QLabel(self.page_19)
        self.StatusB10.setObjectName(u"StatusB10")
        self.StatusB10.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB10.setFrameShape(QFrame.Box)
        self.StatusB10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_183 = QLabel(self.page_19)
        self.label_183.setObjectName(u"label_183")
        self.label_183.setGeometry(QRect(10, 20, 101, 16))
        self.label_183.setFrameShape(QFrame.Box)
        self.label_184 = QLabel(self.page_19)
        self.label_184.setObjectName(u"label_184")
        self.label_184.setGeometry(QRect(10, 60, 101, 16))
        self.label_184.setFrameShape(QFrame.Box)
        self.OccupationB10 = QLabel(self.page_19)
        self.OccupationB10.setObjectName(u"OccupationB10")
        self.OccupationB10.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB10.setFrameShape(QFrame.Box)
        self.OccupationB10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.AuthorityB10 = QLabel(self.page_19)
        self.AuthorityB10.setObjectName(u"AuthorityB10")
        self.AuthorityB10.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB10.setFrameShape(QFrame.Box)
        self.AuthorityB10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_187 = QLabel(self.page_19)
        self.label_187.setObjectName(u"label_187")
        self.label_187.setGeometry(QRect(10, 40, 101, 16))
        self.label_187.setFrameShape(QFrame.Box)
        self.SugSpeedB10 = QLabel(self.page_19)
        self.SugSpeedB10.setObjectName(u"SugSpeedB10")
        self.SugSpeedB10.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB10.setFrameShape(QFrame.Box)
        self.SugSpeedB10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_189 = QLabel(self.page_19)
        self.label_189.setObjectName(u"label_189")
        self.label_189.setGeometry(QRect(10, 0, 101, 16))
        self.label_189.setFrameShape(QFrame.Box)
        self.toolBox_4.addItem(self.page_19, u"Block 10")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.toolBox_3 = QToolBox(self.tab_7)
        self.toolBox_3.setObjectName(u"toolBox_3")
        self.toolBox_3.setGeometry(QRect(0, 0, 221, 191))
        self.page_12 = QWidget()
        self.page_12.setObjectName(u"page_12")
        self.page_12.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB12 = QLabel(self.page_12)
        self.StatusB12.setObjectName(u"StatusB12")
        self.StatusB12.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB12.setFrameShape(QFrame.Box)
        self.StatusB12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.OccupationB12 = QLabel(self.page_12)
        self.OccupationB12.setObjectName(u"OccupationB12")
        self.OccupationB12.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB12.setFrameShape(QFrame.Box)
        self.OccupationB12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SugSpeedB12 = QLabel(self.page_12)
        self.SugSpeedB12.setObjectName(u"SugSpeedB12")
        self.SugSpeedB12.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB12.setFrameShape(QFrame.Box)
        self.SugSpeedB12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_161 = QLabel(self.page_12)
        self.label_161.setObjectName(u"label_161")
        self.label_161.setGeometry(QRect(10, 60, 101, 16))
        self.label_161.setFrameShape(QFrame.Box)
        self.label_68 = QLabel(self.page_12)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(10, 40, 101, 16))
        self.label_68.setFrameShape(QFrame.Box)
        self.label_71 = QLabel(self.page_12)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(10, 20, 101, 16))
        self.label_71.setFrameShape(QFrame.Box)
        self.label_69 = QLabel(self.page_12)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 0, 101, 16))
        self.label_69.setFrameShape(QFrame.Box)
        self.AuthorityB12 = QLabel(self.page_12)
        self.AuthorityB12.setObjectName(u"AuthorityB12")
        self.AuthorityB12.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB12.setFrameShape(QFrame.Box)
        self.AuthorityB12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.toolBox_3.addItem(self.page_12, u"Block 12")
        self.page_13 = QWidget()
        self.page_13.setObjectName(u"page_13")
        self.page_13.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB13 = QLabel(self.page_13)
        self.StatusB13.setObjectName(u"StatusB13")
        self.StatusB13.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB13.setFrameShape(QFrame.Box)
        self.StatusB13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SugSpeedB13 = QLabel(self.page_13)
        self.SugSpeedB13.setObjectName(u"SugSpeedB13")
        self.SugSpeedB13.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB13.setFrameShape(QFrame.Box)
        self.SugSpeedB13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_75 = QLabel(self.page_13)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(10, 0, 101, 16))
        self.label_75.setFrameShape(QFrame.Box)
        self.label_77 = QLabel(self.page_13)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(10, 20, 101, 16))
        self.label_77.setFrameShape(QFrame.Box)
        self.label_74 = QLabel(self.page_13)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(10, 40, 101, 16))
        self.label_74.setFrameShape(QFrame.Box)
        self.OccupationB13 = QLabel(self.page_13)
        self.OccupationB13.setObjectName(u"OccupationB13")
        self.OccupationB13.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB13.setFrameShape(QFrame.Box)
        self.OccupationB13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.AuthorityB13 = QLabel(self.page_13)
        self.AuthorityB13.setObjectName(u"AuthorityB13")
        self.AuthorityB13.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB13.setFrameShape(QFrame.Box)
        self.AuthorityB13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_163 = QLabel(self.page_13)
        self.label_163.setObjectName(u"label_163")
        self.label_163.setGeometry(QRect(10, 60, 101, 16))
        self.label_163.setFrameShape(QFrame.Box)
        self.toolBox_3.addItem(self.page_13, u"Block 13")
        self.page_14 = QWidget()
        self.page_14.setObjectName(u"page_14")
        self.page_14.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB14 = QLabel(self.page_14)
        self.StatusB14.setObjectName(u"StatusB14")
        self.StatusB14.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB14.setFrameShape(QFrame.Box)
        self.StatusB14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_165 = QLabel(self.page_14)
        self.label_165.setObjectName(u"label_165")
        self.label_165.setGeometry(QRect(10, 60, 101, 16))
        self.label_165.setFrameShape(QFrame.Box)
        self.label_83 = QLabel(self.page_14)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(10, 20, 101, 16))
        self.label_83.setFrameShape(QFrame.Box)
        self.label_81 = QLabel(self.page_14)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(10, 0, 101, 16))
        self.label_81.setFrameShape(QFrame.Box)
        self.SugSpeedB14 = QLabel(self.page_14)
        self.SugSpeedB14.setObjectName(u"SugSpeedB14")
        self.SugSpeedB14.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB14.setFrameShape(QFrame.Box)
        self.SugSpeedB14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_80 = QLabel(self.page_14)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(10, 40, 101, 16))
        self.label_80.setFrameShape(QFrame.Box)
        self.AuthorityB14 = QLabel(self.page_14)
        self.AuthorityB14.setObjectName(u"AuthorityB14")
        self.AuthorityB14.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB14.setFrameShape(QFrame.Box)
        self.AuthorityB14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.OccupationB14 = QLabel(self.page_14)
        self.OccupationB14.setObjectName(u"OccupationB14")
        self.OccupationB14.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB14.setFrameShape(QFrame.Box)
        self.OccupationB14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.toolBox_3.addItem(self.page_14, u"Block 14")
        self.page_15 = QWidget()
        self.page_15.setObjectName(u"page_15")
        self.page_15.setGeometry(QRect(0, 0, 221, 79))
        self.StatusB15 = QLabel(self.page_15)
        self.StatusB15.setObjectName(u"StatusB15")
        self.StatusB15.setGeometry(QRect(110, 0, 101, 16))
        self.StatusB15.setFrameShape(QFrame.Box)
        self.StatusB15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_89 = QLabel(self.page_15)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(10, 20, 101, 16))
        self.label_89.setFrameShape(QFrame.Box)
        self.label_167 = QLabel(self.page_15)
        self.label_167.setObjectName(u"label_167")
        self.label_167.setGeometry(QRect(10, 60, 101, 16))
        self.label_167.setFrameShape(QFrame.Box)
        self.OccupationB15 = QLabel(self.page_15)
        self.OccupationB15.setObjectName(u"OccupationB15")
        self.OccupationB15.setGeometry(QRect(110, 20, 101, 16))
        self.OccupationB15.setFrameShape(QFrame.Box)
        self.OccupationB15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.AuthorityB15 = QLabel(self.page_15)
        self.AuthorityB15.setObjectName(u"AuthorityB15")
        self.AuthorityB15.setGeometry(QRect(110, 40, 101, 16))
        self.AuthorityB15.setFrameShape(QFrame.Box)
        self.AuthorityB15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_86 = QLabel(self.page_15)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(10, 40, 101, 16))
        self.label_86.setFrameShape(QFrame.Box)
        self.SugSpeedB15 = QLabel(self.page_15)
        self.SugSpeedB15.setObjectName(u"SugSpeedB15")
        self.SugSpeedB15.setGeometry(QRect(110, 60, 101, 16))
        self.SugSpeedB15.setFrameShape(QFrame.Box)
        self.SugSpeedB15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_87 = QLabel(self.page_15)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(10, 0, 101, 16))
        self.label_87.setFrameShape(QFrame.Box)
        self.toolBox_3.addItem(self.page_15, u"Block 15")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.line = QFrame(self.TrackStatus)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 0, 821, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_92 = QLabel(self.TrackStatus)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(340, 190, 31, 16))
        self.label_92.setFrameShape(QFrame.Box)
        self.label_92.setAlignment(Qt.AlignCenter)
        self.label_93 = QLabel(self.TrackStatus)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(370, 190, 31, 16))
        self.label_93.setFrameShape(QFrame.Box)
        self.label_93.setAlignment(Qt.AlignCenter)
        self.label_94 = QLabel(self.TrackStatus)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(400, 190, 31, 16))
        self.label_94.setFrameShape(QFrame.Box)
        self.label_94.setAlignment(Qt.AlignCenter)
        self.label_95 = QLabel(self.TrackStatus)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(430, 190, 31, 16))
        self.label_95.setFrameShape(QFrame.Box)
        self.label_95.setAlignment(Qt.AlignCenter)
        self.label_96 = QLabel(self.TrackStatus)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(460, 190, 31, 16))
        self.label_96.setFrameShape(QFrame.Box)
        self.label_96.setAlignment(Qt.AlignCenter)
        self.label_107 = QLabel(self.TrackStatus)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(520, 170, 31, 16))
        self.label_107.setFrameShape(QFrame.Box)
        self.label_107.setAlignment(Qt.AlignCenter)
        self.label_108 = QLabel(self.TrackStatus)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setGeometry(QRect(520, 210, 31, 16))
        self.label_108.setFrameShape(QFrame.Box)
        self.label_108.setAlignment(Qt.AlignCenter)
        self.label_109 = QLabel(self.TrackStatus)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(550, 160, 31, 16))
        self.label_109.setFrameShape(QFrame.Box)
        self.label_109.setAlignment(Qt.AlignCenter)
        self.label_110 = QLabel(self.TrackStatus)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(550, 220, 31, 16))
        self.label_110.setFrameShape(QFrame.Box)
        self.label_110.setAlignment(Qt.AlignCenter)
        self.label_111 = QLabel(self.TrackStatus)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setGeometry(QRect(580, 230, 31, 16))
        self.label_111.setFrameShape(QFrame.Box)
        self.label_111.setAlignment(Qt.AlignCenter)
        self.label_112 = QLabel(self.TrackStatus)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setGeometry(QRect(580, 150, 31, 16))
        self.label_112.setFrameShape(QFrame.Box)
        self.label_112.setAlignment(Qt.AlignCenter)
        self.label_113 = QLabel(self.TrackStatus)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setGeometry(QRect(610, 140, 31, 16))
        self.label_113.setFrameShape(QFrame.Box)
        self.label_113.setAlignment(Qt.AlignCenter)
        self.label_114 = QLabel(self.TrackStatus)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setGeometry(QRect(640, 130, 31, 16))
        self.label_114.setFrameShape(QFrame.Box)
        self.label_114.setAlignment(Qt.AlignCenter)
        self.label_115 = QLabel(self.TrackStatus)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(610, 240, 31, 16))
        self.label_115.setFrameShape(QFrame.Box)
        self.label_115.setAlignment(Qt.AlignCenter)
        self.label_116 = QLabel(self.TrackStatus)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(640, 250, 31, 16))
        self.label_116.setFrameShape(QFrame.Box)
        self.label_116.setAlignment(Qt.AlignCenter)
        self.label_97 = QLabel(self.TrackStatus)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(670, 110, 81, 41))
        self.label_97.setFrameShape(QFrame.Box)
        self.label_97.setAlignment(Qt.AlignCenter)
        self.label_98 = QLabel(self.TrackStatus)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(670, 240, 81, 41))
        self.label_98.setFrameShape(QFrame.Box)
        self.label_98.setAlignment(Qt.AlignCenter)
        self.label_99 = QLabel(self.TrackStatus)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(260, 180, 81, 41))
        self.label_99.setFrameShape(QFrame.Box)
        self.label_99.setAlignment(Qt.AlignCenter)
        self.label_117 = QLabel(self.TrackStatus)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(490, 180, 31, 16))
        self.label_117.setFrameShape(QFrame.Panel)
        self.label_117.setFrameShadow(QFrame.Plain)
        self.label_117.setAlignment(Qt.AlignCenter)
        self.label_118 = QLabel(self.TrackStatus)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setGeometry(QRect(490, 200, 31, 16))
        self.label_118.setFrameShape(QFrame.Box)
        self.label_118.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.TrackStatus, "")
        self.SignalStatus = QWidget()
        self.SignalStatus.setObjectName(u"SignalStatus")
        self.label_190 = QLabel(self.SignalStatus)
        self.label_190.setObjectName(u"label_190")
        self.label_190.setGeometry(QRect(640, 130, 31, 16))
        self.label_190.setFrameShape(QFrame.Box)
        self.label_190.setAlignment(Qt.AlignCenter)
        self.label_191 = QLabel(self.SignalStatus)
        self.label_191.setObjectName(u"label_191")
        self.label_191.setGeometry(QRect(670, 110, 81, 41))
        self.label_191.setFrameShape(QFrame.Box)
        self.label_191.setAlignment(Qt.AlignCenter)
        self.label_192 = QLabel(self.SignalStatus)
        self.label_192.setObjectName(u"label_192")
        self.label_192.setGeometry(QRect(340, 190, 31, 16))
        self.label_192.setFrameShape(QFrame.Box)
        self.label_192.setAlignment(Qt.AlignCenter)
        self.label_193 = QLabel(self.SignalStatus)
        self.label_193.setObjectName(u"label_193")
        self.label_193.setGeometry(QRect(430, 190, 31, 16))
        self.label_193.setFrameShape(QFrame.Box)
        self.label_193.setAlignment(Qt.AlignCenter)
        self.label_194 = QLabel(self.SignalStatus)
        self.label_194.setObjectName(u"label_194")
        self.label_194.setGeometry(QRect(460, 190, 31, 16))
        self.label_194.setFrameShape(QFrame.Box)
        self.label_194.setAlignment(Qt.AlignCenter)
        self.label_195 = QLabel(self.SignalStatus)
        self.label_195.setObjectName(u"label_195")
        self.label_195.setGeometry(QRect(610, 240, 31, 16))
        self.label_195.setFrameShape(QFrame.Box)
        self.label_195.setAlignment(Qt.AlignCenter)
        self.label_196 = QLabel(self.SignalStatus)
        self.label_196.setObjectName(u"label_196")
        self.label_196.setGeometry(QRect(550, 220, 31, 16))
        self.label_196.setFrameShape(QFrame.Box)
        self.label_196.setAlignment(Qt.AlignCenter)
        self.label_197 = QLabel(self.SignalStatus)
        self.label_197.setObjectName(u"label_197")
        self.label_197.setGeometry(QRect(580, 230, 31, 16))
        self.label_197.setFrameShape(QFrame.Box)
        self.label_197.setAlignment(Qt.AlignCenter)
        self.label_198 = QLabel(self.SignalStatus)
        self.label_198.setObjectName(u"label_198")
        self.label_198.setGeometry(QRect(490, 180, 31, 16))
        self.label_198.setFrameShape(QFrame.Panel)
        self.label_198.setFrameShadow(QFrame.Plain)
        self.label_198.setAlignment(Qt.AlignCenter)
        self.label_199 = QLabel(self.SignalStatus)
        self.label_199.setObjectName(u"label_199")
        self.label_199.setGeometry(QRect(640, 250, 31, 16))
        self.label_199.setFrameShape(QFrame.Box)
        self.label_199.setAlignment(Qt.AlignCenter)
        self.label_200 = QLabel(self.SignalStatus)
        self.label_200.setObjectName(u"label_200")
        self.label_200.setGeometry(QRect(610, 140, 31, 16))
        self.label_200.setFrameShape(QFrame.Box)
        self.label_200.setAlignment(Qt.AlignCenter)
        self.label_201 = QLabel(self.SignalStatus)
        self.label_201.setObjectName(u"label_201")
        self.label_201.setGeometry(QRect(580, 150, 31, 16))
        self.label_201.setFrameShape(QFrame.Box)
        self.label_201.setAlignment(Qt.AlignCenter)
        self.label_202 = QLabel(self.SignalStatus)
        self.label_202.setObjectName(u"label_202")
        self.label_202.setGeometry(QRect(550, 160, 31, 16))
        self.label_202.setFrameShape(QFrame.Box)
        self.label_202.setAlignment(Qt.AlignCenter)
        self.label_203 = QLabel(self.SignalStatus)
        self.label_203.setObjectName(u"label_203")
        self.label_203.setGeometry(QRect(370, 190, 31, 16))
        self.label_203.setFrameShape(QFrame.Box)
        self.label_203.setAlignment(Qt.AlignCenter)
        self.label_204 = QLabel(self.SignalStatus)
        self.label_204.setObjectName(u"label_204")
        self.label_204.setGeometry(QRect(260, 180, 81, 41))
        self.label_204.setFrameShape(QFrame.Box)
        self.label_204.setAlignment(Qt.AlignCenter)
        self.label_205 = QLabel(self.SignalStatus)
        self.label_205.setObjectName(u"label_205")
        self.label_205.setGeometry(QRect(520, 170, 31, 16))
        self.label_205.setFrameShape(QFrame.Box)
        self.label_205.setAlignment(Qt.AlignCenter)
        self.label_206 = QLabel(self.SignalStatus)
        self.label_206.setObjectName(u"label_206")
        self.label_206.setGeometry(QRect(670, 240, 81, 41))
        self.label_206.setFrameShape(QFrame.Box)
        self.label_206.setAlignment(Qt.AlignCenter)
        self.label_207 = QLabel(self.SignalStatus)
        self.label_207.setObjectName(u"label_207")
        self.label_207.setGeometry(QRect(520, 210, 31, 16))
        self.label_207.setFrameShape(QFrame.Box)
        self.label_207.setAlignment(Qt.AlignCenter)
        self.label_208 = QLabel(self.SignalStatus)
        self.label_208.setObjectName(u"label_208")
        self.label_208.setGeometry(QRect(490, 200, 31, 16))
        self.label_208.setFrameShape(QFrame.Box)
        self.label_208.setAlignment(Qt.AlignCenter)
        self.label_209 = QLabel(self.SignalStatus)
        self.label_209.setObjectName(u"label_209")
        self.label_209.setGeometry(QRect(400, 190, 31, 16))
        self.label_209.setFrameShape(QFrame.Box)
        self.label_209.setAlignment(Qt.AlignCenter)
        self.tabWidget_4 = QTabWidget(self.SignalStatus)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        self.tabWidget_4.setGeometry(QRect(0, 10, 231, 381))
        self.tabWidget_4.setTabShape(QTabWidget.Triangular)
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.label_2 = QLabel(self.tab_9)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 101, 16))
        self.label_2.setFrameShape(QFrame.Box)
        self.label_3 = QLabel(self.tab_9)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 10, 101, 16))
        self.label_3.setFrameShape(QFrame.Box)
        self.label_5 = QLabel(self.tab_9)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(110, 30, 101, 16))
        self.label_5.setFrameShape(QFrame.Box)
        self.label_4 = QLabel(self.tab_9)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 101, 16))
        self.label_4.setFrameShape(QFrame.Box)
        self.tabWidget_4.addTab(self.tab_9, "")
        self.line_2 = QFrame(self.SignalStatus)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 0, 821, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.SignalStatus, "")
        self.Program = QWidget()
        self.Program.setObjectName(u"Program")
        self.line_3 = QFrame(self.Program)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 0, 821, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.TMButton = QPushButton(self.Program)
        self.TMButton.setObjectName(u"TMButton")
        self.TMButton.setGeometry(QRect(30, 360, 111, 23))
        self.label_6 = QLabel(self.Program)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 30, 231, 16))
        self.label_6.setFrameShape(QFrame.Box)
        self.label_7 = QLabel(self.Program)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(50, 330, 121, 21))
        self.label_7.setFrameShape(QFrame.Box)
        self.label_8 = QLabel(self.Program)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 260, 71, 16))
        self.label_8.setFrameShape(QFrame.Box)
        self.label_9 = QLabel(self.Program)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 130, 121, 21))
        self.label_9.setFrameShape(QFrame.Box)
        self.AuthorityInput = QLineEdit(self.Program)
        self.AuthorityInput.setObjectName(u"AuthorityInput")
        self.AuthorityInput.setGeometry(QRect(180, 160, 113, 20))
        self.ClosedTrackInput = QLineEdit(self.Program)
        self.ClosedTrackInput.setObjectName(u"ClosedTrackInput")
        self.ClosedTrackInput.setGeometry(QRect(180, 190, 113, 20))
        self.label_10 = QLabel(self.Program)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 160, 121, 21))
        self.label_10.setFrameShape(QFrame.Box)
        self.label_11 = QLabel(self.Program)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 190, 121, 21))
        self.label_11.setFrameShape(QFrame.Box)
        self.label_12 = QLabel(self.Program)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 60, 61, 16))
        self.label_12.setFrameShape(QFrame.Box)
        self.SugSpeedInput = QLineEdit(self.Program)
        self.SugSpeedInput.setObjectName(u"SugSpeedInput")
        self.SugSpeedInput.setGeometry(QRect(180, 130, 113, 20))
        self.TrackOccInput = QLineEdit(self.Program)
        self.TrackOccInput.setObjectName(u"TrackOccInput")
        self.TrackOccInput.setGeometry(QRect(180, 330, 113, 20))
        self.line_4 = QFrame(self.Program)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(353, 10, 20, 381))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.OutputButton = QPushButton(self.Program)
        self.OutputButton.setObjectName(u"OutputButton")
        self.OutputButton.setGeometry(QRect(390, 300, 75, 23))
        self.label_13 = QLabel(self.Program)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(390, 280, 101, 16))
        self.label_13.setFrameShape(QFrame.Box)
        self.LightSignalOutput = QLabel(self.Program)
        self.LightSignalOutput.setObjectName(u"LightSignalOutput")
        self.LightSignalOutput.setGeometry(QRect(500, 280, 101, 16))
        self.LightSignalOutput.setFrameShape(QFrame.Box)
        self.label_14 = QLabel(self.Program)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(390, 110, 101, 16))
        self.label_14.setFrameShape(QFrame.Box)
        self.label_16 = QLabel(self.Program)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(370, 30, 261, 16))
        self.label_16.setFrameShape(QFrame.Box)
        self.OccupancyOutput = QLabel(self.Program)
        self.OccupancyOutput.setObjectName(u"OccupancyOutput")
        self.OccupancyOutput.setGeometry(QRect(500, 110, 101, 16))
        self.OccupancyOutput.setFrameShape(QFrame.Box)
        self.label_18 = QLabel(self.Program)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(390, 220, 101, 16))
        self.label_18.setFrameShape(QFrame.Box)
        self.SwitchPosOutput = QLabel(self.Program)
        self.SwitchPosOutput.setObjectName(u"SwitchPosOutput")
        self.SwitchPosOutput.setGeometry(QRect(500, 260, 101, 16))
        self.SwitchPosOutput.setFrameShape(QFrame.Box)
        self.SwitchStateOutput = QLabel(self.Program)
        self.SwitchStateOutput.setObjectName(u"SwitchStateOutput")
        self.SwitchStateOutput.setGeometry(QRect(500, 90, 101, 16))
        self.SwitchStateOutput.setFrameShape(QFrame.Box)
        self.ClearButton = QPushButton(self.Program)
        self.ClearButton.setObjectName(u"ClearButton")
        self.ClearButton.setGeometry(QRect(610, 340, 141, 23))
        self.label_21 = QLabel(self.Program)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(370, 150, 101, 16))
        self.label_21.setFrameShape(QFrame.Box)
        self.ComSpeedOutput = QLabel(self.Program)
        self.ComSpeedOutput.setObjectName(u"ComSpeedOutput")
        self.ComSpeedOutput.setGeometry(QRect(500, 240, 101, 16))
        self.ComSpeedOutput.setFrameShape(QFrame.Box)
        self.AuthorityOutput = QLabel(self.Program)
        self.AuthorityOutput.setObjectName(u"AuthorityOutput")
        self.AuthorityOutput.setGeometry(QRect(500, 220, 101, 16))
        self.AuthorityOutput.setFrameShape(QFrame.Box)
        self.label_24 = QLabel(self.Program)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(390, 240, 101, 16))
        self.label_24.setFrameShape(QFrame.Box)
        self.label_25 = QLabel(self.Program)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(390, 260, 101, 16))
        self.label_25.setFrameShape(QFrame.Box)
        self.label_26 = QLabel(self.Program)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(370, 70, 101, 16))
        self.label_26.setFrameShape(QFrame.Box)
        self.label_27 = QLabel(self.Program)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(390, 90, 101, 16))
        self.label_27.setFrameShape(QFrame.Box)
        self.BlockOutInput = QLineEdit(self.Program)
        self.BlockOutInput.setObjectName(u"BlockOutInput")
        self.BlockOutInput.setGeometry(QRect(500, 190, 113, 20))
        self.label_28 = QLabel(self.Program)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(390, 190, 101, 21))
        self.label_28.setFrameShape(QFrame.Box)
        self.label_29 = QLabel(self.Program)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(390, 170, 261, 16))
        self.label_29.setFrameShape(QFrame.Box)
        self.label_30 = QLabel(self.Program)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(50, 280, 261, 16))
        self.label_30.setFrameShape(QFrame.Box)
        self.label_31 = QLabel(self.Program)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(50, 300, 121, 21))
        self.label_31.setFrameShape(QFrame.Box)
        self.TMTrackBlockInput = QLineEdit(self.Program)
        self.TMTrackBlockInput.setObjectName(u"TMTrackBlockInput")
        self.TMTrackBlockInput.setGeometry(QRect(180, 300, 113, 20))
        self.label_34 = QLabel(self.Program)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(50, 80, 261, 16))
        self.label_34.setFrameShape(QFrame.Box)
        self.CTCTrackBlockInput = QLineEdit(self.Program)
        self.CTCTrackBlockInput.setObjectName(u"CTCTrackBlockInput")
        self.CTCTrackBlockInput.setGeometry(QRect(180, 100, 113, 20))
        self.label_36 = QLabel(self.Program)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(50, 100, 121, 21))
        self.label_36.setFrameShape(QFrame.Box)
        self.CTCButton = QPushButton(self.Program)
        self.CTCButton.setObjectName(u"CTCButton")
        self.CTCButton.setGeometry(QRect(30, 220, 111, 23))
        self.tabWidget.addTab(self.Program, "")
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(0, 440, 821, 111))
        self.plainTextEdit.setTabChangesFocus(False)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 420, 91, 21))
        self.label.setFrameShape(QFrame.Box)
        TrackControllerUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TrackControllerUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 765, 22))
        TrackControllerUI.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TrackControllerUI)
        self.statusbar.setObjectName(u"statusbar")
        TrackControllerUI.setStatusBar(self.statusbar)

        self.retranslateUi(TrackControllerUI)

        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(3)
        self.toolBox_2.setCurrentIndex(3)
        self.toolBox_4.setCurrentIndex(2)
        self.toolBox_3.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(TrackControllerUI)
    # setupUi

    def retranslateUi(self, TrackControllerUI):
        TrackControllerUI.setWindowTitle(QCoreApplication.translate("TrackControllerUI", u"MainWindow", None))
        self.StatusB1.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.AuthorityB1.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_145.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.SugSpeedB1.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_142.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_141.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.OccupationB1.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.label_143.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("TrackControllerUI", u"Block 1", None))
        self.StatusB2.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.SugSpeedB2.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_137.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_133.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.OccupationB2.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.label_135.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.AuthorityB2.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_134.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("TrackControllerUI", u"Block 2", None))
        self.StatusB3.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.OccupationB3.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.label_127.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.label_125.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.SugSpeedB3.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.AuthorityB3.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_129.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_126.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("TrackControllerUI", u"Block 3", None))
        self.SugSpeedB4.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_119.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.AuthorityB4.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.StatusB4.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.label_106.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_105.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.OccupationB4.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.label_121.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QCoreApplication.translate("TrackControllerUI", u"Block 4", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), QCoreApplication.translate("TrackControllerUI", u"Controller 1", None))
        self.StatusB5.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.OccupationB5.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.SugSpeedB5.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_157.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_35.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.AuthorityB5.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_32.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.label_33.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), QCoreApplication.translate("TrackControllerUI", u"Block 5", None))
        self.StatusB6.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.SugSpeedB6.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_38.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.label_41.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_155.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.AuthorityB6.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_39.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.OccupationB6.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), QCoreApplication.translate("TrackControllerUI", u"Block 6", None))
        self.StatusB11.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.OccupationB11.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.label_45.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.label_153.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.AuthorityB11.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_47.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.SugSpeedB11.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_44.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), QCoreApplication.translate("TrackControllerUI", u"Block 11", None))
        self.SwitchDisp.setText(QCoreApplication.translate("TrackControllerUI", u"B", None))
        self.label_51.setText(QCoreApplication.translate("TrackControllerUI", u"Connecting Section", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_9), QCoreApplication.translate("TrackControllerUI", u"Switch 1", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), QCoreApplication.translate("TrackControllerUI", u"Controller 2", None))
        self.StatusB7.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.OccupationB7.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.SugSpeedB7.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_169.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_102.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.label_103.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_148.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.AuthorityB7.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_16), QCoreApplication.translate("TrackControllerUI", u"Block 7", None))
        self.StatusB8.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.SugSpeedB8.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_151.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.label_158.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_159.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.OccupationB8.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.AuthorityB8.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_173.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_17), QCoreApplication.translate("TrackControllerUI", u"Block 8", None))
        self.StatusB9.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.label_175.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_176.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_177.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.SugSpeedB9.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_179.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.AuthorityB9.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.OccupationB9.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_18), QCoreApplication.translate("TrackControllerUI", u"Block 9", None))
        self.StatusB10.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.label_183.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_184.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.OccupationB10.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.AuthorityB10.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_187.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.SugSpeedB10.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_189.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_19), QCoreApplication.translate("TrackControllerUI", u"Block 10", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("TrackControllerUI", u"Controller 3", None))
        self.StatusB12.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.OccupationB12.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.SugSpeedB12.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_161.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_68.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.label_71.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_69.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.AuthorityB12.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_12), QCoreApplication.translate("TrackControllerUI", u"Block 12", None))
        self.StatusB13.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.SugSpeedB13.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_75.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.label_77.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_74.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.OccupationB13.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.AuthorityB13.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_163.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_13), QCoreApplication.translate("TrackControllerUI", u"Block 13", None))
        self.StatusB14.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.label_165.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_83.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_81.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.SugSpeedB14.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_80.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.AuthorityB14.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.OccupationB14.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_14), QCoreApplication.translate("TrackControllerUI", u"Block 14", None))
        self.StatusB15.setText(QCoreApplication.translate("TrackControllerUI", u"Unbroken", None))
        self.label_89.setText(QCoreApplication.translate("TrackControllerUI", u"Occupation", None))
        self.label_167.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.OccupationB15.setText(QCoreApplication.translate("TrackControllerUI", u"Unoccupied", None))
        self.AuthorityB15.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_86.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.SugSpeedB15.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.label_87.setText(QCoreApplication.translate("TrackControllerUI", u"Status", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_15), QCoreApplication.translate("TrackControllerUI", u"Block 15", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("TrackControllerUI", u"Controller 4", None))
        self.label_92.setText(QCoreApplication.translate("TrackControllerUI", u"1", None))
        self.label_93.setText(QCoreApplication.translate("TrackControllerUI", u"2", None))
        self.label_94.setText(QCoreApplication.translate("TrackControllerUI", u"3", None))
        self.label_95.setText(QCoreApplication.translate("TrackControllerUI", u"4", None))
        self.label_96.setText(QCoreApplication.translate("TrackControllerUI", u"5", None))
        self.label_107.setText(QCoreApplication.translate("TrackControllerUI", u"6", None))
        self.label_108.setText(QCoreApplication.translate("TrackControllerUI", u"11", None))
        self.label_109.setText(QCoreApplication.translate("TrackControllerUI", u"7", None))
        self.label_110.setText(QCoreApplication.translate("TrackControllerUI", u"12", None))
        self.label_111.setText(QCoreApplication.translate("TrackControllerUI", u"13", None))
        self.label_112.setText(QCoreApplication.translate("TrackControllerUI", u"8", None))
        self.label_113.setText(QCoreApplication.translate("TrackControllerUI", u"9", None))
        self.label_114.setText(QCoreApplication.translate("TrackControllerUI", u"10", None))
        self.label_115.setText(QCoreApplication.translate("TrackControllerUI", u"14", None))
        self.label_116.setText(QCoreApplication.translate("TrackControllerUI", u"15", None))
        self.label_97.setText(QCoreApplication.translate("TrackControllerUI", u"Station B", None))
        self.label_98.setText(QCoreApplication.translate("TrackControllerUI", u"Station C", None))
        self.label_99.setText(QCoreApplication.translate("TrackControllerUI", u"Yard", None))
        self.label_117.setText(QCoreApplication.translate("TrackControllerUI", u"ON", None))
        self.label_118.setText(QCoreApplication.translate("TrackControllerUI", u"OFF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TrackStatus), QCoreApplication.translate("TrackControllerUI", u"Track Status", None))
        self.label_190.setText(QCoreApplication.translate("TrackControllerUI", u"10", None))
        self.label_191.setText(QCoreApplication.translate("TrackControllerUI", u"Station B", None))
        self.label_192.setText(QCoreApplication.translate("TrackControllerUI", u"1", None))
        self.label_193.setText(QCoreApplication.translate("TrackControllerUI", u"4", None))
        self.label_194.setText(QCoreApplication.translate("TrackControllerUI", u"5", None))
        self.label_195.setText(QCoreApplication.translate("TrackControllerUI", u"14", None))
        self.label_196.setText(QCoreApplication.translate("TrackControllerUI", u"12", None))
        self.label_197.setText(QCoreApplication.translate("TrackControllerUI", u"13", None))
        self.label_198.setText(QCoreApplication.translate("TrackControllerUI", u"ON", None))
        self.label_199.setText(QCoreApplication.translate("TrackControllerUI", u"15", None))
        self.label_200.setText(QCoreApplication.translate("TrackControllerUI", u"9", None))
        self.label_201.setText(QCoreApplication.translate("TrackControllerUI", u"8", None))
        self.label_202.setText(QCoreApplication.translate("TrackControllerUI", u"7", None))
        self.label_203.setText(QCoreApplication.translate("TrackControllerUI", u"2", None))
        self.label_204.setText(QCoreApplication.translate("TrackControllerUI", u"Yard", None))
        self.label_205.setText(QCoreApplication.translate("TrackControllerUI", u"6", None))
        self.label_206.setText(QCoreApplication.translate("TrackControllerUI", u"Station C", None))
        self.label_207.setText(QCoreApplication.translate("TrackControllerUI", u"11", None))
        self.label_208.setText(QCoreApplication.translate("TrackControllerUI", u"OFF", None))
        self.label_209.setText(QCoreApplication.translate("TrackControllerUI", u"3", None))
        self.label_2.setText(QCoreApplication.translate("TrackControllerUI", u"Gate", None))
        self.label_3.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_5.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_4.setText(QCoreApplication.translate("TrackControllerUI", u"Lights", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), QCoreApplication.translate("TrackControllerUI", u"No Crossings Detected", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SignalStatus), QCoreApplication.translate("TrackControllerUI", u"Signal Status", None))
        self.TMButton.setText(QCoreApplication.translate("TrackControllerUI", u"Confirm Track Input", None))
        self.label_6.setText(QCoreApplication.translate("TrackControllerUI", u"Please enter the inputs to the system below:", None))
        self.label_7.setText(QCoreApplication.translate("TrackControllerUI", u"Track Occupancy", None))
        self.label_8.setText(QCoreApplication.translate("TrackControllerUI", u"Track Model", None))
        self.label_9.setText(QCoreApplication.translate("TrackControllerUI", u"Suggested Speed", None))
        self.label_10.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.label_11.setText(QCoreApplication.translate("TrackControllerUI", u"Block Status", None))
        self.label_12.setText(QCoreApplication.translate("TrackControllerUI", u"CTC Office", None))
        self.OutputButton.setText(QCoreApplication.translate("TrackControllerUI", u"Update", None))
        self.label_13.setText(QCoreApplication.translate("TrackControllerUI", u"Crossing Signal", None))
        self.LightSignalOutput.setText(QCoreApplication.translate("TrackControllerUI", u"N/A", None))
        self.label_14.setText(QCoreApplication.translate("TrackControllerUI", u"Occupancy", None))
        self.label_16.setText(QCoreApplication.translate("TrackControllerUI", u"Below is the display for the outputs:", None))
        self.OccupancyOutput.setText(QCoreApplication.translate("TrackControllerUI", u"000000000000000", None))
        self.label_18.setText(QCoreApplication.translate("TrackControllerUI", u"Authority", None))
        self.SwitchPosOutput.setText(QCoreApplication.translate("TrackControllerUI", u"B", None))
        self.SwitchStateOutput.setText(QCoreApplication.translate("TrackControllerUI", u"B", None))
        self.ClearButton.setText(QCoreApplication.translate("TrackControllerUI", u"Clear the System", None))
        self.label_21.setText(QCoreApplication.translate("TrackControllerUI", u"Track Model", None))
        self.ComSpeedOutput.setText(QCoreApplication.translate("TrackControllerUI", u"0 MPH", None))
        self.AuthorityOutput.setText(QCoreApplication.translate("TrackControllerUI", u"15", None))
        self.label_24.setText(QCoreApplication.translate("TrackControllerUI", u"Commanded Speed", None))
        self.label_25.setText(QCoreApplication.translate("TrackControllerUI", u"Switch Positions", None))
        self.label_26.setText(QCoreApplication.translate("TrackControllerUI", u"CTC Office", None))
        self.label_27.setText(QCoreApplication.translate("TrackControllerUI", u"Switch State", None))
        self.BlockOutInput.setText("")
        self.label_28.setText(QCoreApplication.translate("TrackControllerUI", u"Track Block", None))
        self.label_29.setText(QCoreApplication.translate("TrackControllerUI", u"Enter a Track Block below for information", None))
        self.label_30.setText(QCoreApplication.translate("TrackControllerUI", u"Enter a Track Block below for track block Input", None))
        self.label_31.setText(QCoreApplication.translate("TrackControllerUI", u"Track Block", None))
        self.TMTrackBlockInput.setText("")
        self.label_34.setText(QCoreApplication.translate("TrackControllerUI", u"Enter a Track Block below for CTC input", None))
        self.CTCTrackBlockInput.setText("")
        self.label_36.setText(QCoreApplication.translate("TrackControllerUI", u"Track Block", None))
        self.CTCButton.setText(QCoreApplication.translate("TrackControllerUI", u"Confirm CTC Input", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Program), QCoreApplication.translate("TrackControllerUI", u"I/O", None))
        self.label.setText(QCoreApplication.translate("TrackControllerUI", u"Terminal Window", None))
    # retranslateUi

