# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Design.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1303, 1041)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 20, 291, 41))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 106, 220);")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(320, 20, 301, 41))
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 106, 220);")
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(630, 20, 301, 41))
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 106, 220);")
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(940, 20, 291, 41))
        self.pushButton_6.setFont(font)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 106, 220);")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 70, 1231, 861))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label_13 = QLabel(self.page)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 150, 1211, 41))
        self.label_13.setFont(font)
        self.label_13.setCursor(QCursor(Qt.UpArrowCursor))
        self.label_13.setStyleSheet(u"background-color: rgb(197, 220, 255);")
        self.label_13.setFrameShape(QFrame.Box)
        self.label_13.setFrameShadow(QFrame.Plain)
        self.label_13.setLineWidth(1)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.tableWidget = QTableWidget(self.page)
        if (self.tableWidget.columnCount() < 4):
            self.tableWidget.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 190, 1211, 661))
        font1 = QFont()
        font1.setPointSize(10)
        self.tableWidget.setFont(font1)
        self.tableWidget.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShadow(QFrame.Plain)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(302)
        self.tableWidget.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.groupBox = QGroupBox(self.page)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(350, 10, 431, 121))
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(u"")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 30, 221, 41))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        self.label_8.setFont(font2)
        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(240, 40, 181, 31))
        self.pushButton_4.setFont(font2)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet(u"background-color: rgb(255, 246, 219);")
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 70, 221, 41))
        self.label_9.setFont(font2)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(200, 70, 221, 41))
        self.label_10.setFont(font2)
        self.label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 111, 41))
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QFrame.Box)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 331, 41))
        self.label.setFont(font1)
        self.label.setStyleSheet(u"background-color: rgb(197, 220, 255);")
        self.label.setFrameShape(QFrame.Box)
        self.label.setFrameShadow(QFrame.Plain)
        self.label.setAlignment(Qt.AlignCenter)
        self.groupBox_2 = QGroupBox(self.page)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(790, 10, 431, 121))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 30, 221, 41))
        self.label_11.setFont(font2)
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 70, 221, 41))
        self.label_12.setFont(font2)
        self.comboBox = QComboBox(self.groupBox_2)
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(170, 40, 251, 31))
        self.comboBox.setFont(font2)
        self.comboBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit = QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(170, 80, 113, 31))
        self.lineEdit.setFont(font2)
        self.pushButton_5 = QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(290, 80, 131, 31))
        self.pushButton_5.setFont(font2)
        self.pushButton_5.setStyleSheet(u"background-color: rgb(255, 246, 219);")
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 90, 111, 41))
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_5.setFrameShape(QFrame.Box)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(120, 90, 111, 41))
        self.label_6.setFont(font1)
        self.label_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_6.setFrameShape(QFrame.Box)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(120, 50, 111, 41))
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_3.setFrameShape(QFrame.Box)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(230, 50, 111, 41))
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QFrame.Box)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 90, 111, 41))
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_7.setFrameShape(QFrame.Box)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.tableWidget_2 = QTableWidget(self.page_2)
        if (self.tableWidget_2.columnCount() < 5):
            self.tableWidget_2.setColumnCount(5)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, __qtablewidgetitem8)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(10, 10, 1211, 841))
        self.tableWidget_2.setFont(font1)
        self.tableWidget_2.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_2.setAutoFillBackground(False)
        self.tableWidget_2.setFrameShadow(QFrame.Plain)
        self.tableWidget_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(242)
        self.tableWidget_2.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_14 = QLabel(self.page_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 20, 181, 51))
        self.label_14.setFont(font1)
        self.label_14.setStyleSheet(u"background-color: rgb(197, 220, 255);")
        self.label_14.setFrameShape(QFrame.Box)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.tabWidget = QTabWidget(self.page_3)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(200, 20, 361, 211))
        self.tabWidget.setFont(font1)
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 20, 161, 31))
        self.label_15.setFont(font1)
        self.comboBox_2 = QComboBox(self.tab)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(160, 20, 181, 31))
        self.comboBox_2.setFont(font1)
        self.comboBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 50, 181, 61))
        self.label_16.setFont(font1)
        self.label_16.setWordWrap(True)
        self.pushButton_7 = QPushButton(self.tab)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(10, 120, 331, 41))
        self.pushButton_7.setFont(font1)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet(u"background-color: rgb(255, 246, 219);")
        self.comboBox_3 = QComboBox(self.tab)
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(190, 70, 151, 31))
        self.comboBox_3.setFont(font1)
        self.comboBox_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.comboBox_5 = QComboBox(self.tab_2)
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(190, 70, 151, 31))
        self.comboBox_5.setFont(font1)
        self.comboBox_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton_8 = QPushButton(self.tab_2)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(10, 120, 331, 41))
        self.pushButton_8.setFont(font1)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet(u"background-color: rgb(255, 246, 219);")
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 50, 181, 61))
        self.label_18.setFont(font1)
        self.label_18.setWordWrap(True)
        self.comboBox_4 = QComboBox(self.tab_2)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(160, 20, 181, 31))
        self.comboBox_4.setFont(font1)
        self.comboBox_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 20, 161, 31))
        self.label_17.setFont(font1)
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox_3 = QGroupBox(self.page_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(200, 250, 361, 351))
        self.groupBox_3.setFont(font)
        self.label_19 = QLabel(self.groupBox_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 30, 161, 31))
        font3 = QFont()
        font3.setBold(False)
        self.label_19.setFont(font3)
        self.comboBox_6 = QComboBox(self.groupBox_3)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(160, 30, 181, 31))
        self.comboBox_6.setFont(font2)
        self.comboBox_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_7 = QComboBox(self.groupBox_3)
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(190, 80, 151, 31))
        self.comboBox_7.setFont(font2)
        self.comboBox_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_20 = QLabel(self.groupBox_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 60, 181, 61))
        self.label_20.setFont(font3)
        self.label_20.setWordWrap(True)
        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 120, 261, 41))
        self.label_21.setFont(font3)
        self.label_22 = QLabel(self.groupBox_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 150, 261, 41))
        self.label_22.setFont(font3)
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 180, 261, 41))
        self.label_23.setFont(font3)
        self.label_24 = QLabel(self.groupBox_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 210, 261, 41))
        self.label_24.setFont(font3)
        self.label_25 = QLabel(self.groupBox_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 240, 261, 41))
        self.label_25.setFont(font3)
        self.label_26 = QLabel(self.groupBox_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 270, 261, 41))
        self.label_26.setFont(font3)
        self.label_27 = QLabel(self.groupBox_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 300, 261, 41))
        self.label_27.setFont(font3)
        self.groupBox_4 = QGroupBox(self.page_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(200, 620, 361, 231))
        self.groupBox_4.setFont(font)
        self.label_28 = QLabel(self.groupBox_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 70, 161, 31))
        self.label_28.setFont(font3)
        self.comboBox_8 = QComboBox(self.groupBox_4)
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.comboBox_8.setGeometry(QRect(160, 70, 181, 31))
        self.comboBox_8.setFont(font2)
        self.comboBox_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_29 = QLabel(self.groupBox_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 120, 201, 41))
        self.label_29.setFont(font3)
        self.label_30 = QLabel(self.groupBox_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 150, 341, 41))
        self.label_30.setFont(font3)
        self.comboBox_9 = QComboBox(self.groupBox_4)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")
        self.comboBox_9.setGeometry(QRect(160, 30, 181, 31))
        self.comboBox_9.setFont(font2)
        self.comboBox_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_31 = QLabel(self.groupBox_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 30, 161, 31))
        self.label_31.setFont(font3)
        self.pushButton_9 = QPushButton(self.groupBox_4)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(10, 190, 331, 31))
        self.pushButton_9.setFont(font1)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet(u"background-color: rgb(255, 246, 219);")
        self.frame = QFrame(self.page_3)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(580, 20, 641, 831))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.tableWidget_3 = QTableWidget(self.page_3)
        if (self.tableWidget_3.columnCount() < 2):
            self.tableWidget_3.setColumnCount(2)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem10)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(10, 100, 181, 751))
        self.tableWidget_3.setFont(font1)
        self.tableWidget_3.setFrameShadow(QFrame.Plain)
        self.tableWidget_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setAutoScroll(True)
        self.tableWidget_3.setAlternatingRowColors(True)
        self.tableWidget_3.setTextElideMode(Qt.ElideNone)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_3.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.label_35 = QLabel(self.page_3)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 70, 91, 31))
        self.label_35.setFont(font1)
        self.label_35.setFrameShape(QFrame.Box)
        self.label_35.setAlignment(Qt.AlignCenter)
        self.label_36 = QLabel(self.page_3)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(100, 70, 91, 31))
        self.label_36.setFont(font1)
        self.label_36.setFrameShape(QFrame.Box)
        self.label_36.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.frame_2 = QFrame(self.page_4)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(20, 20, 1191, 821))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.label_32 = QLabel(self.frame_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(830, 410, 71, 41))
        self.label_32.setFont(font1)
        self.label_32.setFrameShape(QFrame.Box)
        self.label_32.setLineWidth(1)
        self.label_32.setAlignment(Qt.AlignCenter)
        self.label_33 = QLabel(self.frame_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(890, 380, 21, 31))
        self.label_33.setFont(font1)
        self.label_33.setFrameShape(QFrame.Box)
        self.label_33.setLineWidth(1)
        self.label_33.setAlignment(Qt.AlignCenter)
        self.label_34 = QLabel(self.frame_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(900, 350, 21, 31))
        self.label_34.setFont(font1)
        self.label_34.setFrameShape(QFrame.Box)
        self.label_34.setLineWidth(1)
        self.label_34.setAlignment(Qt.AlignCenter)
        self.label_37 = QLabel(self.frame_2)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(720, 300, 31, 21))
        self.label_37.setFont(font1)
        self.label_37.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_37.setFrameShape(QFrame.Box)
        self.label_37.setLineWidth(1)
        self.label_37.setAlignment(Qt.AlignCenter)
        self.label_38 = QLabel(self.frame_2)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(740, 280, 31, 21))
        self.label_38.setFont(font1)
        self.label_38.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_38.setFrameShape(QFrame.Box)
        self.label_38.setLineWidth(1)
        self.label_38.setAlignment(Qt.AlignCenter)
        self.label_39 = QLabel(self.frame_2)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(760, 260, 31, 21))
        self.label_39.setFont(font1)
        self.label_39.setStyleSheet(u"background-color: rgb(255, 106, 106);\n"
"background-color: rgb(255, 160, 160);")
        self.label_39.setFrameShape(QFrame.Box)
        self.label_39.setLineWidth(1)
        self.label_39.setAlignment(Qt.AlignCenter)
        self.label_40 = QLabel(self.frame_2)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(780, 240, 31, 21))
        self.label_40.setFont(font1)
        self.label_40.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_40.setFrameShape(QFrame.Box)
        self.label_40.setLineWidth(1)
        self.label_40.setAlignment(Qt.AlignCenter)
        self.label_41 = QLabel(self.frame_2)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(800, 220, 31, 21))
        self.label_41.setFont(font1)
        self.label_41.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_41.setFrameShape(QFrame.Box)
        self.label_41.setLineWidth(1)
        self.label_41.setAlignment(Qt.AlignCenter)
        self.label_42 = QLabel(self.frame_2)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(830, 210, 31, 21))
        self.label_42.setFont(font1)
        self.label_42.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_42.setFrameShape(QFrame.Box)
        self.label_42.setLineWidth(1)
        self.label_42.setAlignment(Qt.AlignCenter)
        self.label_43 = QLabel(self.frame_2)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(860, 220, 31, 21))
        self.label_43.setFont(font1)
        self.label_43.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_43.setFrameShape(QFrame.Box)
        self.label_43.setLineWidth(1)
        self.label_43.setAlignment(Qt.AlignCenter)
        self.label_44 = QLabel(self.frame_2)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(890, 230, 21, 31))
        self.label_44.setFont(font1)
        self.label_44.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_44.setFrameShape(QFrame.Box)
        self.label_44.setLineWidth(1)
        self.label_44.setAlignment(Qt.AlignCenter)
        self.label_45 = QLabel(self.frame_2)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(910, 250, 21, 31))
        self.label_45.setFont(font1)
        self.label_45.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_45.setFrameShape(QFrame.Box)
        self.label_45.setLineWidth(1)
        self.label_45.setAlignment(Qt.AlignCenter)
        self.label_46 = QLabel(self.frame_2)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(910, 320, 21, 31))
        self.label_46.setFont(font1)
        self.label_46.setFrameShape(QFrame.Box)
        self.label_46.setLineWidth(1)
        self.label_46.setAlignment(Qt.AlignCenter)
        self.label_47 = QLabel(self.frame_2)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(880, 290, 31, 21))
        self.label_47.setFont(font1)
        self.label_47.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_47.setFrameShape(QFrame.Box)
        self.label_47.setLineWidth(1)
        self.label_47.setAlignment(Qt.AlignCenter)
        self.label_48 = QLabel(self.frame_2)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(860, 310, 31, 21))
        self.label_48.setFont(font1)
        self.label_48.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_48.setFrameShape(QFrame.Box)
        self.label_48.setLineWidth(1)
        self.label_48.setAlignment(Qt.AlignCenter)
        self.label_49 = QLabel(self.frame_2)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(830, 310, 31, 21))
        self.label_49.setFont(font1)
        self.label_49.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_49.setFrameShape(QFrame.Box)
        self.label_49.setLineWidth(1)
        self.label_49.setAlignment(Qt.AlignCenter)
        self.label_50 = QLabel(self.frame_2)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(810, 330, 31, 21))
        self.label_50.setFont(font1)
        self.label_50.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_50.setFrameShape(QFrame.Box)
        self.label_50.setLineWidth(1)
        self.label_50.setAlignment(Qt.AlignCenter)
        self.label_51 = QLabel(self.frame_2)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(780, 330, 31, 21))
        self.label_51.setFont(font1)
        self.label_51.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_51.setFrameShape(QFrame.Box)
        self.label_51.setLineWidth(1)
        self.label_51.setAlignment(Qt.AlignCenter)
        self.label_52 = QLabel(self.frame_2)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(750, 330, 31, 21))
        self.label_52.setFont(font1)
        self.label_52.setStyleSheet(u"background-color: rgb(255, 160, 160);")
        self.label_52.setFrameShape(QFrame.Box)
        self.label_52.setLineWidth(1)
        self.label_52.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.stackedWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_6.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1303, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Schedule", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Train Status", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Track Status", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Ariel Transit View", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Transit Schedule", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Arrival Time", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Destination", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Track Line", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Train ID", None));
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Automatic Sheduling", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Import Predefined Schedule:", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Select File", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Last Loaded Schedule:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Schedule-02-28-2021.xlsx", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Throughput (Tickets/Hour)", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Manual Scheduling", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Select Destination:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Input Arrival Time:", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Dormont", None))

        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"19:00", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Dispatch", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"60", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"145", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Green", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"23", None))
        ___qtablewidgetitem4 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Train ID", None));
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Destination", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Line", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Current Position", None));
        ___qtablewidgetitem8 = self.tableWidget_2.horizontalHeaderItem(4)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Arrival Time", None));
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Closed Blocks", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Specify Track Line:", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Green", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Red", None))

        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Specify Track Block ID:", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Close Block", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"106", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Close Track Blocks", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("MainWindow", u"106", None))

        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Reopen Block", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Specify Track Block ID:", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"Green", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"Red", None))

        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Specify Track Line:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Reopen Track Blocks", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Block Status", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Specify Track Line:", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("MainWindow", u"Green", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("MainWindow", u"Red", None))

        self.comboBox_7.setItemText(0, QCoreApplication.translate("MainWindow", u"106", None))

        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Specify Track Block ID:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Section: V", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Block Length: 164.04 ft", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Block Grade: 0%", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Speed Limit: 37.38 mph", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Cumulative Elevation: 0 ft", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Time to Traverse: 3 Sec", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Status: Open", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Switch Status", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Specify Switch ID:", None))
        self.comboBox_8.setItemText(0, QCoreApplication.translate("MainWindow", u"4", None))

        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Switch Position:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Green Block 48 & Green Block 49", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("MainWindow", u"Green", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("MainWindow", u"Red", None))

        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Specify Track Line:", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Toggle Switch State", None))
        ___qtablewidgetitem9 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Line", None));
        ___qtablewidgetitem10 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Block ID", None));
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Block ID", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Yard", None))
        self.label_33.setText("")
        self.label_34.setText("")
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.label_46.setText("")
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"15", None))
    # retranslateUi

