# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'trackUIdesign.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1125, 798)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-10, 0, 1131, 841))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.LineBox = QGroupBox(self.tab)
        self.LineBox.setObjectName(u"LineBox")
        self.LineBox.setEnabled(True)
        self.LineBox.setGeometry(QRect(10, 10, 371, 131))
        self.LineBox.setAutoFillBackground(False)
        self.trackSelector = QLineEdit(self.LineBox)
        self.trackSelector.setObjectName(u"trackSelector")
        self.trackSelector.setGeometry(QRect(10, 60, 191, 22))
        self.label_17 = QLabel(self.LineBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 30, 201, 31))
        self.getTrackBTN = QPushButton(self.LineBox)
        self.getTrackBTN.setObjectName(u"getTrackBTN")
        self.getTrackBTN.setGeometry(QRect(10, 90, 191, 28))
        self.trackSelectorValid = QLabel(self.LineBox)
        self.trackSelectorValid.setObjectName(u"trackSelectorValid")
        self.trackSelectorValid.setGeometry(QRect(210, 60, 201, 31))
        self.trackBox = QGroupBox(self.tab)
        self.trackBox.setObjectName(u"trackBox")
        self.trackBox.setGeometry(QRect(10, 140, 371, 621))
        self.label_13 = QLabel(self.trackBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 20, 261, 441))
        self.label_13.setMaximumSize(QSize(261, 450))
        self.label_13.setScaledContents(True)
        self.selTrackSW = QLabel(self.trackBox)
        self.selTrackSW.setObjectName(u"selTrackSW")
        self.selTrackSW.setGeometry(QRect(310, 40, 55, 31))
        self.selTrackSW.setMaximumSize(QSize(55, 31))
        self.selTrackCross = QLabel(self.trackBox)
        self.selTrackCross.setObjectName(u"selTrackCross")
        self.selTrackCross.setGeometry(QRect(310, 70, 55, 31))
        self.selTrackCross.setMaximumSize(QSize(55, 31))
        self.selTrackSpeed = QLCDNumber(self.trackBox)
        self.selTrackSpeed.setObjectName(u"selTrackSpeed")
        self.selTrackSpeed.setGeometry(QRect(253, 110, 71, 31))
        self.label_14 = QLabel(self.trackBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(330, 110, 61, 21))
        self.selTrackHeater = QLabel(self.trackBox)
        self.selTrackHeater.setObjectName(u"selTrackHeater")
        self.selTrackHeater.setGeometry(QRect(300, 170, 61, 31))
        self.selTrackHeater.setMaximumSize(QSize(61, 31))
        self.selTrackBranch = QLabel(self.trackBox)
        self.selTrackBranch.setObjectName(u"selTrackBranch")
        self.selTrackBranch.setGeometry(QRect(310, 200, 55, 31))
        self.selTrackBranch.setMaximumSize(QSize(55, 31))
        self.trackStatusBox = QGroupBox(self.trackBox)
        self.trackStatusBox.setObjectName(u"trackStatusBox")
        self.trackStatusBox.setGeometry(QRect(10, 450, 351, 111))
        self.label_15 = QLabel(self.trackStatusBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 0, 131, 211))
        self.selTrackRailStat = QLabel(self.trackStatusBox)
        self.selTrackRailStat.setObjectName(u"selTrackRailStat")
        self.selTrackRailStat.setGeometry(QRect(280, 20, 55, 31))
        self.selTrackCircStat = QLabel(self.trackStatusBox)
        self.selTrackCircStat.setObjectName(u"selTrackCircStat")
        self.selTrackCircStat.setGeometry(QRect(280, 50, 55, 31))
        self.selTrackPowerStat = QLabel(self.trackStatusBox)
        self.selTrackPowerStat.setObjectName(u"selTrackPowerStat")
        self.selTrackPowerStat.setGeometry(QRect(280, 80, 55, 31))
        self.trackSignalBox = QGroupBox(self.trackBox)
        self.trackSignalBox.setObjectName(u"trackSignalBox")
        self.trackSignalBox.setGeometry(QRect(10, 560, 351, 51))
        self.sigGo = QRadioButton(self.trackSignalBox)
        self.sigGo.setObjectName(u"sigGo")
        self.sigGo.setGeometry(QRect(10, 20, 95, 20))
        self.sigGo.setCheckable(True)
        self.sigSlow = QRadioButton(self.trackSignalBox)
        self.sigSlow.setObjectName(u"sigSlow")
        self.sigSlow.setGeometry(QRect(120, 20, 95, 20))
        self.sigStop = QRadioButton(self.trackSignalBox)
        self.sigStop.setObjectName(u"sigStop")
        self.sigStop.setGeometry(QRect(240, 20, 95, 20))
        self.selTrackSection = QLabel(self.trackBox)
        self.selTrackSection.setObjectName(u"selTrackSection")
        self.selTrackSection.setGeometry(QRect(310, 16, 80, 31))
        self.selTrackSection.setMaximumSize(QSize(80, 31))
        self.selTrackGrade = QLabel(self.trackBox)
        self.selTrackGrade.setObjectName(u"selTrackGrade")
        self.selTrackGrade.setGeometry(QRect(300, 140, 55, 31))
        self.selTrackGrade.setMaximumSize(QSize(55, 31))
        self.selTrackStation = QLabel(self.trackBox)
        self.selTrackStation.setObjectName(u"selTrackStation")
        self.selTrackStation.setGeometry(QRect(270, 230, 111, 31))
        self.selTrackStation.setMaximumSize(QSize(200, 31))
        self.selTrackStation.setWordWrap(False)
        self.selTrackUnderground = QLabel(self.trackBox)
        self.selTrackUnderground.setObjectName(u"selTrackUnderground")
        self.selTrackUnderground.setGeometry(QRect(310, 300, 55, 31))
        self.selTrackUnderground.setMaximumSize(QSize(55, 31))
        self.selTrackStationSide = QLabel(self.trackBox)
        self.selTrackStationSide.setObjectName(u"selTrackStationSide")
        self.selTrackStationSide.setGeometry(QRect(290, 270, 91, 31))
        self.selTrackStationSide.setMaximumSize(QSize(91, 31))
        self.selTrackGrade_2 = QLabel(self.trackBox)
        self.selTrackGrade_2.setObjectName(u"selTrackGrade_2")
        self.selTrackGrade_2.setGeometry(QRect(320, 140, 20, 31))
        self.selTrackGrade_2.setMaximumSize(QSize(55, 31))
        self.selTrackDirection = QLabel(self.trackBox)
        self.selTrackDirection.setObjectName(u"selTrackDirection")
        self.selTrackDirection.setGeometry(QRect(289, 340, 75, 31))
        self.selTrackDirection.setMaximumSize(QSize(75, 31))
        self.selTrackElevation = QLabel(self.trackBox)
        self.selTrackElevation.setObjectName(u"selTrackElevation")
        self.selTrackElevation.setGeometry(QRect(310, 370, 55, 31))
        self.selTrackElevation.setMaximumSize(QSize(55, 31))
        self.selTrackUnderground_3 = QLabel(self.trackBox)
        self.selTrackUnderground_3.setObjectName(u"selTrackUnderground_3")
        self.selTrackUnderground_3.setGeometry(QRect(335, 370, 21, 31))
        self.selTrackUnderground_3.setMaximumSize(QSize(55, 31))
        self.selTrackUnderground_4 = QLabel(self.trackBox)
        self.selTrackUnderground_4.setObjectName(u"selTrackUnderground_4")
        self.selTrackUnderground_4.setGeometry(QRect(300, 400, 55, 31))
        self.selTrackUnderground_4.setMaximumSize(QSize(55, 31))
        self.selTrackElevationCumulative = QLabel(self.trackBox)
        self.selTrackElevationCumulative.setObjectName(u"selTrackElevationCumulative")
        self.selTrackElevationCumulative.setGeometry(QRect(310, 400, 55, 31))
        self.selTrackElevationCumulative.setMaximumSize(QSize(55, 31))
        self.waysideBox = QGroupBox(self.tab)
        self.waysideBox.setObjectName(u"waysideBox")
        self.waysideBox.setGeometry(QRect(700, 180, 411, 161))
        self.wayCommandedSpeed = QLCDNumber(self.waysideBox)
        self.wayCommandedSpeed.setObjectName(u"wayCommandedSpeed")
        self.wayCommandedSpeed.setGeometry(QRect(290, 10, 71, 31))
        self.label = QLabel(self.waysideBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 261, 131))
        self.wayAuthority = QLCDNumber(self.waysideBox)
        self.wayAuthority.setObjectName(u"wayAuthority")
        self.wayAuthority.setGeometry(QRect(290, 50, 71, 31))
        self.waySwitch = QLabel(self.waysideBox)
        self.waySwitch.setObjectName(u"waySwitch")
        self.waySwitch.setGeometry(QRect(294, 80, 91, 31))
        self.waySignal = QLabel(self.waysideBox)
        self.waySignal.setObjectName(u"waySignal")
        self.waySignal.setGeometry(QRect(350, 120, 55, 31))
        self.label_11 = QLabel(self.waysideBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(370, 20, 61, 21))
        self.outputBox = QGroupBox(self.tab)
        self.outputBox.setObjectName(u"outputBox")
        self.outputBox.setGeometry(QRect(700, 350, 411, 411))
        self.label_2 = QLabel(self.outputBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 81, 41))
        self.label_3 = QLabel(self.outputBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 261, 161))
        self.label_4 = QLabel(self.outputBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 200, 81, 41))
        self.label_5 = QLabel(self.outputBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 240, 261, 51))
        self.label_6 = QLabel(self.outputBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 310, 111, 41))
        self.label_7 = QLabel(self.outputBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 360, 261, 31))
        self.trainSpeedLimitO = QLCDNumber(self.outputBox)
        self.trainSpeedLimitO.setObjectName(u"trainSpeedLimitO")
        self.trainSpeedLimitO.setGeometry(QRect(290, 50, 71, 31))
        self.trainAuthorityO = QLCDNumber(self.outputBox)
        self.trainAuthorityO.setObjectName(u"trainAuthorityO")
        self.trainAuthorityO.setGeometry(QRect(290, 110, 71, 31))
        self.trainBeaconO = QLabel(self.outputBox)
        self.trainBeaconO.setObjectName(u"trainBeaconO")
        self.trainBeaconO.setGeometry(QRect(230, 140, 171, 31))
        self.label_8 = QLabel(self.outputBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(370, 60, 61, 21))
        self.ctcTicketO = QLCDNumber(self.outputBox)
        self.ctcTicketO.setObjectName(u"ctcTicketO")
        self.ctcTicketO.setGeometry(QRect(290, 260, 71, 31))
        self.ctcTrackUpO = QLabel(self.outputBox)
        self.ctcTrackUpO.setObjectName(u"ctcTrackUpO")
        self.ctcTrackUpO.setGeometry(QRect(280, 230, 101, 31))
        self.wayOccupiedO = QLabel(self.outputBox)
        self.wayOccupiedO.setObjectName(u"wayOccupiedO")
        self.wayOccupiedO.setGeometry(QRect(290, 350, 91, 31))
        self.train_people_boarding = QLCDNumber(self.outputBox)
        self.train_people_boarding.setObjectName(u"train_people_boarding")
        self.train_people_boarding.setGeometry(QRect(290, 170, 71, 31))
        self.trainCommandedSpeedO = QLCDNumber(self.outputBox)
        self.trainCommandedSpeedO.setObjectName(u"trainCommandedSpeedO")
        self.trainCommandedSpeedO.setGeometry(QRect(290, 80, 71, 31))
        self.label_79 = QLabel(self.outputBox)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(370, 90, 61, 21))
        self.green_line_table = QTableWidget(self.tab)
        self.green_line_table.setObjectName(u"green_line_table")
        self.green_line_table.setGeometry(QRect(420, 160, 241, 601))
        self.green_line_table.setRowCount(0)
        self.green_line_table.setColumnCount(0)
        self.green_line_table.horizontalHeader().setVisible(False)
        self.green_line_table.verticalHeader().setVisible(False)
        self.failBox = QGroupBox(self.tab)
        self.failBox.setObjectName(u"failBox")
        self.failBox.setGeometry(QRect(400, 10, 271, 131))
        self.breakRailBTN = QPushButton(self.failBox)
        self.breakRailBTN.setObjectName(u"breakRailBTN")
        self.breakRailBTN.setGeometry(QRect(50, 20, 161, 31))
        self.breakCircuitBTN = QPushButton(self.failBox)
        self.breakCircuitBTN.setObjectName(u"breakCircuitBTN")
        self.breakCircuitBTN.setGeometry(QRect(50, 60, 161, 31))
        self.breakPowerBTN = QPushButton(self.failBox)
        self.breakPowerBTN.setObjectName(u"breakPowerBTN")
        self.breakPowerBTN.setGeometry(QRect(50, 100, 161, 31))
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(690, 10, 431, 141))
        self.ctcTrackUpO_2 = QLabel(self.groupBox)
        self.ctcTrackUpO_2.setObjectName(u"ctcTrackUpO_2")
        self.ctcTrackUpO_2.setGeometry(QRect(10, 10, 111, 71))
        self.ctcTrackUpO_2.setWordWrap(True)
        self.ambTemp = QLCDNumber(self.groupBox)
        self.ambTemp.setObjectName(u"ambTemp")
        self.ambTemp.setGeometry(QRect(130, 30, 71, 31))
        self.tempSelector = QLineEdit(self.groupBox)
        self.tempSelector.setObjectName(u"tempSelector")
        self.tempSelector.setGeometry(QRect(150, 90, 191, 22))
        self.ctcTrackUpO_3 = QLabel(self.groupBox)
        self.ctcTrackUpO_3.setObjectName(u"ctcTrackUpO_3")
        self.ctcTrackUpO_3.setGeometry(QRect(9, 90, 151, 31))
        self.tempSelectorValid = QLabel(self.groupBox)
        self.tempSelectorValid.setObjectName(u"tempSelectorValid")
        self.tempSelectorValid.setGeometry(QRect(220, 110, 81, 31))
        self.heaterToggleBTN = QPushButton(self.groupBox)
        self.heaterToggleBTN.setObjectName(u"heaterToggleBTN")
        self.heaterToggleBTN.setGeometry(QRect(290, 20, 111, 51))
        self.setTempBTN = QPushButton(self.groupBox)
        self.setTempBTN.setObjectName(u"setTempBTN")
        self.setTempBTN.setGeometry(QRect(350, 90, 81, 21))
        self.selTrackRailStat_2 = QLabel(self.groupBox)
        self.selTrackRailStat_2.setObjectName(u"selTrackRailStat_2")
        self.selTrackRailStat_2.setGeometry(QRect(220, 30, 55, 31))
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.outputBox_4 = QGroupBox(self.tab_3)
        self.outputBox_4.setObjectName(u"outputBox_4")
        self.outputBox_4.setGeometry(QRect(700, 350, 411, 421))
        self.label_65 = QLabel(self.outputBox_4)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(10, 10, 81, 41))
        self.label_66 = QLabel(self.outputBox_4)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(10, 50, 261, 161))
        self.label_67 = QLabel(self.outputBox_4)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(10, 200, 81, 41))
        self.label_68 = QLabel(self.outputBox_4)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(10, 240, 261, 51))
        self.label_69 = QLabel(self.outputBox_4)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 310, 111, 41))
        self.label_70 = QLabel(self.outputBox_4)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(10, 360, 261, 31))
        self.trainSpeedLimitO_red = QLCDNumber(self.outputBox_4)
        self.trainSpeedLimitO_red.setObjectName(u"trainSpeedLimitO_red")
        self.trainSpeedLimitO_red.setGeometry(QRect(290, 50, 71, 31))
        self.trainAuthorityO_red = QLCDNumber(self.outputBox_4)
        self.trainAuthorityO_red.setObjectName(u"trainAuthorityO_red")
        self.trainAuthorityO_red.setGeometry(QRect(290, 110, 71, 31))
        self.trainBeaconO_red = QLabel(self.outputBox_4)
        self.trainBeaconO_red.setObjectName(u"trainBeaconO_red")
        self.trainBeaconO_red.setGeometry(QRect(230, 140, 171, 31))
        self.label_71 = QLabel(self.outputBox_4)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(370, 60, 61, 21))
        self.ctcTicketO_red = QLCDNumber(self.outputBox_4)
        self.ctcTicketO_red.setObjectName(u"ctcTicketO_red")
        self.ctcTicketO_red.setGeometry(QRect(290, 260, 71, 31))
        self.ctcTrackUpO_red = QLabel(self.outputBox_4)
        self.ctcTrackUpO_red.setObjectName(u"ctcTrackUpO_red")
        self.ctcTrackUpO_red.setGeometry(QRect(280, 230, 101, 31))
        self.wayOccupiedO_red = QLabel(self.outputBox_4)
        self.wayOccupiedO_red.setObjectName(u"wayOccupiedO_red")
        self.wayOccupiedO_red.setGeometry(QRect(290, 350, 91, 31))
        self.train_people_boarding_red = QLCDNumber(self.outputBox_4)
        self.train_people_boarding_red.setObjectName(u"train_people_boarding_red")
        self.train_people_boarding_red.setGeometry(QRect(290, 170, 71, 31))
        self.trainCommandedSpeedO_red = QLCDNumber(self.outputBox_4)
        self.trainCommandedSpeedO_red.setObjectName(u"trainCommandedSpeedO_red")
        self.trainCommandedSpeedO_red.setGeometry(QRect(290, 80, 71, 31))
        self.label_78 = QLabel(self.outputBox_4)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(370, 90, 61, 21))
        self.groupBox_7 = QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(690, 10, 431, 141))
        self.ctcTrackUpO_17 = QLabel(self.groupBox_7)
        self.ctcTrackUpO_17.setObjectName(u"ctcTrackUpO_17")
        self.ctcTrackUpO_17.setGeometry(QRect(10, 10, 111, 71))
        self.ctcTrackUpO_17.setWordWrap(True)
        self.ambTemp_red = QLCDNumber(self.groupBox_7)
        self.ambTemp_red.setObjectName(u"ambTemp_red")
        self.ambTemp_red.setGeometry(QRect(130, 30, 71, 31))
        self.tempSelector_red = QLineEdit(self.groupBox_7)
        self.tempSelector_red.setObjectName(u"tempSelector_red")
        self.tempSelector_red.setGeometry(QRect(150, 90, 191, 22))
        self.ctcTrackUpO_18 = QLabel(self.groupBox_7)
        self.ctcTrackUpO_18.setObjectName(u"ctcTrackUpO_18")
        self.ctcTrackUpO_18.setGeometry(QRect(9, 90, 151, 31))
        self.tempSelectorValid_6 = QLabel(self.groupBox_7)
        self.tempSelectorValid_6.setObjectName(u"tempSelectorValid_6")
        self.tempSelectorValid_6.setGeometry(QRect(220, 110, 81, 31))
        self.heaterToggleBTN_red = QPushButton(self.groupBox_7)
        self.heaterToggleBTN_red.setObjectName(u"heaterToggleBTN_red")
        self.heaterToggleBTN_red.setGeometry(QRect(290, 20, 111, 51))
        self.setTempBTN_red = QPushButton(self.groupBox_7)
        self.setTempBTN_red.setObjectName(u"setTempBTN_red")
        self.setTempBTN_red.setGeometry(QRect(350, 90, 81, 21))
        self.selTrackRailStat_11 = QLabel(self.groupBox_7)
        self.selTrackRailStat_11.setObjectName(u"selTrackRailStat_11")
        self.selTrackRailStat_11.setGeometry(QRect(220, 30, 55, 31))
        self.red_line_table = QTableWidget(self.tab_3)
        self.red_line_table.setObjectName(u"red_line_table")
        self.red_line_table.setGeometry(QRect(420, 160, 241, 611))
        self.red_line_table.setRowCount(0)
        self.red_line_table.setColumnCount(0)
        self.red_line_table.horizontalHeader().setVisible(False)
        self.red_line_table.verticalHeader().setVisible(False)
        self.waysideBox_4 = QGroupBox(self.tab_3)
        self.waysideBox_4.setObjectName(u"waysideBox_4")
        self.waysideBox_4.setGeometry(QRect(700, 180, 411, 161))
        self.wayCommandedSpeed_red = QLCDNumber(self.waysideBox_4)
        self.wayCommandedSpeed_red.setObjectName(u"wayCommandedSpeed_red")
        self.wayCommandedSpeed_red.setGeometry(QRect(290, 10, 71, 31))
        self.label_72 = QLabel(self.waysideBox_4)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(10, 20, 261, 131))
        self.wayAuthority_red = QLCDNumber(self.waysideBox_4)
        self.wayAuthority_red.setObjectName(u"wayAuthority_red")
        self.wayAuthority_red.setGeometry(QRect(290, 50, 71, 31))
        self.waySwitch_red = QLabel(self.waysideBox_4)
        self.waySwitch_red.setObjectName(u"waySwitch_red")
        self.waySwitch_red.setGeometry(QRect(294, 80, 91, 31))
        self.waySignal_red = QLabel(self.waysideBox_4)
        self.waySignal_red.setObjectName(u"waySignal_red")
        self.waySignal_red.setGeometry(QRect(350, 120, 55, 31))
        self.label_73 = QLabel(self.waysideBox_4)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(370, 20, 61, 21))
        self.trackBox_4 = QGroupBox(self.tab_3)
        self.trackBox_4.setObjectName(u"trackBox_4")
        self.trackBox_4.setGeometry(QRect(10, 140, 371, 631))
        self.label_74 = QLabel(self.trackBox_4)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(10, 20, 261, 441))
        self.label_74.setMaximumSize(QSize(261, 450))
        self.label_74.setScaledContents(True)
        self.selTrackSW_red = QLabel(self.trackBox_4)
        self.selTrackSW_red.setObjectName(u"selTrackSW_red")
        self.selTrackSW_red.setGeometry(QRect(310, 40, 55, 31))
        self.selTrackSW_red.setMaximumSize(QSize(55, 31))
        self.selTrackCross_red = QLabel(self.trackBox_4)
        self.selTrackCross_red.setObjectName(u"selTrackCross_red")
        self.selTrackCross_red.setGeometry(QRect(310, 70, 55, 31))
        self.selTrackCross_red.setMaximumSize(QSize(55, 31))
        self.selTrackSpeed_red = QLCDNumber(self.trackBox_4)
        self.selTrackSpeed_red.setObjectName(u"selTrackSpeed_red")
        self.selTrackSpeed_red.setGeometry(QRect(253, 110, 71, 31))
        self.label_75 = QLabel(self.trackBox_4)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(330, 110, 61, 21))
        self.selTrackHeater_red = QLabel(self.trackBox_4)
        self.selTrackHeater_red.setObjectName(u"selTrackHeater_red")
        self.selTrackHeater_red.setGeometry(QRect(300, 170, 61, 31))
        self.selTrackHeater_red.setMaximumSize(QSize(61, 31))
        self.selTrackBranch_red = QLabel(self.trackBox_4)
        self.selTrackBranch_red.setObjectName(u"selTrackBranch_red")
        self.selTrackBranch_red.setGeometry(QRect(310, 200, 55, 31))
        self.selTrackBranch_red.setMaximumSize(QSize(55, 31))
        self.trackStatusBox_5 = QGroupBox(self.trackBox_4)
        self.trackStatusBox_5.setObjectName(u"trackStatusBox_5")
        self.trackStatusBox_5.setGeometry(QRect(10, 460, 351, 111))
        self.label_76 = QLabel(self.trackStatusBox_5)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(10, 0, 131, 211))
        self.selTrackRailStat_red = QLabel(self.trackStatusBox_5)
        self.selTrackRailStat_red.setObjectName(u"selTrackRailStat_red")
        self.selTrackRailStat_red.setGeometry(QRect(280, 20, 55, 31))
        self.selTrackCircStat_red = QLabel(self.trackStatusBox_5)
        self.selTrackCircStat_red.setObjectName(u"selTrackCircStat_red")
        self.selTrackCircStat_red.setGeometry(QRect(280, 50, 55, 31))
        self.selTrackPowerStat_red = QLabel(self.trackStatusBox_5)
        self.selTrackPowerStat_red.setObjectName(u"selTrackPowerStat_red")
        self.selTrackPowerStat_red.setGeometry(QRect(280, 80, 55, 31))
        self.trackSignalBox_5 = QGroupBox(self.trackBox_4)
        self.trackSignalBox_5.setObjectName(u"trackSignalBox_5")
        self.trackSignalBox_5.setGeometry(QRect(10, 570, 351, 51))
        self.sigGo_red = QRadioButton(self.trackSignalBox_5)
        self.sigGo_red.setObjectName(u"sigGo_red")
        self.sigGo_red.setGeometry(QRect(10, 20, 95, 20))
        self.sigGo_red.setCheckable(True)
        self.sigSlow_red = QRadioButton(self.trackSignalBox_5)
        self.sigSlow_red.setObjectName(u"sigSlow_red")
        self.sigSlow_red.setGeometry(QRect(120, 20, 95, 20))
        self.sigStop_red = QRadioButton(self.trackSignalBox_5)
        self.sigStop_red.setObjectName(u"sigStop_red")
        self.sigStop_red.setGeometry(QRect(240, 20, 95, 20))
        self.selTrackSection_red = QLabel(self.trackBox_4)
        self.selTrackSection_red.setObjectName(u"selTrackSection_red")
        self.selTrackSection_red.setGeometry(QRect(310, 16, 80, 31))
        self.selTrackSection_red.setMaximumSize(QSize(80, 31))
        self.selTrackGrade_red = QLabel(self.trackBox_4)
        self.selTrackGrade_red.setObjectName(u"selTrackGrade_red")
        self.selTrackGrade_red.setGeometry(QRect(300, 140, 55, 31))
        self.selTrackGrade_red.setMaximumSize(QSize(55, 31))
        self.selTrackStation_red = QLabel(self.trackBox_4)
        self.selTrackStation_red.setObjectName(u"selTrackStation_red")
        self.selTrackStation_red.setGeometry(QRect(270, 230, 111, 31))
        self.selTrackStation_red.setMaximumSize(QSize(200, 31))
        self.selTrackUnderground_red = QLabel(self.trackBox_4)
        self.selTrackUnderground_red.setObjectName(u"selTrackUnderground_red")
        self.selTrackUnderground_red.setGeometry(QRect(310, 300, 55, 31))
        self.selTrackUnderground_red.setMaximumSize(QSize(55, 31))
        self.selTrackStationSide_red = QLabel(self.trackBox_4)
        self.selTrackStationSide_red.setObjectName(u"selTrackStationSide_red")
        self.selTrackStationSide_red.setGeometry(QRect(270, 270, 91, 31))
        self.selTrackStationSide_red.setMaximumSize(QSize(91, 31))
        self.selTrackGrade_10 = QLabel(self.trackBox_4)
        self.selTrackGrade_10.setObjectName(u"selTrackGrade_10")
        self.selTrackGrade_10.setGeometry(QRect(320, 140, 20, 31))
        self.selTrackGrade_10.setMaximumSize(QSize(55, 31))
        self.selTrackDirection_red = QLabel(self.trackBox_4)
        self.selTrackDirection_red.setObjectName(u"selTrackDirection_red")
        self.selTrackDirection_red.setGeometry(QRect(289, 340, 75, 31))
        self.selTrackDirection_red.setMaximumSize(QSize(75, 31))
        self.selTrackElevation_red = QLabel(self.trackBox_4)
        self.selTrackElevation_red.setObjectName(u"selTrackElevation_red")
        self.selTrackElevation_red.setGeometry(QRect(310, 370, 55, 31))
        self.selTrackElevation_red.setMaximumSize(QSize(55, 31))
        self.selTrackUnderground_14 = QLabel(self.trackBox_4)
        self.selTrackUnderground_14.setObjectName(u"selTrackUnderground_14")
        self.selTrackUnderground_14.setGeometry(QRect(335, 370, 21, 31))
        self.selTrackUnderground_14.setMaximumSize(QSize(55, 31))
        self.selTrackUnderground_15 = QLabel(self.trackBox_4)
        self.selTrackUnderground_15.setObjectName(u"selTrackUnderground_15")
        self.selTrackUnderground_15.setGeometry(QRect(300, 400, 55, 31))
        self.selTrackUnderground_15.setMaximumSize(QSize(55, 31))
        self.selTrackElevationCumulative_red = QLabel(self.trackBox_4)
        self.selTrackElevationCumulative_red.setObjectName(u"selTrackElevationCumulative_red")
        self.selTrackElevationCumulative_red.setGeometry(QRect(310, 400, 55, 31))
        self.selTrackElevationCumulative_red.setMaximumSize(QSize(55, 31))
        self.failBox_4 = QGroupBox(self.tab_3)
        self.failBox_4.setObjectName(u"failBox_4")
        self.failBox_4.setGeometry(QRect(400, 10, 271, 131))
        self.breakRailBTN_red = QPushButton(self.failBox_4)
        self.breakRailBTN_red.setObjectName(u"breakRailBTN_red")
        self.breakRailBTN_red.setGeometry(QRect(50, 20, 161, 31))
        self.breakCircuitBTN_red = QPushButton(self.failBox_4)
        self.breakCircuitBTN_red.setObjectName(u"breakCircuitBTN_red")
        self.breakCircuitBTN_red.setGeometry(QRect(50, 60, 161, 31))
        self.breakPowerBTN_red = QPushButton(self.failBox_4)
        self.breakPowerBTN_red.setObjectName(u"breakPowerBTN_red")
        self.breakPowerBTN_red.setGeometry(QRect(50, 100, 161, 31))
        self.LineBox_4 = QGroupBox(self.tab_3)
        self.LineBox_4.setObjectName(u"LineBox_4")
        self.LineBox_4.setEnabled(True)
        self.LineBox_4.setGeometry(QRect(10, 10, 371, 131))
        self.LineBox_4.setAutoFillBackground(False)
        self.trackSelector_red = QLineEdit(self.LineBox_4)
        self.trackSelector_red.setObjectName(u"trackSelector_red")
        self.trackSelector_red.setGeometry(QRect(10, 60, 191, 22))
        self.label_77 = QLabel(self.LineBox_4)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(10, 30, 201, 31))
        self.getTrackBTN_red = QPushButton(self.LineBox_4)
        self.getTrackBTN_red.setObjectName(u"getTrackBTN_red")
        self.getTrackBTN_red.setGeometry(QRect(10, 90, 191, 28))
        self.trackSelectorValid_6 = QLabel(self.LineBox_4)
        self.trackSelectorValid_6.setObjectName(u"trackSelectorValid_6")
        self.trackSelectorValid_6.setGeometry(QRect(210, 60, 201, 31))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 10, 211, 61))
        self.lineEdit = QLineEdit(self.tab_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 60, 113, 22))
        self.getTrackFileBTN = QPushButton(self.tab_2)
        self.getTrackFileBTN.setObjectName(u"getTrackFileBTN")
        self.getTrackFileBTN.setGeometry(QRect(20, 90, 111, 28))
        self.trackFileValid = QLabel(self.tab_2)
        self.trackFileValid.setObjectName(u"trackFileValid")
        self.trackFileValid.setGeometry(QRect(140, 60, 201, 31))
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 130, 141, 101))
        self.upTrackRed = QRadioButton(self.groupBox_2)
        self.upTrackRed.setObjectName(u"upTrackRed")
        self.upTrackRed.setGeometry(QRect(10, 60, 111, 20))
        self.upTrackRed.setChecked(False)
        self.upTrackGreen = QRadioButton(self.groupBox_2)
        self.upTrackGreen.setObjectName(u"upTrackGreen")
        self.upTrackGreen.setGeometry(QRect(10, 30, 95, 20))
        self.upTrackGreen.setChecked(True)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.LineBox.setTitle(QCoreApplication.translate("Dialog", u"Green Line", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Input Track Block Number</span></p></body></html>", None))
        self.getTrackBTN.setText(QCoreApplication.translate("Dialog", u"Get Track", None))
        self.trackSelectorValid.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Valid</span></p></body></html>", None))
        self.trackBox.setTitle(QCoreApplication.translate("Dialog", u"Selected Track Status", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:11pt;\">\u2022 Track Section:</span></p><p><span style=\" font-size:11pt;\">\u2022 Track Switch:</span></p><p><span style=\" font-size:11pt;\">\u2022 Railway Crossing:</span></p><p><span style=\" font-size:11pt;\">\u2022 Rail Speed Limit:</span></p><p><span style=\" font-size:11pt;\">\u2022 Grade:</span></p><p><span style=\" font-size:11pt;\">\u2022 Track Heater Status:</span></p><p><span style=\" font-size:11pt;\">\u2022 Branch:</span></p><p><span style=\" font-size:11pt;\">\u2022 Station:</span></p><p><span style=\" font-size:11pt;\">\u2022 Station Side:</span></p><p><span style=\" font-size:11pt;\">\u2022 Underground:</span></p><p><span style=\" font-size:11pt;\">\u2022 Directionality:</span></p><p><span style=\" font-size:11pt;\">\u2022 Elevation:</span></p><p><span style=\" font-size:11pt;\">\u2022 Cumulative Elevation:</span><br/><br/></p><p><br/></p></body></html>", None))
        self.selTrackSW.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.selTrackCross.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.selTrackHeater.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Off&quot;</span></p></body></html>", None))
        self.selTrackBranch.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.trackStatusBox.setTitle(QCoreApplication.translate("Dialog", u"Track Status", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:11pt;\">\u2022 Rail Status:</span></p><p><span style=\" font-size:11pt;\">\u2022 Circuit Status:</span></p><p><span style=\" font-size:11pt;\">\u2022 Power Status:</span></p><p><br/></p><p><br/></p></body></html>", None))
        self.selTrackRailStat.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">&quot;OK&quot;</span></p></body></html>", None))
        self.selTrackCircStat.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">&quot;OK&quot;</span></p></body></html>", None))
        self.selTrackPowerStat.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">&quot;OK&quot;</span></p></body></html>", None))
        self.trackSignalBox.setTitle(QCoreApplication.translate("Dialog", u"Signals", None))
        self.sigGo.setText(QCoreApplication.translate("Dialog", u"Go", None))
        self.sigSlow.setText(QCoreApplication.translate("Dialog", u"Slow", None))
        self.sigStop.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.selTrackSection.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;A&quot;</span></p></body></html>", None))
        self.selTrackGrade.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;0%&quot;</span></p></body></html>", None))
        self.selTrackStation.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Station 1&quot;</span></p></body></html>", None))
        self.selTrackUnderground.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.selTrackStationSide.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Left/Right&quot;</span></p></body></html>", None))
        self.selTrackGrade_2.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">%</span></p></body></html>", None))
        self.selTrackDirection.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Unidirectional&quot;</span></p></body></html>", None))
        self.selTrackElevation.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;0&quot;</span></p></body></html>", None))
        self.selTrackUnderground_3.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">ft</span></p></body></html>", None))
        self.selTrackUnderground_4.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">ft</span></p></body></html>", None))
        self.selTrackElevationCumulative.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;0&quot;</span></p></body></html>", None))
        self.waysideBox.setTitle(QCoreApplication.translate("Dialog", u"Wayside Status", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:11pt;\">\u2022 Commanded Speed:</span></p><p><span style=\" font-size:11pt;\">\u2022 Authroity:</span></p><p><span style=\" font-size:11pt;\">\u2022 Switch Position:</span></p><p><span style=\" font-size:11pt;\">\u2022 Signal:</span></p><p><br/></p></body></html>", None))
        self.waySwitch.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">North</span></p></body></html>", None))
        self.waySignal.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Go</span></p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.outputBox.setTitle(QCoreApplication.translate("Dialog", u"Outputs", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">To Train:</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u2022 Speed Limit:</span></p><p><span style=\" font-size:10pt;\">\u2022 Commanded Speed:</span></p><p><span style=\" font-size:10pt;\">\u2022 Authroity:</span></p><p><span style=\" font-size:10pt;\">\u2022 Beacon:</span></p><p><span style=\" font-size:10pt;\">\u2022 People Boarding:</span></p><p><br/></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">To CTC:</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u2022 Track Update Status:</span></p><p><span style=\" font-size:10pt;\">\u2022 Ticket Count:</span></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">To Wayside:</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u2022 Occupied:</span></p><p><br/></p></body></html>", None))
        self.trainBeaconO.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Station&quot;</span></p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.ctcTrackUpO.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Updated&quot;</span></p></body></html>", None))
        self.wayOccupiedO.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Open&quot;</span></p></body></html>", None))
        self.label_79.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.failBox.setTitle(QCoreApplication.translate("Dialog", u"Cause a Failure", None))
        self.breakRailBTN.setText(QCoreApplication.translate("Dialog", u"Toggle Break Rail", None))
        self.breakCircuitBTN.setText(QCoreApplication.translate("Dialog", u"Toggle Break Track Circuit", None))
        self.breakPowerBTN.setText(QCoreApplication.translate("Dialog", u"Toggle Break Power Line", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Temperature Status and Controls", None))
        self.ctcTrackUpO_2.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:9pt; text-decoration: underline;\">Current Ambient Temperature:</span></p></body></html>", None))
        self.ctcTrackUpO_3.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:9pt; text-decoration: underline;\">Input Ambient Temp</span></p></body></html>", None))
        self.tempSelectorValid.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:9pt;\">Valid</span></p></body></html>", None))
        self.heaterToggleBTN.setText(QCoreApplication.translate("Dialog", u"Toggle Heater", None))
        self.setTempBTN.setText(QCoreApplication.translate("Dialog", u"Set Temp", None))
        self.selTrackRailStat_2.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-family:'Roboto,arial,sans-serif'; font-size:12pt; color:#4d5156; background-color:#ffffff;\">\u00b0F</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Green Line", None))
        self.outputBox_4.setTitle(QCoreApplication.translate("Dialog", u"Outputs", None))
        self.label_65.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">To Train:</span></p></body></html>", None))
        self.label_66.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u2022 Speed Limit:</span></p><p><span style=\" font-size:10pt;\">\u2022 Commanded Speed:</span></p><p><span style=\" font-size:10pt;\">\u2022 Authroity:</span></p><p><span style=\" font-size:10pt;\">\u2022 Beacon:</span></p><p><span style=\" font-size:10pt;\">\u2022 People Boarding:</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">To CTC:</span></p></body></html>", None))
        self.label_68.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u2022 Track Update Status:</span></p><p><span style=\" font-size:10pt;\">\u2022 Ticket Count:</span></p></body></html>", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">To Wayside:</span></p></body></html>", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u2022 Occupied:</span></p><p><br/></p></body></html>", None))
        self.trainBeaconO_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Station&quot;</span></p></body></html>", None))
        self.label_71.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.ctcTrackUpO_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Updated&quot;</span></p></body></html>", None))
        self.wayOccupiedO_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Open&quot;</span></p></body></html>", None))
        self.label_78.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Dialog", u"Temperature Status and Controls", None))
        self.ctcTrackUpO_17.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:9pt; text-decoration: underline;\">Current Ambient Temperature:</span></p></body></html>", None))
        self.ctcTrackUpO_18.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:9pt; text-decoration: underline;\">Input Ambient Temp</span></p></body></html>", None))
        self.tempSelectorValid_6.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:9pt;\">Valid</span></p></body></html>", None))
        self.heaterToggleBTN_red.setText(QCoreApplication.translate("Dialog", u"Toggle Heater", None))
        self.setTempBTN_red.setText(QCoreApplication.translate("Dialog", u"Set Temp", None))
        self.selTrackRailStat_11.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-family:'Roboto,arial,sans-serif'; font-size:12pt; color:#4d5156; background-color:#ffffff;\">\u00b0F</span></p></body></html>", None))
        self.waysideBox_4.setTitle(QCoreApplication.translate("Dialog", u"Wayside Status", None))
        self.label_72.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:11pt;\">\u2022 Commanded Speed:</span></p><p><span style=\" font-size:11pt;\">\u2022 Authroity:</span></p><p><span style=\" font-size:11pt;\">\u2022 Switch Position:</span></p><p><span style=\" font-size:11pt;\">\u2022 Signal:</span></p><p><br/></p></body></html>", None))
        self.waySwitch_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">North</span></p></body></html>", None))
        self.waySignal_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Go</span></p></body></html>", None))
        self.label_73.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.trackBox_4.setTitle(QCoreApplication.translate("Dialog", u"Selected Track Status", None))
        self.label_74.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:11pt;\">\u2022 Track Section:</span></p><p><span style=\" font-size:11pt;\">\u2022 Track Switch:</span></p><p><span style=\" font-size:11pt;\">\u2022 Railway Crossing:</span></p><p><span style=\" font-size:11pt;\">\u2022 Rail Speed Limit:</span></p><p><span style=\" font-size:11pt;\">\u2022 Grade:</span></p><p><span style=\" font-size:11pt;\">\u2022 Track Heater Status:</span></p><p><span style=\" font-size:11pt;\">\u2022 Branch:</span></p><p><span style=\" font-size:11pt;\">\u2022 Station:</span></p><p><span style=\" font-size:11pt;\">\u2022 Station Side:</span></p><p><span style=\" font-size:11pt;\">\u2022 Underground:</span></p><p><span style=\" font-size:11pt;\">\u2022 Directionality:</span></p><p><span style=\" font-size:11pt;\">\u2022 Elevation:</span></p><p><span style=\" font-size:11pt;\">\u2022 Cumulative Elevation:</span><br/><br/></p><p><br/></p></body></html>", None))
        self.selTrackSW_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.selTrackCross_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.label_75.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">mph</span></p></body></html>", None))
        self.selTrackHeater_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Off&quot;</span></p></body></html>", None))
        self.selTrackBranch_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.trackStatusBox_5.setTitle(QCoreApplication.translate("Dialog", u"Track Status", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:11pt;\">\u2022 Rail Status:</span></p><p><span style=\" font-size:11pt;\">\u2022 Circuit Status:</span></p><p><span style=\" font-size:11pt;\">\u2022 Power Status:</span></p><p><br/></p><p><br/></p></body></html>", None))
        self.selTrackRailStat_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">&quot;OK&quot;</span></p></body></html>", None))
        self.selTrackCircStat_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">&quot;OK&quot;</span></p></body></html>", None))
        self.selTrackPowerStat_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">&quot;OK&quot;</span></p></body></html>", None))
        self.trackSignalBox_5.setTitle(QCoreApplication.translate("Dialog", u"Signals", None))
        self.sigGo_red.setText(QCoreApplication.translate("Dialog", u"Go", None))
        self.sigSlow_red.setText(QCoreApplication.translate("Dialog", u"Slow", None))
        self.sigStop_red.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.selTrackSection_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;A&quot;</span></p></body></html>", None))
        self.selTrackGrade_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;0%&quot;</span></p></body></html>", None))
        self.selTrackStation_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Station 1&quot;</span></p></body></html>", None))
        self.selTrackUnderground_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;No&quot;</span></p></body></html>", None))
        self.selTrackStationSide_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Left/Right&quot;</span></p></body></html>", None))
        self.selTrackGrade_10.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">%</span></p></body></html>", None))
        self.selTrackDirection_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;Unidirectional&quot;</span></p></body></html>", None))
        self.selTrackElevation_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;0&quot;</span></p></body></html>", None))
        self.selTrackUnderground_14.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">ft</span></p></body></html>", None))
        self.selTrackUnderground_15.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">ft</span></p></body></html>", None))
        self.selTrackElevationCumulative_red.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">&quot;0&quot;</span></p></body></html>", None))
        self.failBox_4.setTitle(QCoreApplication.translate("Dialog", u"Cause a Failure", None))
        self.breakRailBTN_red.setText(QCoreApplication.translate("Dialog", u"Toggle Break Rail", None))
        self.breakCircuitBTN_red.setText(QCoreApplication.translate("Dialog", u"Toggle Break Track Circuit", None))
        self.breakPowerBTN_red.setText(QCoreApplication.translate("Dialog", u"Toggle Break Power Line", None))
        self.LineBox_4.setTitle(QCoreApplication.translate("Dialog", u"Red Line", None))
        self.label_77.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Input Track Block Number</span></p></body></html>", None))
        self.getTrackBTN_red.setText(QCoreApplication.translate("Dialog", u"Get Track", None))
        self.trackSelectorValid_6.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Valid</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"Red Line", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Type Rail Document Name</span></p></body></html>", None))
        self.lineEdit.setText(QCoreApplication.translate("Dialog", u"GreenLine.txt", None))
        self.getTrackFileBTN.setText(QCoreApplication.translate("Dialog", u"Load", None))
        self.trackFileValid.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">.</span></p></body></html>", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Choose a Line", None))
        self.upTrackRed.setText(QCoreApplication.translate("Dialog", u"Red Line Line", None))
        self.upTrackGreen.setText(QCoreApplication.translate("Dialog", u"Green Line", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Track Editor", None))
    # retranslateUi

