# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TrainModel.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(789, 399)
        font = QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.tabWidget = QTabWidget(MainWindow)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 781, 401))
        self.passenger = QWidget()
        self.passenger.setObjectName(u"passenger")
        self.label = QLabel(self.passenger)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 361, 31))
        font1 = QFont()
        font1.setPointSize(16)
        self.label.setFont(font1)
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.passenger)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(450, 60, 251, 151))
        self.groupBox.setFont(font)
        self.Door_label_13 = QLabel(self.groupBox)
        self.Door_label_13.setObjectName(u"Door_label_13")
        self.Door_label_13.setGeometry(QRect(30, 40, 91, 21))
        self.Door_label_13.setFont(font)
        self.rightDoorsOutput_4 = QLabel(self.groupBox)
        self.rightDoorsOutput_4.setObjectName(u"rightDoorsOutput_4")
        self.rightDoorsOutput_4.setGeometry(QRect(130, 40, 51, 20))
        self.rightDoorsOutput_4.setFont(font)
        self.Door_label_14 = QLabel(self.groupBox)
        self.Door_label_14.setObjectName(u"Door_label_14")
        self.Door_label_14.setGeometry(QRect(30, 110, 81, 21))
        self.Door_label_14.setFont(font)
        self.leftDoorsOutput_4 = QLabel(self.groupBox)
        self.leftDoorsOutput_4.setObjectName(u"leftDoorsOutput_4")
        self.leftDoorsOutput_4.setGeometry(QRect(120, 110, 51, 20))
        self.leftDoorsOutput_4.setFont(font)
        self.routeOutput = QLabel(self.groupBox)
        self.routeOutput.setObjectName(u"routeOutput")
        self.routeOutput.setGeometry(QRect(130, 130, 101, 21))
        self.routeOutput.setFont(font)
        self.announcmentOutput = QLabel(self.passenger)
        self.announcmentOutput.setObjectName(u"announcmentOutput")
        self.announcmentOutput.setGeometry(QRect(50, 70, 341, 151))
        self.announcmentOutput.setAutoFillBackground(True)
        self.announcmentOutput.setFrameShape(QFrame.Box)
        self.announcmentOutput.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.announcmentOutput.setWordWrap(True)
        self.pushButton = QPushButton(self.passenger)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(54, 242, 651, 81))
        font2 = QFont()
        font2.setPointSize(24)
        self.pushButton.setFont(font2)
        self.pushButton.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.tabWidget.addTab(self.passenger, "")
        self.Murphy = QWidget()
        self.Murphy.setObjectName(u"Murphy")
        self.label_99 = QLabel(self.Murphy)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(260, 50, 111, 20))
        self.label_99.setFont(font)
        self.layoutWidget_18 = QWidget(self.Murphy)
        self.layoutWidget_18.setObjectName(u"layoutWidget_18")
        self.layoutWidget_18.setGeometry(QRect(130, 50, 84, 54))
        self.verticalLayout_22 = QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.brakeFailureOn = QRadioButton(self.layoutWidget_18)
        self.brakeFailureOn.setObjectName(u"brakeFailureOn")
        self.brakeFailureOn.setCheckable(True)
        self.brakeFailureOn.setChecked(False)

        self.verticalLayout_22.addWidget(self.brakeFailureOn)

        self.brakeFailureOff = QRadioButton(self.layoutWidget_18)
        self.brakeFailureOff.setObjectName(u"brakeFailureOff")
        self.brakeFailureOff.setChecked(True)

        self.verticalLayout_22.addWidget(self.brakeFailureOff)

        self.label_100 = QLabel(self.Murphy)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(20, 50, 111, 20))
        self.label_100.setFont(font)
        self.label_101 = QLabel(self.Murphy)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(10, 140, 111, 20))
        self.label_101.setFont(font)
        self.layoutWidget_19 = QWidget(self.Murphy)
        self.layoutWidget_19.setObjectName(u"layoutWidget_19")
        self.layoutWidget_19.setGeometry(QRect(370, 50, 92, 141))
        self.verticalLayout_23 = QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.engine1 = QCheckBox(self.layoutWidget_19)
        self.engine1.setObjectName(u"engine1")

        self.verticalLayout_23.addWidget(self.engine1)

        self.engine2 = QCheckBox(self.layoutWidget_19)
        self.engine2.setObjectName(u"engine2")

        self.verticalLayout_23.addWidget(self.engine2)

        self.engine3 = QCheckBox(self.layoutWidget_19)
        self.engine3.setObjectName(u"engine3")

        self.verticalLayout_23.addWidget(self.engine3)

        self.engine4 = QCheckBox(self.layoutWidget_19)
        self.engine4.setObjectName(u"engine4")

        self.verticalLayout_23.addWidget(self.engine4)

        self.engine5 = QCheckBox(self.layoutWidget_19)
        self.engine5.setObjectName(u"engine5")

        self.verticalLayout_23.addWidget(self.engine5)

        self.layoutWidget_20 = QWidget(self.Murphy)
        self.layoutWidget_20.setObjectName(u"layoutWidget_20")
        self.layoutWidget_20.setGeometry(QRect(130, 140, 84, 54))
        self.verticalLayout_24 = QVBoxLayout(self.layoutWidget_20)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.circuitFailureOn = QRadioButton(self.layoutWidget_20)
        self.circuitFailureOn.setObjectName(u"circuitFailureOn")
        self.circuitFailureOn.setCheckable(True)
        self.circuitFailureOn.setChecked(False)

        self.verticalLayout_24.addWidget(self.circuitFailureOn)

        self.circuitFailureOff = QRadioButton(self.layoutWidget_20)
        self.circuitFailureOff.setObjectName(u"circuitFailureOff")
        self.circuitFailureOff.setChecked(True)

        self.verticalLayout_24.addWidget(self.circuitFailureOff)

        self.brakeFailureOutput_4 = QLabel(self.Murphy)
        self.brakeFailureOutput_4.setObjectName(u"brakeFailureOutput_4")
        self.brakeFailureOutput_4.setGeometry(QRect(660, 70, 51, 20))
        self.brakeFailureOutput_4.setFont(font)
        self.brakeFailureOutput_4.setFrameShape(QFrame.NoFrame)
        self.label_102 = QLabel(self.Murphy)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(550, 100, 111, 20))
        self.label_102.setFont(font)
        self.circuitFailureOutput_4 = QLabel(self.Murphy)
        self.circuitFailureOutput_4.setObjectName(u"circuitFailureOutput_4")
        self.circuitFailureOutput_4.setGeometry(QRect(660, 130, 51, 20))
        self.circuitFailureOutput_4.setFont(font)
        self.circuitFailureOutput_4.setFrameShape(QFrame.NoFrame)
        self.label_103 = QLabel(self.Murphy)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(550, 130, 111, 20))
        self.label_103.setFont(font)
        self.label_104 = QLabel(self.Murphy)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(560, 70, 111, 20))
        self.label_104.setFont(font)
        self.engineFailureOutput_4 = QLabel(self.Murphy)
        self.engineFailureOutput_4.setObjectName(u"engineFailureOutput_4")
        self.engineFailureOutput_4.setGeometry(QRect(660, 100, 51, 20))
        self.engineFailureOutput_4.setFont(font)
        self.engineFailureOutput_4.setFrameShape(QFrame.NoFrame)
        self.groupBox_8 = QGroupBox(self.Murphy)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(0, 10, 491, 221))
        self.groupBox_9 = QGroupBox(self.Murphy)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(510, 10, 251, 221))
        self.tabWidget.addTab(self.Murphy, "")
        self.groupBox_9.raise_()
        self.groupBox_8.raise_()
        self.label_99.raise_()
        self.layoutWidget_18.raise_()
        self.label_100.raise_()
        self.label_101.raise_()
        self.layoutWidget_19.raise_()
        self.layoutWidget_20.raise_()
        self.brakeFailureOutput_4.raise_()
        self.label_102.raise_()
        self.circuitFailureOutput_4.raise_()
        self.label_103.raise_()
        self.label_104.raise_()
        self.engineFailureOutput_4.raise_()
        self.Information = QWidget()
        self.Information.setObjectName(u"Information")
        self.groupBox_10 = QGroupBox(self.Information)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(300, 30, 461, 311))
        self.Door_label_3 = QLabel(self.groupBox_10)
        self.Door_label_3.setObjectName(u"Door_label_3")
        self.Door_label_3.setGeometry(QRect(250, 130, 91, 21))
        self.Door_label_3.setFont(font)
        self.label_16 = QLabel(self.groupBox_10)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 220, 111, 20))
        self.label_16.setFont(font)
        self.label_14 = QLabel(self.groupBox_10)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(60, 160, 111, 20))
        self.label_14.setFont(font)
        self.cLightsOutput = QLabel(self.groupBox_10)
        self.cLightsOutput.setObjectName(u"cLightsOutput")
        self.cLightsOutput.setGeometry(QRect(350, 190, 51, 20))
        self.cLightsOutput.setFont(font)
        self.cLightsOutput.setFrameShape(QFrame.NoFrame)
        self.label_18 = QLabel(self.groupBox_10)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(250, 190, 91, 20))
        self.label_18.setFont(font)
        self.label_17 = QLabel(self.groupBox_10)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(240, 220, 111, 20))
        self.label_17.setFont(font)
        self.circuitFailureOutput = QLabel(self.groupBox_10)
        self.circuitFailureOutput.setObjectName(u"circuitFailureOutput")
        self.circuitFailureOutput.setGeometry(QRect(160, 220, 51, 20))
        self.circuitFailureOutput.setFont(font)
        self.circuitFailureOutput.setFrameShape(QFrame.NoFrame)
        self.tempOuput = QLabel(self.groupBox_10)
        self.tempOuput.setObjectName(u"tempOuput")
        self.tempOuput.setGeometry(QRect(166, 130, 41, 20))
        self.tempOuput.setFont(font)
        self.leftDoorsOutput = QLabel(self.groupBox_10)
        self.leftDoorsOutput.setObjectName(u"leftDoorsOutput")
        self.leftDoorsOutput.setGeometry(QRect(350, 160, 51, 20))
        self.leftDoorsOutput.setFont(font)
        self.label_19 = QLabel(self.groupBox_10)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 130, 131, 20))
        self.label_19.setFont(font)
        self.Door_label_2 = QLabel(self.groupBox_10)
        self.Door_label_2.setObjectName(u"Door_label_2")
        self.Door_label_2.setGeometry(QRect(260, 160, 81, 21))
        self.Door_label_2.setFont(font)
        self.rightDoorsOutput = QLabel(self.groupBox_10)
        self.rightDoorsOutput.setObjectName(u"rightDoorsOutput")
        self.rightDoorsOutput.setGeometry(QRect(350, 130, 51, 20))
        self.rightDoorsOutput.setFont(font)
        self.label_15 = QLabel(self.groupBox_10)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 190, 111, 20))
        self.label_15.setFont(font)
        self.tLightsOutput = QLabel(self.groupBox_10)
        self.tLightsOutput.setObjectName(u"tLightsOutput")
        self.tLightsOutput.setGeometry(QRect(350, 220, 51, 20))
        self.tLightsOutput.setFont(font)
        self.tLightsOutput.setFrameShape(QFrame.NoFrame)
        self.brakeFailureOutput = QLabel(self.groupBox_10)
        self.brakeFailureOutput.setObjectName(u"brakeFailureOutput")
        self.brakeFailureOutput.setGeometry(QRect(160, 160, 51, 20))
        self.brakeFailureOutput.setFont(font)
        self.brakeFailureOutput.setFrameShape(QFrame.NoFrame)
        self.engineFailureOutput = QLabel(self.groupBox_10)
        self.engineFailureOutput.setObjectName(u"engineFailureOutput")
        self.engineFailureOutput.setGeometry(QRect(160, 190, 51, 20))
        self.engineFailureOutput.setFont(font)
        self.engineFailureOutput.setFrameShape(QFrame.NoFrame)
        self.label_29 = QLabel(self.groupBox_10)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(250, 100, 111, 20))
        self.label_29.setFont(font)
        self.label_30 = QLabel(self.groupBox_10)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(30, 100, 141, 20))
        self.label_30.setFont(font)
        self.serviceBreakOuput = QLabel(self.groupBox_10)
        self.serviceBreakOuput.setObjectName(u"serviceBreakOuput")
        self.serviceBreakOuput.setGeometry(QRect(360, 100, 51, 20))
        self.serviceBreakOuput.setFont(font)
        self.serviceBreakOuput.setFrameShape(QFrame.NoFrame)
        self.emergencyBreakOuput = QLabel(self.groupBox_10)
        self.emergencyBreakOuput.setObjectName(u"emergencyBreakOuput")
        self.emergencyBreakOuput.setGeometry(QRect(170, 100, 51, 20))
        self.emergencyBreakOuput.setFont(font)
        self.emergencyBreakOuput.setFrameShape(QFrame.NoFrame)
        self.veloOutput = QLabel(self.groupBox_10)
        self.veloOutput.setObjectName(u"veloOutput")
        self.veloOutput.setGeometry(QRect(100, 70, 131, 20))
        self.veloOutput.setFont(font)
        self.label_31 = QLabel(self.groupBox_10)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(30, 70, 81, 20))
        self.label_31.setFont(font)
        self.length_9 = QLabel(self.groupBox_10)
        self.length_9.setObjectName(u"length_9")
        self.length_9.setGeometry(QRect(250, 70, 111, 21))
        self.accOutput = QLabel(self.groupBox_10)
        self.accOutput.setObjectName(u"accOutput")
        self.accOutput.setGeometry(QRect(350, 70, 111, 21))
        self.groupBox_11 = QGroupBox(self.Information)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 30, 281, 311))
        self.length = QLabel(self.groupBox_11)
        self.length.setObjectName(u"length")
        self.length.setGeometry(QRect(20, 60, 71, 21))
        self.length_2 = QLabel(self.groupBox_11)
        self.length_2.setObjectName(u"length_2")
        self.length_2.setGeometry(QRect(20, 90, 71, 21))
        self.length_3 = QLabel(self.groupBox_11)
        self.length_3.setObjectName(u"length_3")
        self.length_3.setGeometry(QRect(20, 150, 71, 21))
        self.length_4 = QLabel(self.groupBox_11)
        self.length_4.setObjectName(u"length_4")
        self.length_4.setGeometry(QRect(20, 120, 71, 21))
        self.length_5 = QLabel(self.groupBox_11)
        self.length_5.setObjectName(u"length_5")
        self.length_5.setGeometry(QRect(10, 170, 261, 41))
        self.OccupantOutput = QLabel(self.groupBox_11)
        self.OccupantOutput.setObjectName(u"OccupantOutput")
        self.OccupantOutput.setGeometry(QRect(80, 210, 91, 21))
        self.OccupantOutput.setFont(font)
        self.OccupantOutput.setFrameShape(QFrame.NoFrame)
        self.length_6 = QLabel(self.groupBox_11)
        self.length_6.setObjectName(u"length_6")
        self.length_6.setGeometry(QRect(80, 60, 151, 21))
        self.length_7 = QLabel(self.groupBox_11)
        self.length_7.setObjectName(u"length_7")
        self.length_7.setGeometry(QRect(80, 90, 121, 21))
        self.length_8 = QLabel(self.groupBox_11)
        self.length_8.setObjectName(u"length_8")
        self.length_8.setGeometry(QRect(80, 120, 131, 21))
        self.massOutput = QLabel(self.groupBox_11)
        self.massOutput.setObjectName(u"massOutput")
        self.massOutput.setGeometry(QRect(70, 150, 131, 21))
        self.tabWidget.addTab(self.Information, "")

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Station Announcments", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Passenger Information ", None))
        self.Door_label_13.setText(QCoreApplication.translate("MainWindow", u"Right Doors:", None))
        self.rightDoorsOutput_4.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.Door_label_14.setText(QCoreApplication.translate("MainWindow", u"Left Doors:", None))
        self.leftDoorsOutput_4.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.routeOutput.setText("")
        self.announcmentOutput.setText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Emergency Brake", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.passenger), QCoreApplication.translate("MainWindow", u"Passenger", None))
        self.label_99.setText(QCoreApplication.translate("MainWindow", u"Engine Failure:", None))
        self.brakeFailureOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.brakeFailureOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.label_100.setText(QCoreApplication.translate("MainWindow", u"Brake Failure:", None))
        self.label_101.setText(QCoreApplication.translate("MainWindow", u"Circuit Failure:", None))
        self.engine1.setText(QCoreApplication.translate("MainWindow", u"Engine 1", None))
        self.engine2.setText(QCoreApplication.translate("MainWindow", u"Engine 2 ", None))
        self.engine3.setText(QCoreApplication.translate("MainWindow", u"Engine 3 ", None))
        self.engine4.setText(QCoreApplication.translate("MainWindow", u"Engine4", None))
        self.engine5.setText(QCoreApplication.translate("MainWindow", u"Engine 5", None))
        self.circuitFailureOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.circuitFailureOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.brakeFailureOutput_4.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.label_102.setText(QCoreApplication.translate("MainWindow", u"Engine Failure:", None))
        self.circuitFailureOutput_4.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.label_103.setText(QCoreApplication.translate("MainWindow", u"Circuit Failure:", None))
        self.label_104.setText(QCoreApplication.translate("MainWindow", u"Brake Failure:", None))
        self.engineFailureOutput_4.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Failure inputs", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Current Failures", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Murphy), QCoreApplication.translate("MainWindow", u"Murphy", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Controller Information", None))
        self.Door_label_3.setText(QCoreApplication.translate("MainWindow", u"Right Doors:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Circuit Failure:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Brake Failure:", None))
        self.cLightsOutput.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Cabin Lights:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Tunnel Lights:", None))
        self.circuitFailureOutput.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.tempOuput.setText(QCoreApplication.translate("MainWindow", u"70 \u00b0F", None))
        self.leftDoorsOutput.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Temperature(\u00b0F): ", None))
        self.Door_label_2.setText(QCoreApplication.translate("MainWindow", u"Left Doors:", None))
        self.rightDoorsOutput.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Engine Failure:", None))
        self.tLightsOutput.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.brakeFailureOutput.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.engineFailureOutput.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Service Brake:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Emergency Brake:", None))
        self.serviceBreakOuput.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.emergencyBreakOuput.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.veloOutput.setText("")
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Velocity:", None))
        self.length_9.setText(QCoreApplication.translate("MainWindow", u"Acceleration:", None))
        self.accOutput.setText("")
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Other Information", None))
        self.length.setText(QCoreApplication.translate("MainWindow", u"Length:", None))
        self.length_2.setText(QCoreApplication.translate("MainWindow", u"Width:", None))
        self.length_3.setText(QCoreApplication.translate("MainWindow", u"Mass:", None))
        self.length_4.setText(QCoreApplication.translate("MainWindow", u"Height:", None))
        self.length_5.setText(QCoreApplication.translate("MainWindow", u"Occupants : (passengers + 6 crew)", None))
        self.OccupantOutput.setText(QCoreApplication.translate("MainWindow", u"6 people", None))
        self.length_6.setText(QCoreApplication.translate("MainWindow", u"105 feet 8 inches", None))
        self.length_7.setText(QCoreApplication.translate("MainWindow", u"8 feet 8 inches", None))
        self.length_8.setText(QCoreApplication.translate("MainWindow", u"11 feet 2 inches", None))
        self.massOutput.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Information), QCoreApplication.translate("MainWindow", u"Information", None))
    # retranslateUi

