# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TrainModel.ui'
##
## Created by: Qt User Interface Compiler version 6.0.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(789, 399)
        font = QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.tabWidget = QTabWidget(MainWindow)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 781, 401))
        self.passenger = QWidget()
        self.passenger.setObjectName(u"passenger")
        self.label = QLabel(self.passenger)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 361, 31))
        font1 = QFont()
        font1.setPointSize(16)
        self.label.setFont(font1)
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.passenger)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(40, 270, 661, 81))
        font2 = QFont()
        font2.setPointSize(14)
        self.pushButton.setFont(font2)
        self.pushButton.setStyleSheet(u"background-color: rgb(255, 9, 1);")
        self.groupBox = QGroupBox(self.passenger)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(450, 40, 251, 191))
        self.groupBox.setFont(font)
        self.Door_label_13 = QLabel(self.groupBox)
        self.Door_label_13.setObjectName(u"Door_label_13")
        self.Door_label_13.setGeometry(QRect(30, 40, 91, 21))
        self.Door_label_13.setFont(font)
        self.rightDoorsOutput_4 = QLabel(self.groupBox)
        self.rightDoorsOutput_4.setObjectName(u"rightDoorsOutput_4")
        self.rightDoorsOutput_4.setGeometry(QRect(130, 40, 51, 20))
        self.rightDoorsOutput_4.setFont(font)
        self.Door_label_14 = QLabel(self.groupBox)
        self.Door_label_14.setObjectName(u"Door_label_14")
        self.Door_label_14.setGeometry(QRect(40, 70, 81, 21))
        self.Door_label_14.setFont(font)
        self.leftDoorsOutput_4 = QLabel(self.groupBox)
        self.leftDoorsOutput_4.setObjectName(u"leftDoorsOutput_4")
        self.leftDoorsOutput_4.setGeometry(QRect(130, 70, 51, 20))
        self.leftDoorsOutput_4.setFont(font)
        self.label_94 = QLabel(self.groupBox)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(40, 100, 81, 21))
        self.label_94.setFont(font)
        self.Beacon = QLabel(self.groupBox)
        self.Beacon.setObjectName(u"Beacon")
        self.Beacon.setGeometry(QRect(120, 100, 111, 21))
        self.Beacon.setFont(font)
        self.label_95 = QLabel(self.groupBox)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(70, 130, 81, 21))
        self.label_95.setFont(font)
        self.routeOutput = QLabel(self.groupBox)
        self.routeOutput.setObjectName(u"routeOutput")
        self.routeOutput.setGeometry(QRect(130, 130, 101, 21))
        self.routeOutput.setFont(font)
        self.announcmentOutput = QLabel(self.passenger)
        self.announcmentOutput.setObjectName(u"announcmentOutput")
        self.announcmentOutput.setGeometry(QRect(50, 70, 341, 181))
        self.announcmentOutput.setAutoFillBackground(True)
        self.announcmentOutput.setFrameShape(QFrame.Box)
        self.announcmentOutput.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.tabWidget.addTab(self.passenger, "")
        self.Murphy = QWidget()
        self.Murphy.setObjectName(u"Murphy")
        self.label_99 = QLabel(self.Murphy)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(260, 50, 111, 20))
        self.label_99.setFont(font)
        self.layoutWidget_18 = QWidget(self.Murphy)
        self.layoutWidget_18.setObjectName(u"layoutWidget_18")
        self.layoutWidget_18.setGeometry(QRect(130, 50, 84, 54))
        self.verticalLayout_22 = QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.brakeFailureOn = QRadioButton(self.layoutWidget_18)
        self.brakeFailureOn.setObjectName(u"brakeFailureOn")
        self.brakeFailureOn.setCheckable(True)
        self.brakeFailureOn.setChecked(False)

        self.verticalLayout_22.addWidget(self.brakeFailureOn)

        self.brakeFailureOff = QRadioButton(self.layoutWidget_18)
        self.brakeFailureOff.setObjectName(u"brakeFailureOff")
        self.brakeFailureOff.setChecked(True)

        self.verticalLayout_22.addWidget(self.brakeFailureOff)

        self.label_100 = QLabel(self.Murphy)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(20, 50, 111, 20))
        self.label_100.setFont(font)
        self.label_101 = QLabel(self.Murphy)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(10, 140, 111, 20))
        self.label_101.setFont(font)
        self.layoutWidget_19 = QWidget(self.Murphy)
        self.layoutWidget_19.setObjectName(u"layoutWidget_19")
        self.layoutWidget_19.setGeometry(QRect(370, 50, 92, 141))
        self.verticalLayout_23 = QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.engine1 = QCheckBox(self.layoutWidget_19)
        self.engine1.setObjectName(u"engine1")

        self.verticalLayout_23.addWidget(self.engine1)

        self.engine2 = QCheckBox(self.layoutWidget_19)
        self.engine2.setObjectName(u"engine2")

        self.verticalLayout_23.addWidget(self.engine2)

        self.engine3 = QCheckBox(self.layoutWidget_19)
        self.engine3.setObjectName(u"engine3")

        self.verticalLayout_23.addWidget(self.engine3)

        self.engine4 = QCheckBox(self.layoutWidget_19)
        self.engine4.setObjectName(u"engine4")

        self.verticalLayout_23.addWidget(self.engine4)

        self.engine5 = QCheckBox(self.layoutWidget_19)
        self.engine5.setObjectName(u"engine5")

        self.verticalLayout_23.addWidget(self.engine5)

        self.layoutWidget_20 = QWidget(self.Murphy)
        self.layoutWidget_20.setObjectName(u"layoutWidget_20")
        self.layoutWidget_20.setGeometry(QRect(130, 140, 84, 54))
        self.verticalLayout_24 = QVBoxLayout(self.layoutWidget_20)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.circuitFailureOn = QRadioButton(self.layoutWidget_20)
        self.circuitFailureOn.setObjectName(u"circuitFailureOn")
        self.circuitFailureOn.setCheckable(True)
        self.circuitFailureOn.setChecked(False)

        self.verticalLayout_24.addWidget(self.circuitFailureOn)

        self.circuitFailureOff = QRadioButton(self.layoutWidget_20)
        self.circuitFailureOff.setObjectName(u"circuitFailureOff")
        self.circuitFailureOff.setChecked(True)

        self.verticalLayout_24.addWidget(self.circuitFailureOff)

        self.brakeFailureOutput_4 = QLabel(self.Murphy)
        self.brakeFailureOutput_4.setObjectName(u"brakeFailureOutput_4")
        self.brakeFailureOutput_4.setGeometry(QRect(660, 70, 51, 20))
        self.brakeFailureOutput_4.setFont(font)
        self.brakeFailureOutput_4.setFrameShape(QFrame.NoFrame)
        self.label_102 = QLabel(self.Murphy)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(550, 100, 111, 20))
        self.label_102.setFont(font)
        self.circuitFailureOutput_4 = QLabel(self.Murphy)
        self.circuitFailureOutput_4.setObjectName(u"circuitFailureOutput_4")
        self.circuitFailureOutput_4.setGeometry(QRect(660, 130, 51, 20))
        self.circuitFailureOutput_4.setFont(font)
        self.circuitFailureOutput_4.setFrameShape(QFrame.NoFrame)
        self.label_103 = QLabel(self.Murphy)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(550, 130, 111, 20))
        self.label_103.setFont(font)
        self.label_104 = QLabel(self.Murphy)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(560, 70, 111, 20))
        self.label_104.setFont(font)
        self.engineFailureOutput_4 = QLabel(self.Murphy)
        self.engineFailureOutput_4.setObjectName(u"engineFailureOutput_4")
        self.engineFailureOutput_4.setGeometry(QRect(660, 100, 51, 20))
        self.engineFailureOutput_4.setFont(font)
        self.engineFailureOutput_4.setFrameShape(QFrame.NoFrame)
        self.groupBox_8 = QGroupBox(self.Murphy)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(0, 10, 491, 221))
        self.groupBox_9 = QGroupBox(self.Murphy)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(510, 10, 251, 221))
        self.tabWidget.addTab(self.Murphy, "")
        self.groupBox_8.raise_()
        self.label_99.raise_()
        self.layoutWidget_18.raise_()
        self.label_100.raise_()
        self.label_101.raise_()
        self.layoutWidget_19.raise_()
        self.layoutWidget_20.raise_()
        self.brakeFailureOutput_4.raise_()
        self.label_102.raise_()
        self.circuitFailureOutput_4.raise_()
        self.label_103.raise_()
        self.label_104.raise_()
        self.engineFailureOutput_4.raise_()
        self.groupBox_9.raise_()
        self.Information = QWidget()
        self.Information.setObjectName(u"Information")
        self.label_18 = QLabel(self.Information)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(550, 140, 91, 20))
        self.label_18.setFont(font)
        self.authOutput = QLabel(self.Information)
        self.authOutput.setObjectName(u"authOutput")
        self.authOutput.setGeometry(QRect(160, 90, 141, 20))
        self.authOutput.setFont(font)
        self.label_15 = QLabel(self.Information)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(350, 140, 111, 20))
        self.label_15.setFont(font)
        self.label_28 = QLabel(self.Information)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 120, 161, 21))
        self.label_28.setFont(font)
        self.rightDoorsOutput = QLabel(self.Information)
        self.rightDoorsOutput.setObjectName(u"rightDoorsOutput")
        self.rightDoorsOutput.setGeometry(QRect(650, 80, 51, 20))
        self.rightDoorsOutput.setFont(font)
        self.label_20 = QLabel(self.Information)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(80, 90, 81, 20))
        self.label_20.setFont(font)
        self.label_30 = QLabel(self.Information)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 180, 141, 20))
        self.label_30.setFont(font)
        self.cLightsOutput = QLabel(self.Information)
        self.cLightsOutput.setObjectName(u"cLightsOutput")
        self.cLightsOutput.setGeometry(QRect(650, 140, 51, 20))
        self.cLightsOutput.setFont(font)
        self.cLightsOutput.setFrameShape(QFrame.NoFrame)
        self.label_16 = QLabel(self.Information)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(350, 170, 111, 20))
        self.label_16.setFont(font)
        self.engineFailureOutput = QLabel(self.Information)
        self.engineFailureOutput.setObjectName(u"engineFailureOutput")
        self.engineFailureOutput.setGeometry(QRect(460, 140, 51, 20))
        self.engineFailureOutput.setFont(font)
        self.engineFailureOutput.setFrameShape(QFrame.NoFrame)
        self.tempOuput = QLabel(self.Information)
        self.tempOuput.setObjectName(u"tempOuput")
        self.tempOuput.setGeometry(QRect(466, 80, 41, 20))
        self.tempOuput.setFont(font)
        self.label_31 = QLabel(self.Information)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(90, 60, 81, 20))
        self.label_31.setFont(font)
        self.circuitFailureOutput = QLabel(self.Information)
        self.circuitFailureOutput.setObjectName(u"circuitFailureOutput")
        self.circuitFailureOutput.setGeometry(QRect(460, 170, 51, 20))
        self.circuitFailureOutput.setFont(font)
        self.circuitFailureOutput.setFrameShape(QFrame.NoFrame)
        self.Door_label_3 = QLabel(self.Information)
        self.Door_label_3.setObjectName(u"Door_label_3")
        self.Door_label_3.setGeometry(QRect(550, 80, 91, 21))
        self.Door_label_3.setFont(font)
        self.Door_label_2 = QLabel(self.Information)
        self.Door_label_2.setObjectName(u"Door_label_2")
        self.Door_label_2.setGeometry(QRect(560, 110, 81, 21))
        self.Door_label_2.setFont(font)
        self.veloOutput = QLabel(self.Information)
        self.veloOutput.setObjectName(u"veloOutput")
        self.veloOutput.setGeometry(QRect(160, 60, 131, 20))
        self.veloOutput.setFont(font)
        self.emergencyBreakOuput = QLabel(self.Information)
        self.emergencyBreakOuput.setObjectName(u"emergencyBreakOuput")
        self.emergencyBreakOuput.setGeometry(QRect(160, 180, 51, 20))
        self.emergencyBreakOuput.setFont(font)
        self.emergencyBreakOuput.setFrameShape(QFrame.NoFrame)
        self.cmdSpeedOutput = QLabel(self.Information)
        self.cmdSpeedOutput.setObjectName(u"cmdSpeedOutput")
        self.cmdSpeedOutput.setGeometry(QRect(160, 120, 131, 20))
        self.cmdSpeedOutput.setFont(font)
        self.brakeFailureOutput = QLabel(self.Information)
        self.brakeFailureOutput.setObjectName(u"brakeFailureOutput")
        self.brakeFailureOutput.setGeometry(QRect(460, 110, 51, 20))
        self.brakeFailureOutput.setFont(font)
        self.brakeFailureOutput.setFrameShape(QFrame.NoFrame)
        self.tLightsOutput = QLabel(self.Information)
        self.tLightsOutput.setObjectName(u"tLightsOutput")
        self.tLightsOutput.setGeometry(QRect(650, 170, 51, 20))
        self.tLightsOutput.setFont(font)
        self.tLightsOutput.setFrameShape(QFrame.NoFrame)
        self.label_29 = QLabel(self.Information)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(50, 150, 111, 20))
        self.label_29.setFont(font)
        self.label_17 = QLabel(self.Information)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(540, 170, 111, 20))
        self.label_17.setFont(font)
        self.label_19 = QLabel(self.Information)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(330, 80, 131, 20))
        self.label_19.setFont(font)
        self.label_14 = QLabel(self.Information)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(360, 110, 111, 20))
        self.label_14.setFont(font)
        self.leftDoorsOutput = QLabel(self.Information)
        self.leftDoorsOutput.setObjectName(u"leftDoorsOutput")
        self.leftDoorsOutput.setGeometry(QRect(650, 110, 51, 20))
        self.leftDoorsOutput.setFont(font)
        self.serviceBreakOuput = QLabel(self.Information)
        self.serviceBreakOuput.setObjectName(u"serviceBreakOuput")
        self.serviceBreakOuput.setGeometry(QRect(160, 150, 51, 20))
        self.serviceBreakOuput.setFont(font)
        self.serviceBreakOuput.setFrameShape(QFrame.NoFrame)
        self.groupBox_10 = QGroupBox(self.Information)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(300, 30, 461, 221))
        self.groupBox_11 = QGroupBox(self.Information)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(0, 30, 281, 221))
        self.tabWidget.addTab(self.Information, "")
        self.groupBox_11.raise_()
        self.label_18.raise_()
        self.authOutput.raise_()
        self.label_15.raise_()
        self.label_28.raise_()
        self.rightDoorsOutput.raise_()
        self.label_20.raise_()
        self.label_30.raise_()
        self.cLightsOutput.raise_()
        self.label_16.raise_()
        self.engineFailureOutput.raise_()
        self.tempOuput.raise_()
        self.label_31.raise_()
        self.circuitFailureOutput.raise_()
        self.Door_label_3.raise_()
        self.Door_label_2.raise_()
        self.veloOutput.raise_()
        self.emergencyBreakOuput.raise_()
        self.cmdSpeedOutput.raise_()
        self.brakeFailureOutput.raise_()
        self.tLightsOutput.raise_()
        self.label_29.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.label_14.raise_()
        self.leftDoorsOutput.raise_()
        self.serviceBreakOuput.raise_()
        self.groupBox_10.raise_()
        self.Test = QWidget()
        self.Test.setObjectName(u"Test")
        self.pwrInput = QLineEdit(self.Test)
        self.pwrInput.setObjectName(u"pwrInput")
        self.pwrInput.setGeometry(QRect(190, 90, 71, 20))
        self.pwrInput.setFont(font)
        self.label_2 = QLabel(self.Test)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(130, 90, 47, 13))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.Test)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 120, 81, 20))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.Test)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 140, 161, 31))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.Test)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(90, 180, 101, 16))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.Test)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 210, 141, 16))
        self.label_6.setFont(font)
        self.label_8 = QLabel(self.Test)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(50, 240, 151, 16))
        self.label_8.setFont(font)
        self.authInput = QLineEdit(self.Test)
        self.authInput.setObjectName(u"authInput")
        self.authInput.setGeometry(QRect(190, 120, 71, 20))
        self.authInput.setFont(font)
        self.cmdSpeed = QLineEdit(self.Test)
        self.cmdSpeed.setObjectName(u"cmdSpeed")
        self.cmdSpeed.setGeometry(QRect(190, 150, 71, 20))
        self.cmdSpeed.setFont(font)
        self.speedLimit = QLineEdit(self.Test)
        self.speedLimit.setObjectName(u"speedLimit")
        self.speedLimit.setGeometry(QRect(190, 180, 71, 20))
        self.speedLimit.setFont(font)
        self.accLimit = QLineEdit(self.Test)
        self.accLimit.setObjectName(u"accLimit")
        self.accLimit.setGeometry(QRect(190, 210, 71, 20))
        self.accLimit.setFont(font)
        self.decLimit = QLineEdit(self.Test)
        self.decLimit.setObjectName(u"decLimit")
        self.decLimit.setGeometry(QRect(190, 240, 71, 20))
        self.decLimit.setFont(font)
        self.spinBox = QSpinBox(self.Test)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(200, 50, 42, 22))
        self.spinBox.setFont(font)
        self.spinBox.setValue(70)
        self.label_10 = QLabel(self.Test)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 50, 131, 20))
        self.label_10.setFont(font)
        self.groupBox_2 = QGroupBox(self.Test)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 20, 331, 341))
        self.label_21 = QLabel(self.groupBox_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(260, 70, 47, 13))
        self.label_21.setFont(font)
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(260, 130, 47, 21))
        self.label_22.setFont(font)
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(260, 160, 47, 21))
        self.label_23.setFont(font)
        self.label_24 = QLabel(self.groupBox_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(260, 190, 61, 21))
        self.label_24.setFont(font)
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(260, 220, 61, 21))
        self.label_25.setFont(font)
        self.label_26 = QLabel(self.groupBox_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(246, 30, 41, 20))
        self.label_26.setFont(font)
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(260, 100, 47, 13))
        self.beacInput = QLineEdit(self.groupBox_2)
        self.beacInput.setObjectName(u"beacInput")
        self.beacInput.setGeometry(QRect(80, 270, 241, 21))
        self.beacInput.setFont(font)
        self.label_97 = QLabel(self.groupBox_2)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(20, 301, 61, 31))
        self.label_97.setFont(font)
        self.label_96 = QLabel(self.groupBox_2)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(20, 261, 61, 31))
        self.label_96.setFont(font)
        self.routeInput = QLineEdit(self.groupBox_2)
        self.routeInput.setObjectName(u"routeInput")
        self.routeInput.setGeometry(QRect(80, 301, 241, 21))
        self.routeInput.setFont(font)
        self.label_98 = QLabel(self.Test)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(370, 50, 121, 20))
        self.label_98.setFont(font)
        self.announcmentsInput = QLineEdit(self.Test)
        self.announcmentsInput.setObjectName(u"announcmentsInput")
        self.announcmentsInput.setGeometry(QRect(500, 50, 241, 21))
        self.announcmentsInput.setFont(font)
        self.groupBox_7 = QGroupBox(self.Test)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(360, 20, 401, 341))
        self.widget = QWidget(self.groupBox_7)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(330, 80, 60, 52))
        self.verticalLayout_7 = QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.leftDoorOpen = QRadioButton(self.widget)
        self.leftDoorsGroup = QButtonGroup(MainWindow)
        self.leftDoorsGroup.setObjectName(u"leftDoorsGroup")
        self.leftDoorsGroup.addButton(self.leftDoorOpen)
        self.leftDoorOpen.setObjectName(u"leftDoorOpen")

        self.verticalLayout_7.addWidget(self.leftDoorOpen)

        self.leftDoorsClose = QRadioButton(self.widget)
        self.leftDoorsGroup.addButton(self.leftDoorsClose)
        self.leftDoorsClose.setObjectName(u"leftDoorsClose")
        self.leftDoorsClose.setChecked(True)

        self.verticalLayout_7.addWidget(self.leftDoorsClose)

        self.Door_label_4 = QLabel(self.groupBox_7)
        self.Door_label_4.setObjectName(u"Door_label_4")
        self.Door_label_4.setGeometry(QRect(220, 80, 91, 20))
        self.Door_label_4.setFont(font)
        self.widget1 = QWidget(self.groupBox_7)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(140, 80, 60, 52))
        self.verticalLayout = QVBoxLayout(self.widget1)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.rightDoorsOpen = QRadioButton(self.widget1)
        self.rightDoorsGroup = QButtonGroup(MainWindow)
        self.rightDoorsGroup.setObjectName(u"rightDoorsGroup")
        self.rightDoorsGroup.addButton(self.rightDoorsOpen)
        self.rightDoorsOpen.setObjectName(u"rightDoorsOpen")

        self.verticalLayout.addWidget(self.rightDoorsOpen)

        self.rightDoorClose = QRadioButton(self.widget1)
        self.rightDoorsGroup.addButton(self.rightDoorClose)
        self.rightDoorClose.setObjectName(u"rightDoorClose")
        self.rightDoorClose.setChecked(True)

        self.verticalLayout.addWidget(self.rightDoorClose)

        self.Door_label = QLabel(self.groupBox_7)
        self.Door_label.setObjectName(u"Door_label")
        self.Door_label.setGeometry(QRect(20, 80, 91, 20))
        self.Door_label.setFont(font)
        self.widget2 = QWidget(self.groupBox_7)
        self.widget2.setObjectName(u"widget2")
        self.widget2.setGeometry(QRect(130, 260, 84, 52))
        self.verticalLayout_2 = QVBoxLayout(self.widget2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.cLightsOn = QRadioButton(self.widget2)
        self.cLightsGroup = QButtonGroup(MainWindow)
        self.cLightsGroup.setObjectName(u"cLightsGroup")
        self.cLightsGroup.addButton(self.cLightsOn)
        self.cLightsOn.setObjectName(u"cLightsOn")
        self.cLightsOn.setChecked(True)

        self.verticalLayout_2.addWidget(self.cLightsOn)

        self.cLightsOff = QRadioButton(self.widget2)
        self.cLightsGroup.addButton(self.cLightsOff)
        self.cLightsOff.setObjectName(u"cLightsOff")

        self.verticalLayout_2.addWidget(self.cLightsOff)

        self.label_7 = QLabel(self.groupBox_7)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 260, 91, 20))
        self.label_7.setFont(font)
        self.label_9 = QLabel(self.groupBox_7)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 180, 111, 20))
        self.label_9.setFont(font)
        self.layoutWidget = QWidget(self.groupBox_7)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(130, 184, 84, 54))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.tLightsOn = QRadioButton(self.layoutWidget)
        self.tLightsGroup = QButtonGroup(MainWindow)
        self.tLightsGroup.setObjectName(u"tLightsGroup")
        self.tLightsGroup.addButton(self.tLightsOn)
        self.tLightsOn.setObjectName(u"tLightsOn")
        self.tLightsOn.setCheckable(True)
        self.tLightsOn.setChecked(False)

        self.verticalLayout_3.addWidget(self.tLightsOn)

        self.tLightsOff = QRadioButton(self.layoutWidget)
        self.tLightsGroup.addButton(self.tLightsOff)
        self.tLightsOff.setObjectName(u"tLightsOff")
        self.tLightsOff.setChecked(True)

        self.verticalLayout_3.addWidget(self.tLightsOff)

        self.widget3 = QWidget(self.groupBox_7)
        self.widget3.setObjectName(u"widget3")
        self.widget3.setGeometry(QRect(270, 180, 96, 79))
        self.verticalLayout_4 = QVBoxLayout(self.widget3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QLabel(self.widget3)
        self.label_12.setObjectName(u"label_12")

        self.verticalLayout_4.addWidget(self.label_12)

        self.serviceBreakOn = QRadioButton(self.widget3)
        self.serviceBrakeGroup = QButtonGroup(MainWindow)
        self.serviceBrakeGroup.setObjectName(u"serviceBrakeGroup")
        self.serviceBrakeGroup.addButton(self.serviceBreakOn)
        self.serviceBreakOn.setObjectName(u"serviceBreakOn")
        self.serviceBreakOn.setChecked(True)

        self.verticalLayout_4.addWidget(self.serviceBreakOn)

        self.serviceBreakOff = QRadioButton(self.widget3)
        self.serviceBrakeGroup.addButton(self.serviceBreakOff)
        self.serviceBreakOff.setObjectName(u"serviceBreakOff")
        self.serviceBreakOff.setChecked(False)

        self.verticalLayout_4.addWidget(self.serviceBreakOff)

        self.tabWidget.addTab(self.Test, "")
        self.groupBox_7.raise_()
        self.groupBox_2.raise_()
        self.pwrInput.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.authInput.raise_()
        self.cmdSpeed.raise_()
        self.speedLimit.raise_()
        self.accLimit.raise_()
        self.decLimit.raise_()
        self.cLightsOn.raise_()
        self.cLightsOff.raise_()
        self.spinBox.raise_()
        self.label_10.raise_()
        self.label_98.raise_()
        self.announcmentsInput.raise_()

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Station Announcments", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Emergency Brake", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Passenger Information ", None))
        self.Door_label_13.setText(QCoreApplication.translate("MainWindow", u"Right Doors:", None))
        self.rightDoorsOutput_4.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.Door_label_14.setText(QCoreApplication.translate("MainWindow", u"Left Doors:", None))
        self.leftDoorsOutput_4.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.label_94.setText(QCoreApplication.translate("MainWindow", u"Next Stop:", None))
        self.Beacon.setText("")
        self.label_95.setText(QCoreApplication.translate("MainWindow", u"Route:", None))
        self.routeOutput.setText("")
        self.announcmentOutput.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.passenger), QCoreApplication.translate("MainWindow", u"Passenger", None))
        self.label_99.setText(QCoreApplication.translate("MainWindow", u"Engine Failure:", None))
        self.brakeFailureOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.brakeFailureOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.label_100.setText(QCoreApplication.translate("MainWindow", u"Brake Failure:", None))
        self.label_101.setText(QCoreApplication.translate("MainWindow", u"Circuit Failure:", None))
        self.engine1.setText(QCoreApplication.translate("MainWindow", u"Engine 1", None))
        self.engine2.setText(QCoreApplication.translate("MainWindow", u"Engine 2 ", None))
        self.engine3.setText(QCoreApplication.translate("MainWindow", u"Engine 3 ", None))
        self.engine4.setText(QCoreApplication.translate("MainWindow", u"Engine4", None))
        self.engine5.setText(QCoreApplication.translate("MainWindow", u"Engine 5", None))
        self.circuitFailureOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.circuitFailureOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.brakeFailureOutput_4.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.label_102.setText(QCoreApplication.translate("MainWindow", u"Engine Failure:", None))
        self.circuitFailureOutput_4.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.label_103.setText(QCoreApplication.translate("MainWindow", u"Circuit Failure:", None))
        self.label_104.setText(QCoreApplication.translate("MainWindow", u"Brake Failure:", None))
        self.engineFailureOutput_4.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Failure inputs", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Current Failures", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Murphy), QCoreApplication.translate("MainWindow", u"Murphy", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Cabin Lights:", None))
        self.authOutput.setText("")
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Engine Failure:", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Commanded Speed:", None))
        self.rightDoorsOutput.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Authority:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Emergency Brake:", None))
        self.cLightsOutput.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Circuit Failure:", None))
        self.engineFailureOutput.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.tempOuput.setText(QCoreApplication.translate("MainWindow", u"70 \u00b0F", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Velocity:", None))
        self.circuitFailureOutput.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.Door_label_3.setText(QCoreApplication.translate("MainWindow", u"Right Doors:", None))
        self.Door_label_2.setText(QCoreApplication.translate("MainWindow", u"Left Doors:", None))
        self.veloOutput.setText("")
        self.emergencyBreakOuput.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.cmdSpeedOutput.setText("")
        self.brakeFailureOutput.setText(QCoreApplication.translate("MainWindow", u"No", None))
        self.tLightsOutput.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Service Brake:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Tunnel Lights:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Temperature(\u00b0F): ", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Brake Failure:", None))
        self.leftDoorsOutput.setText(QCoreApplication.translate("MainWindow", u"Closed", None))
        self.serviceBreakOuput.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Other Outputs", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Controller Outputs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Information), QCoreApplication.translate("MainWindow", u"Information", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Power:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Authority:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Commanded Speed:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Speed Limit:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Acceleration Limit:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Deceleration Limit:", None))
        self.speedLimit.setText(QCoreApplication.translate("MainWindow", u"43.4", None))
        self.accLimit.setText(QCoreApplication.translate("MainWindow", u"4026. 4 ", None))
        self.decLimit.setText(QCoreApplication.translate("MainWindow", u"-21984.6", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Temperature(\u00b0F): ", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Track Inputs", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"kW", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"mph", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"mph", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"m/h^2", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"m/h^2", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"\u00b0F", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Meters", None))
        self.label_97.setText(QCoreApplication.translate("MainWindow", u"Route:", None))
        self.label_96.setText(QCoreApplication.translate("MainWindow", u"Beacon:", None))
        self.label_98.setText(QCoreApplication.translate("MainWindow", u"Announcements:", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Controller Inputs", None))
        self.leftDoorOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.leftDoorsClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.Door_label_4.setText(QCoreApplication.translate("MainWindow", u"Left Doors:", None))
        self.rightDoorsOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.rightDoorClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.Door_label.setText(QCoreApplication.translate("MainWindow", u"Right Doors:", None))
        self.cLightsOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.cLightsOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Cabin Lights:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Tunnel Lights:", None))
        self.tLightsOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.tLightsOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Service Brake", None))
        self.serviceBreakOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.serviceBreakOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Test), QCoreApplication.translate("MainWindow", u"Test", None))
    # retranslateUi

